### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by xgasser** [joomla/joomla-websites#1014]
My webpage recently has these lines of text and trying to figure out if this is a Joomla issue or my web host issue?  

hotshirtsonline.com

Has a bunch of text lines throughout similar to this:

Strict Standards: Non-static method mosMainFrame::sessionCookieValue() should not be called statically, assuming $this from incompatible context in /home/hotshirt/public_html/includes/joomla.php on line 3496
 Thanks for any help,

Brad

**Comment by zero-24** [comment]
Hi @xgasser You are using a version that is out of support atleast since 22 July 2009 it looks like your hoster or yourself updated the PHP Version where the old code did not work anymore without error messages.

Please contact the Joomla Forum at https://forum.joomla.org or better the company that have set up your site so that site can be migrated on the latest Joomla version.

You can find the latest joomla version here: https://downloads.joomla.org/

As this question is not about a joomla.org property i'm going to close this thanks!
