### ISSUE TITLE
[japi] old sites

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1022]
through google search I ended up on the following old sites. Do we still need them? If we do should the copyright and menus be updated?

https://api.joomla.org/1.5/
https://api.joomla.org/11.4/

**Comment by mbabker** [comment]
They are left online for reference purposes but [aren't indexed](https://api.joomla.org/robots.txt).

I also don't have access to the source template files to be able to recompile those areas using the existing templates and I'm honestly not sure what the result would be if we were to try and run the current phpDocumentor build against our current template source.

**Comment by brianteeman** [comment]
That only stops indexing from the date it was added. It doesn't remove existing indexes which is how I found it

**Comment by mbabker** [comment]
IMO there's no harm in keeping the content online.  If someone wants to try and recompile the CMS 1.5.26 and Platform 11.4 docs against the [current template](https://github.com/joomla/api.joomla.org) and make sure things are actually displayed OK, you basically need to configure the current phpDocumentor 2.x release using [this command](https://github.com/joomla/joomla-cms/blob/staging/build.xml#L74-L89).

At this point we're basically doing it all blindly though since at that time the only things in our code repos were the actual production code and the tests directory, so we have no configuration references to work from.

**Comment by mbabker** [comment]
Before the end of the month I intend on taking down these old sections (finally) and redirecting them to a page explaining those sections have been archived and are no longer available.  So that'll address that.

**Comment by Joomv** [comment]
These still seem to be there.

**Comment by mbabker** [comment]
Someone double check my `.htaccess` rule:

```sh
RewriteCond %{REQUEST_URI} ^/(1.5|11.4|12.1)/
RewriteRule (.*) /archived.html [R=301,L,QSA]
```

(Essentially all requests for anything in the `1.5`, `11.4`, and `12.1` subdirectories redirects to a to-be-created `archived.html` file)

Pull requests to https://github.com/joomla/api.joomla.org welcome, otherwise I'll get to it whenever I get to it.

**Comment by conconnl** [comment]
@pe7er @zero-24 
Can you help with this?
