### ISSUE TITLE
[joomla.org] Not appropriate link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1051]
> Help Cpt. Joomla save the puppies of the Siebtlingsgeburt!

This really is inappropriate for all our domains. It looks incredibly childish and amateurish. It doesnt belong on our property. If you really want to enter a competition then do it on a dedicated domain - which is exactly what that silly competition says that you should do.

**Comment by chriswagner0815** [comment]
Hello Brian,
this is an SEO contest in Germany about the artificial keyword "siebtlingsgeburt" to see where we could rank. We are doing this because we want about 700 SEOs and marketing responsible to see that Joomla is still there. 

Regarding the "what the competition says" information: That must be a maltranslation with Google translate. There are others working on their domains for the keyword and this is what the contest is about. 

So we have 2 positive things:
a) joomla.org taking part
b) marketing buzz for the project
if that does not translate into:
c) a success for the visibility of Joomla to you, then I dont know what will.

Hugs from Cologne
Chris

**Comment by Hils** [comment]
Actually, I can't see it on joomla.org - where are you seeing it please? and whereabouts on the page?

**Comment by chriswagner0815** [comment]
Hey Hils,
in the morning it was between 8 and 14 - we can't see it either right now because Google seems to do a big data refresh. We are waiting currently to see what happens.

Chris

**Comment by Hils** [comment]
Thanks for the reply Chris !

Hils

**Comment by brianteeman** [comment]
@hils it is in the footer on every property
<img width="630" alt="screenshotr10-54-36" src="https://user-images.githubusercontent.com/1296369/31170019-798a0ec8-a8f2-11e7-897c-7125bdac3e4f.png">

I still stand by original comments - this is not the place to enter competitions

**Comment by Sandra97** [comment]
We have decided to enter this German SEO contest with the goal to reach influencers and make more people aware of Joomla, as already mentioned by Christopher. You can find on the JCM why we entered this contest. 

FYI, I didn’t agree to create again a new subdomain for just 2 weeks, so we decided to put the page on /3 as this site was already set up for multilingual and also because it allows to work faster and be sure to be ready in time. And I also approved the project of the SEO team. 

And note that all bottom links will be removed in 8 days.

**Comment by Hils** [comment]
Aha so it is quite discreet then... and is only short term - I thought you meant there was a massive graphic-laden module!

**Comment by siebtlingsgeburt** [comment]
We can close this one. AFAIK all links are removed now. 
Joomla is appropiate, adultish and professional again.
