### ISSUE TITLE
email issue

### ISSUE THREAD

**Issue by tmero** [joomla/joomla-websites#1058]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

My joomla.org email address password was just changed and logged into. Not sure if it is someone who is in charge of the google accounts or not, but I'd like to get a fair warning first so I can detach my other accounts that is attached to that email first. (I've had the email for sooo many years) :)  

I am unable to reset my password as it says to contact an admin, but I keep getting notifications via email that someone is logged into my email account.

Thank you.

**Comment by jeckodevelopment** [comment]
Hi Tessa,
since you left the project several months ago. As secretary it's my duty to keep our userbase and accounts clean and as part of the regular cleanup process i was working on joomla.org GSuite stuff.
Since in Google Admin panel you did not access your mailbox for more than 6 months, i was about to delete it and then i remembered that you dealt with Glip and GitHub and thought you should have something about it in your mailbox. Obviously we need to keep record of these negotiations over the years as currently we don't have them, so before the account deletion and docs ownership transfer, there was password change and you came out there for the notification.
So, please contact me privately and i'll reset your password to allow you to recover your account and deal with your stuff. 

Thank you

**Comment by tmero** [comment]
Thanks for letting me log in and fix my twitter account. Everything is good. You can deactivate it now. :) You rock!

**Comment by jeckodevelopment** [comment]
Thank you Tessa! ;)
