### ISSUE TITLE
[demo.joomla.org] Message: Error PHP 5.5.38 is obsolete

### ISSUE THREAD

**Issue by CEWebDesign** [joomla/joomla-websites#1059]
On demo-site https://demo.joomla.org/ click "Launch Test Drive":
Message:
Error
We have detected that your server is using PHP 5.5.38 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 5.6 or later which will receive security updates at least until 2018-12-31. Please ask your host to make PHP 5.6 or a later version the default version for your site. If your host is already PHP 5.6 ready please enable PHP 5.6 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure.

**Comment by Sandra97** [comment]
@kirilhristov Could you give a look? Thanks!

**Comment by kirilhristov** [comment]
Hello, the issue has been fixed. Thanks for reporting!

**Comment by pe7er** [comment]
Thanks @CEWebDesign for reporting and @kirilhristov for fixing!

**Comment by CEWebDesign** [comment]
Hello, looks like the issue is back.

**Comment by kirilhristov** [comment]
Fixed. Thanks for reporting!

**Comment by 908ltd** [comment]
Hi there,

I have this exact message on my website admin panel. Please could someone offer advise on how it was solved?

Thanks in advance.

Error message says: ×
Error
We have detected that your server is using PHP 5.5.38 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 5.6 or later which will receive security updates at least until 2018-12-31. Please ask your host to make PHP 5.6 or a later version the default version for your site. If your host is already PHP 5.6 ready please enable PHP 5.6 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure.

**Comment by mbabker** [comment]
Upgrade PHP on your server.  This is not an error, it is a notification that the software powering your site is no longer supported.  Contact your hosting provider for assistance on this.

**Comment by 908ltd** [comment]
Thank you for the fast response. I thought pretty much what you just said.

Basically, we have 2 websites using Joomla and are built with a template called IT TheShop2 from a company called IceThemes.

As of late we have had a message to update PHP on our websites to the latest versions, this message appeared in our admin section of the websites, However when trying to upgrade to latest PHP version, the sites do not work. This was obviously due to a conflicting extension or template.

So I tried to update the PHP version on a different template (Beez3 & protostar) to the one I mentioned above and it worked fine.

I went to look for support from IceThemes and it almost seems as though they cant offer support anymore, as if the company has just gone. their website sits there online but they don't respond to emails or anything.

www.908ltd.co.uk is using PHP 7.0.31
www.gardenlabelling.co.uk is using PHP 5.5.38

I tried multiple different versions but they didn't work. The sites only work with the versions that are now. I tried to check the page of requirements for the theme but there isn't one. 

I just wondered if anyone had the same issue or if I am doing something wrong here.

Thanks again for your response.
