### ISSUE TITLE
[jhelp] HELP37 instead of 38

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1063]
In your joomla admin click on the Help->Joomla Help link and the content of this page (https://help.joomla.org/proxy?keyref=Help38:Start_Here&lang=en) will be loaded in an iframe as shown in the image

<img width="660" alt="screenshotr12-27-29" src="https://user-images.githubusercontent.com/1296369/31818968-58edb776-b592-11e7-9055-2c71ee905ad6.png">

As can be seen it says 37 instead of 38 o

**Comment by Sandra97** [comment]
@Hutchy68 Can you help with this? Thanks!

**Comment by brianteeman** [comment]
Bump. It looks really bad to have 37 in the title of all the help pages

**Comment by Sandra97** [comment]
@Hutchy68 Please, can you make the change?

**Comment by brianteeman** [comment]
And please document and share how to do it so others can do it in the future

**Comment by Hutchy68** [comment]
I have a PR on the help proxy to remove the preceding `Help##` from all help screen titles when rendering the page. It even removes translated pages which were improperly translated (translating the namespace and not just the title).

What is at issue is the en version of the namespace isn't updated until it sees the update. This requires an edit and a save of the page. Yes we can bot run the edit and actually need to do so to add in the category for 3.8. No we can't mark the pages automatically with bot for translation which signals the translation bot to update the namespace of the en version. Page changes for translation should not be marked for translation automatically anyway, but this is the hurdle I am trying to bridge with the Help Proxy change. The URL is correct at the bottom and the preceding Help37 or Help38 is just noise in the title anyway.

**Comment by brianteeman** [comment]
it might be "noise" but it also makes the page content inaccurate

**Comment by mbabker** [comment]
Well, yes and no.  There aren't separate versions of the pages for each minor branch because of how the namespaces have been handled so https://help.joomla.org/proxy?keyref=Help30:Start_Here&lang=en is the same as https://help.joomla.org/proxy?keyref=Help38:Start_Here&lang=en and at least when looking at 3.x pages it really doesn't matter.

Where it does start to make a difference is if you're looking at https://help.joomla.org/proxy?keyref=Help25:Start_Here&lang=en or https://help.joomla.org/proxy?keyref=Help40:Start_Here&lang=en when that is created.  Across the major version branches we might want the version in the title, but since the proxy is really only accessed via the CMS backend it should be pretty obvious you're looking at help content for 2.5 on a 2.5 install, 3.latest on a 3.x install, etc.

**Comment by brianteeman** [comment]
I assumed that if you were on 3.6 you got the help for 3.6  -  my mistake

It is still confusing to see 3.7 when there is new content for 3.8

**Comment by mbabker** [comment]
It was like that once upon a time.  But, now imagine trying to maintain 9 unique sets of help screens for the 3.x series.

**Comment by Hutchy68** [comment]
That would be something like 1400 to 1500 individual pages, aka nightmare. You won't see a 3.8 help screen on a topic in 3.5 because a feature was added to 3.7. The keys don't exist in 3.5 to show it, nor is the feature there. So I'm on 3.3 and see the Article Manager for 3.8 in the help screen. Of course it looks different. 3.3 vs 3.8 lots of changes. So what, carrot and the stick. Why are you still on 3.3? You get to see what the current version looks like (carrot) and you are punished (the stick) for still being on 3.3. Solution, update the site as you should have updated it already.

**Comment by Hutchy68** [comment]
This is fixed. Please verify.

**Comment by Sandra97** [comment]
All fine now! No more `HelpXX:`
Thanks Tom!

**Comment by Hutchy68** [comment]
Fixed closing
