### ISSUE TITLE
[jdev] Nightly builds for Joomla! 4.0

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1075]
![image](https://user-images.githubusercontent.com/2596554/32678162-8d5e9ce8-c661-11e7-8a05-5b899ef43852.png)

`Nightly builds for Joomla! 4.0 are temporarily unavailable while we work on upgrading our CI system.`

https://developer.joomla.org/nightly-builds.html

What does that mean? What kind of upgrade is planed and is there help needed / possible? Don't we use Travis/Drone also for 4.0?

**Comment by mbabker** [comment]
The Jenkins box is running a PHP 5 version.  After the PHP 7 bump the builds stopped working because the build script uses the Version class which now has PHP 7 syntax in it.

Sometime next week I'm going to wire up a cron to run on the dev site's server to do the builds since that already has all the prerequisites to do it.  But sooner or later that Jenkins system needs updating or replacing (depending on what the testing team is doing).

**Comment by zero-24** [comment]
Ah ok so it is a admin task only. Thanks 👍 Do you want me to keep this open or do you have that on your own list already?

**Comment by mbabker** [comment]
Cron set up.
