### ISSUE TITLE
SSL Certificate deadline 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1097]
Starting with Chrome 66, Chrome will remove trust in Symantec-issued certificates issued prior to June 1, 2016. Chrome 66 is currently scheduled to be released to Chrome Beta users on March 15, 2018 and to Chrome Stable users around April 17, 2018.

The same is true for firefox and IE although the dates are different. 

We are effected because we use a rapidssl cert that uses symantec in the chain

Chrome is already displaying this message in the console
> The SSL certificate used to load resources from https://www.joomla.org will be distrusted in M66. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by mbabker** [comment]
Well.  Crap.  That's the wildcard certificate.

**Comment by mbabker** [comment]
Looks like this affects two certificates:

- `*.joomla.org`
- `update.joomla.org` (which is even more annoying because we just renewed this one last month)

**Comment by brianteeman** [comment]
It's hard to work out on the rapidssl site but they might be replacing those certificates. Alternatively letsencrypt will be providing wildcard certificates from January and as an open source organisation it feels more appropriate to support the!.

**Comment by brianteeman** [comment]
Looks like its just a case of getting the certificate re-issued
https://opensrs.com/blog/2017/09/google-symantec-resolve-chrome-browser-trust-issues/

https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=AR1548

Hope that helps

**Comment by andrepereiradasilva** [comment]
hi. yes Let's encrypt (open certificate authority) will support issuing wildcard certificates for free starting February 27, 2018.
https://letsencrypt.org/upcoming-features/

i agree with @brianteeman. it would be a good idea for Joomla (open-source project) to be associated with let's encrypt (open certificate authority project).

And it's already possible to issue SAN certificates with up to 100 alternate domains (which in most circunstances can replace the need for a wildcard certificate) and the process can be fully automated.

> If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 2,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate.
>
> https://letsencrypt.org/docs/rate-limits/

Let's encrypt certificates are for 3 months only, which is not bad since the renew can be fully automated trough ACME protocol (ex: certbot, acme.sh, etc).

But the let's encrypt wildcard certs will not be so easy to automate because, for now, wildcard certificates will require domain challenge level validation.

> Wildcard certificates will be offered free of charge via our upcoming ACME v2 API endpoint. We will initially only support base domain validation via DNS for wildcard certificates, but may explore additional validation options over time. We encourage people to ask any questions they might have about wildcard certificate support on our community forums.
> 
> Source: https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by mbabker** [comment]
Considering we already have over 40 subdomains I would rather not require us to move to a system where every time a subdomain goes up or down we have to do extra work to have SSL enabled.  So if we can keep a wildcard certificate that is going to be the most efficient thing for everyone's sanity.  We already have enough problems keeping up with the resources we have (and people not paying attention to certificate expirations), let's not add to that if we can avoid it.

**Comment by andrepereiradasilva** [comment]
ok, so wait for the wildcard from let's encrypt to be easily automated. Maybe in 6 months or so ... (then no need to forget expirations anymore since the renew can be fully automated).

**Comment by brianteeman** [comment]
Just a reminder that this needs to be addressed. Google Chrome Canary has already started to block access to joomla.org

<img width="562" alt="screenshotr22-26-57" src="https://user-images.githubusercontent.com/1296369/35783137-93533f14-09fa-11e8-812b-3390636e9909.png">

**Comment by mbabker** [comment]
If the timelines stay valid then on February 27 we can start the process to refresh our wildcard certificate using Let's Encrypt, this will be before Chrome 66 hits beta (I'm not so concerned with Canary and "bleeding edge" builds at the moment).  We'll also be close to the window for refreshing the CDN certificate for the downloads portal due to expiration, so that'll work itself out well.  Then we just need to validate our other certificates are good to go or take action to get those refreshed (the CDN partner used by Rochen doesn't allow our wildcard certificate hence every CDN node having its own certificate).

Certificate Name | Date Expires
-- | --
*.joomla.org | 24 February 2019
appscdn.joomla.org | 1 October 2018
cdn.joomla.org | 17 January 2019
downloadscdn.joomla.org | 28 March 2018
extensionscdn.joomla.org | 18 January 2019
update.joomla.org | 10 December 2018

**Comment by andrepereiradasilva** [comment]
Just additional info.
Let's encrypt changed target date for wildcard certificates do Q1 2018
https://letsencrypt.org/upcoming-features/

**Comment by mbabker** [comment]
https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654

Sigh, guess it's time for Plan B.

**Comment by brianteeman** [comment]
Guess so

**Comment by andrepereiradasilva** [comment]
use Subject Alternate Name (SAN) let's encrypt certificate with all current joomla domains and then replace it by a wildcard when available?

**Comment by mbabker** [comment]
A new certificate has been acquired and is now partially rolled out.  Will close when rollout complete.

**Comment by brianteeman** [comment]
thank you

**Comment by mbabker** [comment]
Everything `*.joomla.org` minus the demo site (this includes all CDN nodes) should now all be on the new wildcard certificate.  If there's a site still on the old certificate (Chrome will nag and that cert has a Feb 2019 expiry, the new one is June 2020) please log a new issue.

**Comment by mbabker** [comment]
Irony - We buy a new certificate, not even a week after it's acquired Let's Encrypt gets their wildcard infrastructure released to the public.

**Comment by brianteeman** [comment]
Sh*t happens
