### ISSUE TITLE
[joomla.org] openhub

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1106]
Our details and links are all out of date on openhub

Only a manager can update them - see here for list of current managers

https://www.openhub.net/p/joomla/managers

**Comment by mbabker** [comment]
Fixing what I can.  But honestly, last I knew their platform was so broken it might not all get corrected.

**Comment by brianteeman** [comment]
happy to help if I get access

Only mentioned it because I saw a few sites referring to it recently

**Comment by mbabker** [comment]
What I can fix is fixed.  Their system is doing a re-import on the CMS repo since I had to change the target branch to analyze, so when that's done everything should be up-to-date.

I can't add managers.  You have to go to the manager page and request to be added if you want that level permission (though I think it's set up in a way where anyone can edit, don't know for sure though).

**Comment by brianteeman** [comment]
Thanks for doing that

From what I can see its still only managers who can edit but we should be good to go now
