### ISSUE TITLE
[japi] 

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1116]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue 
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

I see no styling on this URL https://api.joomla.org/cms-2.5/classes/JFormFieldPredefinedList.html

**Comment by mbabker** [comment]
That page shouldn't be there to begin with.  It's not a 2.5 API source.

**Comment by mbabker** [comment]
Apparently at some point in 2014 I managed to deploy the 3.x docs over the 2.5 workspace.  As the root template and numerous media assets have been updated since then, that's why the page had a broken display.  That page should have never existed on an index so not sure how you stumbled on it, but everything that wasn't updated as part of the last deployment (which is noted in the footer of the phpDocumentor generated pages) has been removed.
