### ISSUE TITLE
sites down

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1156]
multiple j.org sites are down

**Comment by franz-wohlkoenig** [comment]
at Glip is reported that one of our Servers is down.

**Comment by Sandra97** [comment]
A ticket is opened at Rochen for that. They're working on the issue

**Comment by brianteeman** [comment]
Must be a big issue

**Comment by PhilETaylor** [comment]
@mbabker was working on them last night :) 

Specifically what I see at the moment 

https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My44&dev_level=Nw==&list=grid&pv=MS4xLjE=&callback=jedapps_jsonpcallback

504 Gateway Timeout - means tab in Joomla Admin Consoles displays an error instead of installable extensions. 

<img width="730" alt="screen shot 2018-05-13 at 12 42 34" src="https://user-images.githubusercontent.com/400092/39966915-3c570fda-56ab-11e8-98fe-987656dbde76.png">


<img width="1290" alt="screen shot 2018-05-13 at 12 40 33" src="https://user-images.githubusercontent.com/400092/39966898-0b7cd782-56ab-11e8-9f2f-7f3921623da3.png">


docs.joomla.org also down.

**Comment by Sandra97** [comment]
https://appscdn.joomla.org is on the server which is down, so it's approx 14 sites which are impacted by this issue

**Comment by PhilETaylor** [comment]
Multi million pound project using shared hosting for critical infrastructure... with a non-responsive, no-SLAed webhost... 

![05-138-egg-basket3016-e1442410529485](https://user-images.githubusercontent.com/400092/39967050-1622d61c-56ad-11e8-85df-79654dc49fa3.jpg)

**Comment by Sandra97** [comment]
Closing this issue.
