### ISSUE TITLE
[jevnt] Events not related to Joomla

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1190]
Hello, 

So now we are displaying on the Joomla Events site events which are not related to Joomla? 

https://community.joomla.org/events/archive/3765-africa-cybersecurity-and-forensic-summit.html
https://community.joomla.org/events/archive/joomla-conferences/3780-epigenetics-conference-2018.html
https://community.joomla.org/events/3770-3d-printing-technology-and-innovations-expo-3rd-international-conference.html
https://community.joomla.org/events/3760-data-summit-2018-usa.html

Why are we promoting these events?

I wanted to report them, but Access Denied even when I'm log in.

**Comment by hvdmeer** [comment]
Spotted them on Monday and wanted to ask about this. Here for the notification on the ruling of these events.

**Comment by mandville** [comment]
I tried to report some of those events as some of the people posting them are purely doing it for self promotion and /or are listed as commercial company names. while logged in i was presented with a 403 / ACL style error 
If these events are "satellite"  events as per the Official Joomla Events Charter then they should clearly be marked as such and any promotional benefit declared after consultation.  Is autopublish events set yo on?

**Comment by carcam** [comment]
Hi @Sandra97, and @hvdmeer and @mandville
thanks for reporting I will check with the team and will take proper measures.

The events are in the "Joomla! Related Events" category but it's not being clearly showed in the event detail so we will check into fix that.

Also some of them are clearly for self promotion and we will look into our approval procedure and be more clear about what a Related Event is.

Regarding your issues with the portal after login, are you able to submit a ticket at all? If so, please do it and write there the usernames experimenting the problem. Otherwise, please send me an email with those details at carlos.camara@community.joomla.org.

Thank you!!

**Comment by Sandra97** [comment]
As all events not related to Joomla have been removed, I'm closing this issue.
