### ISSUE TITLE
[jlaunch] Painful slow or expected fast > not predictable

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#1206]
Since launch.joomla.org has started is use it for 3.* and 4.*-Sites, Server in Europe.

As Title say its unpredictable how slow/fast Websites are loaded. Example Today load of backend takes 20 Seconds, load of cPanel next 20 Seconds, ...

I don't know ow to solve this but its no recommendation to use CloudAccess for a live Site (i guess there is no Difference using a Site for free or paid).

**Comment by jonathanCA** [comment]
Hi Franz, I just wanted to let you know that we are looking into this. We are reaching out to you directly for more specific information and we will report back here once we have identified the solution.

**Comment by jonathanCA** [comment]
Hi Franz, two questions/requests. 
1. Is it possible that you are seeing the slowness when first accessing the site? We believe the delay you are seeing is related to the creation of the LVE user context, which happens when site is first requested. Production sites don't see this since their LVE user context is saved as a result of traffic to the site. 
2. Just to rule out any network issues, would it be possible for you to provide a traceroute to one of the sites? 

Our goal here is to provide a great service, we really appreciate you expressing concern on performance, with a bit more info we should be able to identify the cause here.  Thank you!!

**Comment by franz-wohlkoenig** [comment]
Thanks for your Questions, @jonathanCA 

1. its not about first Accessing the Sites. It can take Hours CA-Sites are slow, other Sites (not CA-Sites) are at the same Time fast as ever. But its also happen CA-Sites are fast at first Access and later on too.

2. Tracerout if CA-Site is slow? How to make a Traceroute please?

Thanks for Info about LVE-Difference.

**Comment by wojsmol** [comment]
@franz-wohlkoenig See [this](https://www.youtube.com/watch?v=TulqpjgIa0k) video for example

**Comment by franz-wohlkoenig** [comment]
thanks @wojsmol, no i know how to do that. Make a Traceroute on http://wohlkoenig-4.joomla.com/ got "unknown host http://wohlkoenig-4.joomla.com".

**Comment by wojsmol** [comment]
use wohlkoenig-4.joomla.com as host

**Comment by franz-wohlkoenig** [comment]
@wojsmol thanks, that works.

@jonathanCA should i copy traceroute here?

**Comment by franz-wohlkoenig** [comment]
no Ticket open with CA, so @jonathanCA will say whats next.

**Comment by jonathanCA** [comment]
Thanks all, you can send traceroute info to bugreporting@cloudaccess.net

**Comment by franz-wohlkoenig** [comment]
Traceroute send. Thanks all for helping.
