### ISSUE TITLE
wysiwyg editor won't allow import of image

### ISSUE THREAD

**Issue by Chattels-it** [joomla/joomla-websites#1228]
I have the latest version of Joomla (3.8.12?) and have installed Adsmanager gold successfully. My frontend 'Home' page is in a Module and I used the wysiwyg editor to create text in that area. That was fine. But now I want to import a table/chart which I have converted to jpeg format. I select this for 'upload' from my Desktop and it uploads 'successfully' However, it uploads to the folder 'media/com_acymailing/upload' and when I press the blue 'insert' button, the button goes a pale shade of blue and nothing happens. What am I not doing right? So frustrating!!

**Comment by pe7er** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

For this reasons we'll close your issue here.
