### ISSUE TITLE
[jshow] Missing country in top menu

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#1230]
Even if there are several sites for "Italy", it's not shown under the country menu.

![immagine](https://user-images.githubusercontent.com/733133/45536998-64c75d80-b803-11e8-92d6-c69d9b713ed1.png)

**Comment by Sandra97** [comment]
IIRC, a minimum of number of websites was needed to be displayed in this menu, which is for me something unfair. You display all countries or none or in fact, you highlight some more than others and give also the impression that only these countries are building Joomla websites

**Comment by Sandra97** [comment]
@sebastienlapoux Could you please check this? Thanks!

**Comment by sebastienlapoux** [comment]
Hi,
Only after 20 items. We added the rule on FAQ.
![image](https://user-images.githubusercontent.com/13470265/46298553-a98f1a80-c59f-11e8-833b-e1b3828ed893.png)
Thanks.

**Comment by Sandra97** [comment]
It's not because this rule is in the FAQ that it means it's a fair one. For me, it isn't, it's an arbitrary rule. 
It can work for large countries, not for small ones where there's few people using Joomla, it gives them less visibility. Without mentioning it gives the visitor the impression there's Joomla websites only in these countries

**Comment by mbabker** [comment]
Call it "Featured Countries" or something if you want to impose an arbitrary restriction but as is it gives the impression that the only countries with showcased sites are those in that menu.  For me it's mainly the menu label that is the issue here, not the practice of having select countries in that menu.

**Comment by sebastienlapoux** [comment]
@Sandra97 to list into main menu some links without a minimum of items doesn't make sense too for the visitor.

@mbabker yes it's a solution, thanks!

@Sandra97 do you prefer Michael's solution by renaming it "Featured Countries" or do you prefer to delete this main link "By country/Featured Countries" ?

**Comment by Sandra97** [comment]
I'm fine with Michael's solution

**Comment by sebastienlapoux** [comment]
Done, thanks both!
