### ISSUE TITLE
www.sertaocentral.com

### ISSUE THREAD

**Issue by sertaocentral** [joomla/joomla-websites#1233]
meu site foi excluido, queria recuperar ele de volta

**Comment by sertaocentral** [comment]
alguem pode me ajudar?

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

For this reason, please close your issue here.
