### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by mundofit** [joomla/joomla-websites#1234]
Hello, we have a web with joomla and it appears in google as web "not sure" I want to solve the problem.

When I try to access the joomla admin I get 500 error.
 Thank you

www.mundofit.es

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

I'll close this issue here.

**Comment by Sandra97** [comment]
Your website can be marked as unsecure because it's not using the https protocol.
