### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by prardin** [joomla/joomla-websites#1235]
I am unable to access the joomla back end of my account after migrating our website to a different hosting service. I'm not sure if I am simply inputting the wrong login info or it is something different.

I get:

Error
An error has occurred.
36 JFTP: :append: Unable to use passive mode
Return to Control Panel

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

For this reason, please close your issue here.
