### ISSUE TITLE
the modules are not appearing propely on some of the menu items

### ISSUE THREAD

**Issue by kasaq06** [joomla/joomla-websites#1237]
If you could see below link , and scroll down you can see modules like search trainings etc are not appearing completely . they have partial appearance.
http://a2ftest.com/oracle-training/new-oracle-trainings

Where as if you go to ther menu item modules are diaplyed perfectly

http://a2ftest.com/oracle-training/fully-verifiable-testimonials

How can I adjust the css positions for mdules only for the first witout affecting other menu item .

You may need to add security exception to access these links

Joomla version is 3.6.5

**Comment by pe7er** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

I'll close this issue here.
