### ISSUE TITLE
[forum.joomla.org] sign up field

### ISSUE THREAD

**Issue by osita12** [joomla/joomla-websites#1240]
![screenshot_2018-10-09 www worldbestcinema site](https://user-images.githubusercontent.com/42456170/46801384-77757980-cd52-11e8-8e5f-f35e2a60b25e.png)
 
sign up requirement field is too much for a new visitor to field, please how can edit it?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

I'll close this issue here.
