### ISSUE TITLE
[jcomm] Sponsoring page should not display full name

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-websites#1304]
[The sponsoring page](https://community.joomla.org/sponsorship-campaigns.html) on the right side should not display the "full name" and the "How should we address you?"-name combined, only the latter.

**Comment by Sandra97** [comment]
@Joomv Can you please answer Benjamin? Thanks.

**Comment by conconnl** [comment]
@Joomv can we take care of this?

**Comment by conconnl** [comment]
I did a check myself.
It seems that the field officially is the First & Last Name.
Someone change the question to "How should we address you?" while it's still the first name.

The extension doesn't seem to have a option to define when to display it.
The only way to remove it is by overriding the Module or use the component how it was meant by the Developer. "First & Last name"
<img width="568" alt="image" src="https://user-images.githubusercontent.com/11913918/82035723-35d05180-96a0-11ea-858a-a81787505b90.png">


As there is an option to say "Anonymous Sponsorship" I don't see why we have changed the titles of the fields.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/11913918/82035781-4c76a880-96a0-11ea-945b-bca01c6d8b49.png">

I would simply restore the purpose of the field and fix some of the donations.
Instead of creating an override and maintain it.

@jeckodevelopment @Sandra97 What do you think?

**Comment by jeckodevelopment** [comment]
agree with your proposal
can you please proceed if @Sandra97 agrees?

**Comment by Sandra97** [comment]
I would use the component fields, with First and Last name, which is enough. 
If it's a company, I presume it's the company name which will be displayed and not the first name / last name right?

**Comment by Sandra97** [comment]
So I agree (yes, it happens sometimes)

**Comment by conconnl** [comment]
Looking at the extension....
The field company is disabled and if you enabled it, it won't show anything in the module.

We can make it fit by changing this:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/11913918/82038104-55b54480-96a3-11ea-8c0e-d1171f98fb21.png">

Too:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/11913918/82038198-77163080-96a3-11ea-9010-36d27b67f33a.png">

**Comment by jeckodevelopment** [comment]
it shouldn't be mandatory if it's "Last name or nothing" :)

**Comment by conconnl** [comment]
I just edited HTML in the Browser not the site....
I want to know if you would have it like this, so people can choose Name or Company.

**Comment by conconnl** [comment]
Changed to this:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/11913918/82041266-2ce37e00-96a8-11ea-88b4-8325356422e2.png">

**Comment by Sandra97** [comment]
I'm not a fan of this proposal.
I prefer First Name / Last Name / Company

**Comment by conconnl** [comment]
Can't combine without creating overrides etc.
The tool has no company option to display in the sponsor list.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/11913918/82041912-45a06380-96a9-11ea-89d5-5adb152695ce.png">

Or it's not using company at all, or tricking the field.

**Comment by mandville** [comment]
Instead of [Empty] i suggest [or leave blank]

C Mandville
Joomla! Vulnerable Extensions List Team Leader
Joomla Security Strike Team Member
Joomla Trademark Team Leader
Unless indicated - this email discussion is not to be shared beyond the
original recipient

**Comment by conconnl** [comment]
> Instead of [Empty] i suggest [or leave blank] C Mandville

Thank you, that is a very good one.
