### ISSUE TITLE
pop-up window is blank

### ISSUE THREAD

**Issue by ScienceAlive** [joomla/joomla-websites#1312]
Every time I attempt to add a link in an article, the pop-up window that appears is blank. And when I try to select the code tab, the progress icon keeps spinning. Any suggestions?
![blank screen](https://user-images.githubusercontent.com/49325073/55657989-f6eb7f00-57b0-11e9-8308-09bde109c3ea.jpg)

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page 
-or find a service provider at https://resources.joomla.org/
-for bugs about the CMS, please go to https://github.com/joomla/joomla-cms

For this reason, I'm closing your issue here.

Thanks!
