### ISSUE TITLE
wordcrafting.nl | issue with php 7 - no access [joomla.org] 

### ISSUE THREAD

**Issue by aureliafg** [joomla/joomla-websites#1314]
Hi,
My website wordcrafting.nl has been blocked because of several errors due to php 7 upgrade
I can't access anything anymore, and the problem is I want to reverse php to update the joomla version and make it work again.

PLEASE HELP!

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
