### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by AFCURESite** [joomla/joomla-websites#1315]
AFCURE.org is a website I am trying to update via Joomla. However, when I log in, I encounter an Error 1054. When I try and download Joomla (per some conversations on the forum), I do not see any .run/.exe files in order to install the program. I'm not sure how to get into my website for updates.

**Comment by zero-24** [comment]
Where is the error comming from? From the downloads page? Did you tried to download the package manually and update by upload?

**Comment by AFCURESite** [comment]
This error is coming from the administrator login for the page; http://www.afcure.org/administrator/

[cid:image002.jpg@01D4F50B.60F1ED20]
Yes, I tried to download the package manually, but I saw no execute or run file(s).

Thanks,
Sam

**Comment by mbabker** [comment]
Joomla is not a program that you download and install on your local computer, it is a package of files that you upload to a web server (hence the lack of any executable file types).

A 1054 error generally means there is a database issue with the website, and you will need to debug that issue.

As this repository is not a user support platform (this repo is for tracking issues with the `joomla.org` websites), I'm going to be closing this issue out.  If you need further assistance, I can point you to a couple of places:

- The Joomla Forum - https://forum.joomla.org/ - Here you'll be able to find support from various community members volunteering their time to answer questions
- Joomla Resources Directory - https://resources.joomla.org/en/ - On this site, you'll be able to find service providers who provide specialized Joomla support services (generally paid) and would be able to work one-on-one with you

**Comment by AFCURESite** [comment]
I do need additional assistance---Reading through the forum, I am not finding what I need to debug. I don’t think it’s appropriate to close this issue until it is resolved.

**Comment by mbabker** [comment]
I'm sorry you're having issues with your website, but as I mentioned this specific repository and issue tracker is not the place to get help with it; this space is specifically for tracking issues on any of the `joomla.org` subdomains.

If someone watching this repository wants to reach out to you individually to help you, that is their choice.  Otherwise, the "best" options I can suggest for you are either a support forum like https://forum.joomla.org/ or https://joomla.stackexchange.com/ (keeping in mind that these are entirely volunteer driven resources, Joomla does not have a paid support staff) or finding a service provider that you would most likely need to pay that can provide one-on-one assistance for your issue.
