### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Fvinhas147** [joomla/joomla-websites#1324]
Hi, I'm having some trouble on google maps extension for my website. It is not working on all pages.
Is it possible to contact me so I can show better the problem details?
Tks!
Fábio Vinhas

**Comment by zero-24** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
