### ISSUE TITLE
[forum.joomla.org] Register - verification code not found

### ISSUE THREAD

**Issue by vasiledraghita** [joomla/joomla-websites#1330]
Hello,
I couldn't find a support email address for Joomla and I'm writing here.
I tried to create an account with a custom domain email address and it seems like there is a bug.
After clicking the confirmation link, it lead me to a 403 page (http://prntscr.com/nsvla9).
Can someone help me?

**Comment by Sandra97** [comment]
Hi,

There's no support email address for Joomla and this repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by Sandra97** [comment]
You can also send a message to https://community.joomla.org/helpdesk/forum-un-ban-request.html so that they can look at your issue
