### ISSUE TITLE
[jcm] - Broken page: Joomla Author Login page

### ISSUE THREAD

**Issue by alexprut** [joomla/joomla-websites#1333]
The page https://magazine.joomla.org/authorlogin seems to be broken
Below is the error message:

```
403 This request is blocked by Admin Tools. Please change this message in the component's options. If you are the administrator of this site and have blocked your own IP address on accident please visit https://magazine.joomla.org/administrator/index.php?admintools_rescue=you@example.com where you@example.com is the email address of your (Super User) account. This URL will only send you an email if the IP address from which you are accessing it is being blocked by Admin Tools. If you are not blocked no email will be sent; you don't need an email with instructions to unblock your IP if your IP is not blocked
```

The Joomla Magazine authors are not able to login.

**Comment by pe7er** [comment]
The JCM team is working on a new JCM website.
They have ported all authors + articles to the new development website.
Therefore the current website has been "freezed" (otherwise any changes in the current site won't be on the new site) and the login for authors has been disabled temporary.

Sorry for the inconvenience!

**Comment by alexprut** [comment]
Thanks @pe7er , is there any ETA?

**Comment by WebSolutionZau** [comment]
I stepped down from the JCM in May 2019, I believe it is being redone by somebody else but I'm not up to date.

**Comment by conconnl** [comment]
The new magazine website will be online within a few weeks.
