### ISSUE TITLE
[jcm] contact page points to an non existent mail address

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1334]
On the contact page: https://magazine.joomla.org/contact-us the mail `magazine@community.joomla.org` is listed as contact mail. Based on the feedback by @jeckodevelopment this mail does not exists. So maybe we should create that mail or change the page to an mail that exists.

This issue has been first reported by @alexprut

**Comment by Sandra97** [comment]
This email works.

**Comment by jeckodevelopment** [comment]
Sorry, the group exists.
Can you please try and eventually share the error log?
@alexprut

**Comment by alexprut** [comment]
@jeckodevelopment 

There was a problem delivering your message to magazine@community.joomla.org. See the technical details below.
--
https://support.google.com/a/answer/168383

Your email to group magazine@community.joomla.org was rejected due to spam classification. The owner of the group can choose to enable message moderation instead of bouncing these emails. More information can be found here: https://support.google.com/a/answer/168383.

More people got the same error. Even when they used a gmail address.

**Comment by jeckodevelopment** [comment]
it looks like your email has been classified as spam.
I changed some permission settings in the group, could you please retry?

**Comment by zero-24** [comment]
Closing as it seams the issue is solved now.
