### ISSUE TITLE
[joomla.org] - Administrative Panel Access

### ISSUE THREAD

**Issue by Webmaster21-pa** [joomla/joomla-websites#1336]
I am trying to access my administrative panel. However, every time I try to access it, I am kicked back to the public page. I need to be able to access my page on a daily basis and it will not allow me to update it. Please help. I have deleted all the cookies,

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
