### ISSUE TITLE
[jhelp] Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by crcury14** [joomla/joomla-websites#1339]
Please describe the problem or your issue

**Comment by crcury14** [comment]
The error "Cannot use object of type stdClass as array" shows up after clicking on new item button when trying to add a new menu item.

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
