### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by DieKon** [joomla/joomla-websites#1345]
Hello.
After updating joomla, the front-end code stopped working. Material creation date is now always = current date. Through the admin panel, the date changes to the specified one.
How to make it possible to indicate the right date with the front-end too and save it (as it was before)?
`<?php echo $this->form->renderField('created'); ?>`
Здавствуйте.
После обновления joomla перестал работать код с front-end. Дата создания материала теперь всегда = текущей дате. Через панель администратора дата изменяется на указанную.
Как сделать, чтоб с front-end дату тоже можно было указывать нужную и она сохранялась (как было раньше)?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
