### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by mvexpress13** [joomla/joomla-websites#1346]
i"m trying to add and item to my web an i get a blank screen

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
