### ISSUE TITLE
[joomla.org] Accessibility issue with some links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#135]
I did a quick a11y test on the homepage using tenon.io and it highlighted a few issues. The main one is that many of the links (especially the social media links) have no link text.
> Link found which contains no text. Because Accessibility APIs use a link's text do determine its accessible name, this link will have no name and will not be announced by assistive technologies.

Normally I resolve this by adding some link text and giving the link text the BS3 class of sr-only (screen reader only)

We arent using BS3 but the class can easily be added
> .sr-only{
	position:absolute;
	width:1px;
	height:1px;
	padding:0;
	margin:-1px;
	overflow:hidden;
	clip:rect(0,0,0,0);
	border:0
}

For a full list of the links with *blank link text* follow this link http://tenon.io/testNow.php?url=https://www.joomla.org/

**Comment by brianteeman** [comment]
@pbwebdev thoughts?

**Comment by mbabker** [comment]
There's an element-invisible class we added for that purpose in
https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/bootstrap-extended.less
(which is compiled into the template) so we don't need to add that sr-only
class.  Beyond that pull requests are welcome for main template elements on
that repo otherwise a punch list of items that we can work through helps a
lot too.

(I should drink more coffee before responding to these things after a
flight)

**Comment by brianteeman** [comment]
Great that we have the class I didnt know that was there
> .element-invisible 

I had assumed the social links were a module and not hard coded in the template - silly me for thinking we would do such a thing.

As I have access to the template repo I will do a PR there.

**Comment by mbabker** [comment]
Well when the template gets duplicated on 20 different installs (assuming
everyone actually updates them), there are some shortcuts you probably
wouldn't take on a "normal" setup.

**Comment by brianteeman** [comment]
First part done https://github.com/joomla/jdotorgtemplate/pull/17

**Comment by mbabker** [comment]
Added the change to the live site.

**Comment by brianteeman** [comment]
thanks
