### ISSUE TITLE
Position "left" changes - help!

### ISSUE THREAD

**Issue by TabeaG** [joomla/joomla-websites#1357]
I have a problem with a module on my webpage which should be in position "left", but moves down to the bottom of the page. However, depending on the browser I use and on the window size of the brower, the module switches from bottom to top left... 

Furthermore, the same kind of module on a different page of the website stays in position top left how it is supposed to be. 

I already tried to build the page from scratch, but the problem appeared again. 

Any ideas are much appreciated!
The website is www.srerc.ch and the page with the problem is "Call for Papers"

![Position left](https://user-images.githubusercontent.com/56402485/66583250-4b6a1f80-eb83-11e9-9fc5-86d757c38ddf.PNG)
![How it should look like](https://user-images.githubusercontent.com/56402485/66582252-be729680-eb81-11e9-975f-42fb52851692.PNG)
![How it should not look like](https://user-images.githubusercontent.com/56402485/66582253-be729680-eb81-11e9-9099-7f96500ca0e4.PNG)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
