### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by niloofar81** [joomla/joomla-websites#1363]
Hi there

I was trying to add a gallery page to my website and then unpublished. Since then i get error 404. I contact host which they said host is okay.
I am very upset and frustrated. Could you please help me?
melbournevein.com.au/administrator

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
