### ISSUE TITLE
[jevnt] is there an RSS feed for events?

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1364]
We would like to show events on our JUG website to support other JUGs and J Events.  Is there an RSS feed?

**Comment by mbabker** [comment]
Just manipulating Joomla URLs, I'm going to say no.  https://community.joomla.org/events/joomladays.feed

Such a shame there aren't APIs built into `joomla.org` for users to pull data and use it on their own sites.

**Comment by uglyeoin** [comment]
But it's using Sobi right?  Sobi can do it I thought?

**Comment by mbabker** [comment]
Well, considering that would be the feed URL if Sobi was using the same structure as core Joomla to designate a feed view, and that feed is empty, I'm going to assume either Sobi cannot do this or requires extra configuration that nobody thought to go through because nobody thought about creating consumable resources like this for use outside of that specific site (even the events on the `joomla.org` homepage have to be manually updated because of the same lack of API).

**Comment by uglyeoin** [comment]
I wonder if it is on by default as indicated here: https://www.sigsiu.net/default-template-settings#rss I haven't used Sobi, but perhaps it's as simple as me working out the right URL.

**Comment by uglyeoin** [comment]
I know I'll ping Radek a message on Facebook :)
