### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Ramiras3336** [joomla/joomla-websites#1368]
с администраторов ISPServer проблема в скрипте php

Однако сайту barda-school2.ru по-прежнему не хватает выделяемой памяти для php-скрипта:
[Mon Oct 28 12:19:26 2019] 188.120.252.181:54602 [500]: / - Out of memory (allocated 517087232) (tried to allocate 20480 bytes) in /var/www/user6098062/data/www/barda-school2.ru/libraries/joomla/database/driver/mysqli.php on line 891

Притом, что я расширял параметр memory_limit, а также пытался запускать сайт на разных версиях php.

Боюсь вынужден рекомендовать вам обратиться к разработчику сайта для отладки и выяснения причин неконтролируемого расхода памяти php-скриптом.
Очень поможет, если вы уточните, не проводились ли на сайте недавно каких-либо технических работ и не выкатывались ли новые обновления вашим разработчиком.

Как отметил мой коллега в сообщении выше, проблема именно в коде скрипта, единственный вариант решения подобных проблем - правки со стороны разработчика скрипта.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
