### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by Marat0007** [joomla/joomla-websites#1370]
SAMPLE DATA
 Демо данные блога Демо данные, которые создадут сайт-блог. 
Если сайт многоязычный, данные будут привязаны к активному языку бэкэнда.
LATEST ACTIONS
Пользователь Maek781024-1 выполнил проверку таблицы #__content  30-10-2019 10:38
Пользователь Maek781024-1 обновил материал Стронгу Шахтер STU-U6 660 г x11 Asic шахтер Dashcoin горная машина с блоком питания  30-10-2019 10:38
Пользователь Maek781024-1 вошел в админ панель  30-10-2019 10:21
Пользователь Maek781024-1 вошел в админ панель  30-10-2019 10:05
Пользователь Maek781024-1 вышел из сайт  30-10-2019 09:44
PRIVACY DASHBOARD
Нет запросов.
LOGGED-IN USERS
Super User Панель управления  30-10-2019 10:40
POPULAR ARTICLES
0 Стронгу Шахтер STU-U6 660 г x11 Asic шахтер Dashcoin горная машина с блоком питания  30-10-2019 05:34
RECENTLY ADDED ARTICLES
	Стронгу Шахтер STU-U6 660 г x11 Asic шахтер Dashcoin горная машина с блоком питания Super User  30-10-2019 05:34
Joomla! 3.9.12	 —  © 2019 marat007.mcdir.ru

Просмотр сайта0Посетителей1Администратор0СообщенийВыйти как доделать?

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

#### Translated with Google Translate

Здравствуй,

Этот репозиторий предназначен ТОЛЬКО для сообщений о проблемах на сайтах * .joomla.org, а не о Joomla! CMS.

По вопросам поддержки пользователей, пожалуйста, перейдите по ссылке:
-https: //forum.joomla.org/
-https: //docs.joomla.org/Main_Page
или найти поставщика услуг по адресу https://resources.joomla.org/

По этой причине я закрываю вашу проблему здесь.

Спасибо!
