### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by SharonsDanceStudio** [joomla/joomla-websites#1372]
My website reads this message.......
 
"It appears you don't have
permission to access this page.
403 Error. Forbidden."

Please help me fix this, we are a business and need it to be operating. asap.

**Comment by SharonsDanceStudio** [comment]
https://sharonsdancestudio.com/

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS. If you find a bug in Joomla CMS, please report it at issues.joomla.org

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by SharonsDanceStudio** [comment]
thank you.
