### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by takuto4** [joomla/joomla-websites#1373]
Hi,
When trying to download the Spanish version 3.9.13, the next message is shown:
An error has occurred while processing your request. It happens to the best of us!
Could you please repair the error?
Thanks.
Best regards

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS. If you find a bug in Joomla CMS, please report it at issues.joomla.org

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
