### ISSUE TITLE
Error: 1054 on Joomla site

### ISSUE THREAD

**Issue by owenstiffler** [joomla/joomla-websites#1374]
I upgraded my version of Joomla and now when I try to enter the backend of my site it says Error: 1054 and a blank page shows up. How do I fix this?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS. If you find a bug in Joomla CMS, please report it at issues.joomla.org

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
