### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by htetmyat20** [joomla/joomla-websites#1376]
hi joomla team,

i have no idea to select the image that's already exited on my website to another folder in media
please respond as soon as possible

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS. 

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
