### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MusosGuide** [joomla/joomla-websites#1377]
My site (www.musosguide.co.uk) has gone down, displaying the following message:- INSERT command denied to user 'dbo451955272'@'infong-uk7.clienthosting.eu' for table 'musos_session' SQL=INSERT INTO `musos_session` (`session_id`, `client_id`, `time`) VALUES ('eb3eb01abfcd5bd5391b76239f0ad1b1', 1, '1576662040')

Can this be fixed?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by MusosGuide** [comment]
Peter, that's all Greek to me but will see if the links are of any use.

Kenny McMurtrie
Editor-in-Chief
www.musosguide.org.uk
