### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by panoramacomunicacion** [joomla/joomla-websites#1382]
Buenos días,

nuestra página de kineled.com no funciona bien y nos es imposible acceder.
Solicitamos ayuda para ver como lo podemos solucionar.

Gracias y un saludo

Good Morning,

Our kineled.com page does not work well and we are unable to access.
We ask for help to see how we can solve it.

Thanks and best regards

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
