### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ikhwanalias** [joomla/joomla-websites#1383]
Hi, 

I would like to ask about the bug/server problem because our website have an only home page.
There is no other button to go to another page. We did not edit or adjust the setting. Here is our company website's link: http://www.bicarasepakat.com.my/ 

Kindly assist me to solve this problem. Thanks for your time and cooperation.

Regards,

IKHWAN

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
