### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Soslan2017** [joomla/joomla-websites#1385]
Hello. Have a problem with translate my admin panel on site. When I try to install  russian language the joomla is wrong massage "error an install a language".  I try to uninstall all russian lang folders on my file manager to hosting and try to install, but have problem after. Maybe I forgot something or do something not right?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by Soslan2017** [comment]
Thanks and sorry:))

**Comment by pe7er** [comment]
No problem!
