### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by kimvan1215** [joomla/joomla-websites#1396]
Please describe the problem or your issue
I have paid the 49.00 to learn join la and your records show i should say I haven't. 
I got records on it and will call credit card company and with gold a return. 

kimvan1215@outlook or under kimvan52@gmail

Please help me with this. I do like join la and what to learn more. 

Kim Van marter

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
