### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by limepub** [joomla/joomla-websites#1397]
I am the new web designer for JanineHansen.com which I believe is being hosted by Joomla, but the access page, nevadafamilies.org/administrator, gives me a 404 error. How can I log in to make updates to the website?  I have not used Joomla much before. Her site is still up, but I cannot figure out how to access it.

Please help!

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
