### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by artefac0** [joomla/joomla-websites#1409]
I am unable to log in to my Joomla account (admin name Eliaheart2013) for www.artefactcom.com. I need to do so because it seems my Joomla was hacked and people have been creating accounts with email addresses that they do not own. I need to delete these users and make sure it never happens again in my site.

I received notification of this from an OpenProvider ticket about user ChildLaw. Please see my screenshots attached for more details.

When I try to log into Joomla, it says the user account does not exist, and when I try to click on "Forgot Username" or "Forgot password", I get an "empty"/captcha error message. Could you please help ASAP? Thank you.

Helene Turgeon
![ChildLaw2](https://user-images.githubusercontent.com/63404682/78948079-3f5d0d00-7a95-11ea-9794-44b606dc05db.JPG)
![Joomla1](https://user-images.githubusercontent.com/63404682/78948081-3ff5a380-7a95-11ea-812e-3a5e38c5fd4f.JPG)

**Comment by conconnl** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
