### ISSUE TITLE
[osm] Why a custom.css for a custom template?

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1412]
Title.  Shouldn't be a need for a site specific `custom.css` on a template that is used on one website.

**Comment by helvecio** [comment]
Sat the time the developer created this custom template based on someone else's work. Instead of fiddling with previous existing CSS, s/he may have decided to create a custom.css file during the development stage. When the site went in production, instead of bringing the new/modified code into the existing CSS file, it was kept separated in the custom.css file.

**Comment by conconnl** [comment]
Exactly....
Is this really an issue to fix, personally I would say "No"

**Comment by mbabker** [comment]
Close then.

For the record, it is a legitimate issue as a one-off template should be well optimized for its use case.  A custom.css on top of a template.css implies that the template is not well optimized in that it requires extra HTTP requests to load all required resources, and that the custom.css may be overriding styles defined in the template.css (overrides which generally should not be necessary).
