### ISSUE TITLE
problem with joomla site [joomla.org] 

### ISSUE THREAD

**Issue by noelcypress** [joomla/joomla-websites#1418]
Hi there, I have been using Joomla for my website for ten years now. My website is my income. And today when  I went to update the main article like I always do, it wouldnt allow me access. I noticed it wouldnt let me access ANY articles, nor make new ones. It would say an assortment of 500 errors and I dont have the permissions to access anything. I tried some simple troubleshooting, even emptied some of my cache, and now my website's menus and articles are all GONE from the front end of the site! Theyre still in the back end, but still nothing at all is responding to me. I have no idea what to do at this point. My server recently changed their DNS nameservers as well. I dont know if this is so severely affecting my site?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
