### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by geluxd143** [joomla/joomla-websites#1431]
I just want to ask if you are one of the owner of gospelhall.org because i found a vulnerability at that site and there is no contact details about the site and then I saw “joomla” below and try to ask here if ever you can answer my question. Thank you.

**Comment by geluxd143** [comment]
Please email me for your response. Thank you.
Email: hanzhoward15@gmail.com

**Comment by pe7er** [comment]
**Joomla** is an award-winning **content management system** (CMS), which enables you to build web sites and powerful online applications. Everybody can install the software on a web server to create and maintain their own website.

Joomla.org is not the owner of the domain that you mentioned. You can find information (like the owner) of a domain via https://lookup.icann.org/ but in this case the owner is anonymous.


This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by zero-24** [comment]
And just to be cristal clear Security issues should never be reported in a public ticket system. When you find a Security issue in Joomla or our websites please contact the Joomla Security Strike Team at security@joomla.org

In this case we can not help, as mention by peter, as this page is not hosted nor maintaind by the Joomla Project.

**Comment by mandville** [comment]
the contact for them as clearly stated on their website is support@siteaction.com
