### ISSUE TITLE
[idp] Concent download is it automatically processed or manually?

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-websites#1435]
After having confirmed the consent download request by verifying the email+token the message isn´t that specific about what to expect next. Is it a manual or an automated processing that is taking place?
If automatic you would expect an email to arrive soon after verifying (but it didn´t)
![16-05-2020 22-11-25id-conf](https://user-images.githubusercontent.com/790445/82129716-f8b1af80-97c4-11ea-9ebe-103289992ae0.png)

**Comment by sanderpotjer** [comment]
Thanks for the feedback. This is Joomla core functionality. So might be even better if this is fixed in core, but we will have a look if we can change this for the Identify Portal already.

**Comment by brianteeman** [comment]
OR just change the message to indicate that the data will be received within x hours

**Comment by roland-d** [comment]
We cannot say x hours as legally we have 1 calendar month ( https://ico.org.uk/your-data-matters/time-limits-for-responding-to-data-protection-rights-requests/ ) to respond nor can we expect a volunteer to always respond within x hours. 

I do agree with Sander, this is better fixed in Joomla core. For now I have made a language override to provide more information and it reads:
```
Your information request has been confirmed. We will process your request as soon as possible, the export will be send to your email.
```
Other suggestions are welcome if this isn't good enough.

**Comment by brianteeman** [comment]
That's perfect - thank you

**Comment by brianteeman** [comment]
oops - just spotted a type

export will be send 
==>
export will be sent

**Comment by roland-d** [comment]
Fixed :)

**Comment by brianteeman** [comment]
PR submitted to core https://github.com/joomla/joomla-cms/pull/29125
