### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by sharpshooter91** [joomla/joomla-websites#1442]
There is a site maid on your platform that is fake. I just paid 60 NOK on that site and did not get tests for trucks that I paid for and the contact page is not in function. I will have to contact the police if you do not do something about this? This is the site https://www.teori-prover.no/ .

**Comment by pe7er** [comment]
Sorry to hear about your issue with a Norwegian company who did not do what they promised you. Joomla is not affiliated in any way with that company. 

Joomla is an award-winning content management system (CMS), which enables you to build web sites and powerful online applications. Everybody can install the Joomla software on a web server to create and maintain their own website.

So Joomla.org is not the owner of the domain that you mentioned. You can find information (like the owner) of a domain via https://lookup.icann.org/ 

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
