### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ahoyosm** [joomla/joomla-websites#1446]
I can't access to my website

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
