### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by Jannetterodriguez** [joomla/joomla-websites#1448]
We are unable to save information on our articles..

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
