### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by ryanH-1999** [joomla/joomla-websites#1449]
Going to login to edit my website, but a blank window was shown. The Safari tab name was "Error 1054 : Unknown Column ... (see picture).
I updated the Joomla website version, and this suddenly happened. If you can check it.
Best of luck, 
Ryan
<img width="316" alt="Screen Shot 2020-05-22 at 5 19 45 PM" src="https://user-images.githubusercontent.com/65774415/82677287-70ae2880-9c50-11ea-940f-782006e6367d.png">

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
