### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by andr2510** [joomla/joomla-websites#1450]
Security problem. When joomla reports about sql error i see:
![image](https://user-images.githubusercontent.com/3646863/82825831-99cef300-9eb4-11ea-999d-5062394bd732.png)
![image](https://user-images.githubusercontent.com/3646863/82825911-c4b94700-9eb4-11ea-872b-3a5daed63816.png)
![image](https://user-images.githubusercontent.com/3646863/82825924-cc78eb80-9eb4-11ea-9be9-aabfd1854893.png)
![image](https://user-images.githubusercontent.com/3646863/82825961-e31f4280-9eb4-11ea-8388-2af63775ff3a.png)
![image](https://user-images.githubusercontent.com/3646863/82826012-f92d0300-9eb4-11ea-8aaa-0d1265e07ac1.png)
i can see db pref.

**Comment by conconnl** [comment]
On which *.Joomla.org website is this?

**Comment by andr2510** [comment]
It is not on *.Joomla.org
It on my website on joomla cms
  
>Понедельник, 25 мая 2020, 18:29 +03:00 от Wilco Alsemgeest <notifications@github.com>:
> 
> 
>On which *.Joomla.org website is this?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением, Тукманов Андрей

**Comment by conconnl** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
