### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by JGS83-dev** [joomla/joomla-websites#1459]
I have a problem in the version 3.9.19
when i acces to admin area i cant see the nav and the lateral menu
![image](https://user-images.githubusercontent.com/26470443/83713087-70187900-a5e4-11ea-922c-6702cc3ef02c.png)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
