### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Helmosan** [joomla/joomla-websites#1467]
Hello, i have trouble with a site which is moved to a new server.
When moved to the new server ccideal stopped working and i tried to remove the extension but when i try to reinstall it won't let me.
I can install other extensions so my temp path is correct.
Also i moved other sites with the same ccideal and they are working correct.
I've tried contacting the maker of ccideal many times, but i get no answer or they give me a reply but then nothing happened.
My first email to ccideal was 6 mei.
Is there something you can do for me?
I'm having now a webshop with no payment option and i'm getting really frustrated.

Best regards, Jeroen Lodewijckx

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
