### ISSUE TITLE
[api] phpDocumentor 3 Support

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1469]
I'm leaving this here because it's ultimately going to affect multiple repositories and servers.

phpDocumentor 3 is currently in the release candidate phase, meaning a stable release will be coming soon.  The project should begin preparing to use the new version of the package.  Note, it looks as though phpDocumentor 2 will not support some of the newer PHP 7.x syntax so the upgrade will be necessary to generate a proper build for CMS 4.0 or Framework 2.0 based on the builds I've attempted locally.

In order to complete this upgrade, the following changes will be necessary:

- [ ] https://github.com/joomla/joomla-cms repository
    - The `phpdoc` ant task in `build.xml` will need to be reviewed for compatibility with the new software version (it's a glorified wrapper around running `phpdoc` straight from the command line with all the arguments set to the right values)
- [ ] https://github.com/joomla/api.joomla.org repository
    - Update the template to address any B/C breaks or to integrate new features in the new software version
- [ ] Jenkins CI Server
    - Update the version of phpDocumentor used in the `Joomla! API > Deploy Docs - CMS` job (right now it's installed basically as `composer install -g phpdocumentor/phpdocumentor` on the `jenkins` user account, it might be worth looking at switching to a PHAR build with 3.0)
    - Note, this job can still build the documentation for Joomla 2.5, which is generally only triggered if the template changes enough that a fresh build should be deployed; if possible Joomla 2.5 compatibility should be kept here as long as that version's documentation is publicly listed on the site

**Comment by Hackwar** [comment]
- The tasks for the CMS has been moved to a drone setup on api.joomla.org.
- The template has been updated to phpdocumentor 3 largely.
- The tasks on Jenkins have been deprecated and moved to drone. I would say that we wont be rebuilding Joomla 2.5 again, so I wouldn't worry about that being dropped.

I opened a new issue on api.joomla.org for evaluating new features of phpDocumentor 3. Otherwise I think the tasks in here have been solved and I'm going to close this issue.
