### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by komlab13** [joomla/joomla-websites#1472]
I can't login in anymore to Joomla

**Comment by pe7er** [comment]
What's the address of the Joomla.org website you want to log in?

**Comment by komlab13** [comment]
www.ceremonial.ch/administrator

**Comment by pe7er** [comment]
That's not a joomla.org website. This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
