### ISSUE TITLE
Let's talk about Web Vitals

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1473]
**This issue is an open call to review how our sites are built. The change is coming.**

**Web Vitals** is an initiative by Google to provide unified guidance for quality signals that are essential to delivering a great user experience on the web.

Google has provided a number of tools over the years to measure and report on performance. Some developers are experts at using these tools, while others have found the abundance of both tools and metrics challenging to keep up with.

Site owners should not have to be performance gurus in order to understand the quality of experience they are delivering to their users. The Web Vitals initiative aims to simplify the landscape and help sites focus on the metrics that matter most, the **Core Web Vitals**.

https://web.dev/vitals/

- Largest Contentful Paint (LCP) – Loading
- First Input Delay (FID) – Interactivity
- Cumulative Layout Shift (CLS) – Visual Stability

![web-vitals](https://user-images.githubusercontent.com/385780/84643749-8dabe380-aefe-11ea-99d3-e7a9b9692ca6.png)

It looks like the web is going to be shaped under these measures in 2021. **The Google Search Console is already reporting poor pages under these measures**. The search algorithm update is live.

![web-vitals-console](https://user-images.githubusercontent.com/385780/84644309-4b36d680-aeff-11ea-8286-645e3261a9e0.png)

So, Google is going to start deindexing or lowering the ranking of sites with poor pages. The impact is general to the web. 

We have Joomla 4 around the corner, and the developers are in the road to prepare a general renewal of design and extensions. **How can we align the Joomla 4 renewal with Web Vitals?**

**Comment by mbabker** [comment]
If you’re focused on building an internet that is optimized for machines then you can build with these guidelines as your top priority.

I have always, and will continue to always, advocated that building websites with a primary focus on scoring well in automated tooling review is not a good development philosophy.  Using the KPIs this type of tooling highlights as guidelines is beneficial toward delivering a positive end user experience, but it is not THE answer.  You are still building websites to be used and consumed by human beings, you should be optimizing your websites for that target audience.

I spent almost two years rebuilding one of my websites from the ground up and not once in those two years did I audit the site with tooling like this until after it was live.  Once I did, the pages consistently score in the mid-to-upper 90s because I apply subjective best practices to my builds including:

- Use minimal JavaScript
- Use build tooling such as PurgeCSS to deliver only the CSS actually used inside the website
- Use HTTP/2 features to signal preloading necessities

Now, in the case of `joomla.org`, the CSS part of that item is really quite difficult without changing the root template so it does not provide a compiled CSS asset and require every individual website to build its own asset (effectively removing the use of the CDN for the common root build).  The template delivers the entirety of the Bootstrap 2 CSS because it is a general use template and must be adaptable for use across two dozen separate builds, it cannot be opinionated in stating what portions of the framework are or are not available for its users.

So long and short, web vitals should be monitored in building out a template, but they should not be the primary guiding principles in a build unless your aim is to build something that is more suited for the machines in Google’s data centers than the humans viewing it in a browser.

**Comment by anibalsanchez** [comment]
@mbabker In general, I agree with your view.

The only point that I would add is that the user experience also drives these KPIs. 

The main difficulty is finding the KPIs that can be understood by people and processed by machines (google crawler). At this point, the overlord has decided that these are the metrics, and we have to deal with it. 

In my view, it is easier to grasp the concept of:

- Page Loading Time (LCP)
- Interactivity, when the page is ready to work with (FID)
- When the page stops changing (CLS)

If we can shine on these measures, then user experience and the final results will improve.

**Comment by mbabker** [comment]
So is it your intent that the next iteration of the project’s websites be built with a machine first interface or a human first interface?  If it’s machine first, then skip the entire browser presentation and just deliver a RESTful interface and let others decide how to present things.  If it’s human first, then Google’s tools should be used to assist in benchmarking the effort but should not be used as a decision making tool; by following modern development practices you can build human first while delivering machine friendly results.

Too much emphasis is placed on meeting machine requirements, and I have seen teams get to the point where their work on achieving high PageSpeed scores has resulted in visual declines in the human use and interactions with websites, or applying over optimizations to websites which machine optimize one aspect of the site while worsening another part of a website (I have a Joomla client where a plugin was inlining “critical” CSS but in doing so was duplicating it resulting in duplicate rules when rendered and increased page size).

The opening of this issue implies that .org needs to be heavily Google optimized.  I say that is the wrong approach to building a website.

**Comment by anibalsanchez** [comment]
We need to strike the balance to keep everyone happy. A modern web interface.

**Comment by anibalsanchez** [comment]
A recent update:

**Timing for bringing page experience to Google Search**
https://developers.google.com/search/blog/2020/11/timing-for-page-experience

**We're announcing that page experience ranking signals for Google Search will launch in May 2021.** This will combine Core Web Vitals and previous UX-related signals.
https://twitter.com/googlesearchc/status/1326192937164705797

There is time for SEO improvements taking into account Web Vitals until May 2021.

**Comment by Llewellynvdm** [comment]
@mbabker is correct, trying to strike a balance makes you lose out on both sides, and be good at nothing really. I think the machine of our day is constantly improving, but the user experience is suffering dramatically.

Not only should we place humans first, but we should place [humans first, no matter their abilities](https://blog.mozilla.org/accessibility/).

**Comment by anibalsanchez** [comment]
Just to be clear, I'm not arguing in favour of any machine vs human debate. 

The main point of this open issue is that Google SEO is going to take into account Web Vitals signals in May 2021. The websites that don't pay attention to these metrics are going to rank lower.

It's not crazy difficult, however, some effort is necessary to make it work on our current sites.

![tailwindcss_joomla-100](https://user-images.githubusercontent.com/385780/101377269-e5297b80-38b1-11eb-9927-4da6a018f9f9.png)

**Comment by conconnl** [comment]
It sounds very important to you! The only thing I can suggest is for you to work with the JED4 team to make it as close to it as possible. Which seems to be needed (according to Google) as the current JED only has 40 urls with OK, 5690 urls are bad and 1254 URLs need improvement.
The other sites look a lot better on this level.

In addition you could join production to work on the new template for all JOrg websites.

**Comment by anibalsanchez** [comment]
I wish I could do more in my available time.

Please, open an issue to check the URLs. Maybe it is a tagging problem.
