### ISSUE TITLE
Joomla3.9管理員無法登入後台

### ISSUE THREAD

**Issue by 101angus** [joomla/joomla-websites#1476]
我是使用hostgator的空間.
內建的Joomla 安裝包 版本 : 3.9.19, 2.5.28
架設時有設定管理員帳號密碼.
也有在架設好之後.
在後台設定了一些模板之類的設定.

間隔幾個小時後再使用.
後臺要求我重新登入.
帳號密碼都沒打錯.
系統也有送出訊息.
又回到登入畫面.
完全沒進入後台.
https://imgur.com/a/9cpj2qr

使用索取密碼也無效.
嘗試打錯誤的密碼.
系統也能正確判斷.
https://imgur.com/a/Leljyg5
想知道怎麼解決登入問題.

**Comment by particthistle** [comment]
@ 101angus该区域用于报告Joomla官方网站的问题。

您的问题出在您自己的网站上，因此支持的更好选择是：
-联系Hostgator支持
-访问https://forum.joomla.org
-与中文翻译小组的人员联系，他们可能会在中文Joomla资源和网站上了解更多。 https://community.joomla.org/translations/joomla-3-translations.html#zh-cn

这个问题有几个部分：
-默认情况下，Joomla在后端管理员区域的会话时长为15分钟。闲置15分钟后，出于安全考虑，您的会话已关闭。
-如果您在重新登录时遇到问题，则可能未正确记录您的用户名和/或密码。
-如果该帐户是超级管理员帐户，则无法通过“重置密码”选项恢复密码，但是可以通过遵循以下Joomla文档来重置密码：https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F/ zh-cn

我目前尚不了解中国的Joomla社区，但是如果您找到一个社区，那就很高兴让他们参与并在https://community.joomla.org/user-groups/asia.html列出。

希望对您有所帮助。


--

_Google Translation_

I am using hostgator space.
Built-in Joomla installation package version: 3.9.19, 2.5.28
When setting up, the administrator account password is set.
There are also after erection.
Some settings like templates are set in the background.

Use after a few hours.
The background asked me to log in again.
The account password is correct.
The system also sends messages.
Return to the login screen.
Did not enter the background at all.
https://imgur.com/a/9cpj2qr
![image](https://user-images.githubusercontent.com/5515866/85917306-534a2b00-b89c-11ea-9d2d-0144e10ec174.png)


Using the request password is also invalid.
Try to type the wrong password.
The system can also judge correctly.
https://imgur.com/a/Leljyg5
![image](https://user-images.githubusercontent.com/5515866/85917309-5fce8380-b89c-11ea-98a1-4383e448618b.png)

Wondering how to solve the login problem.


--

@101angus this area is for reporting problems with the Joomla official websites.

Your issue is with your own website, and so your better options for support are:
- contact Hostgator support
- visit https://forum.joomla.org
- Contact someone from the Chinese Translation team who may know more on Chinese Joomla resources and sites. https://community.joomla.org/translations/joomla-3-translations.html#zh-cn

The problem has a few parts to it:
- Joomla by default has a 15 minute session length in the backend administrator area. After 15 minutes of inactivity, your session is closed for security.
- If you're then having trouble logging back in, your username and/or password may not have been correctly recorded.
- If the account is a Super Administrator account, then you can not recover the password via the "Reset Password" option, but you can reset it by following this Joomla Documentation: https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F/zh-cn

I'm not aware of a Chinese Joomla community at this time, but if you do find one, it would be great to get them involved and listed at https://community.joomla.org/user-groups/asia.html

I hope that helps.

--
