### ISSUE TITLE
Email Tracking Is Overeager

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1477]
As demonstrated in #1475 system emails coming from the `community.joomla.org` Joomla installation (others may be configured similarly) are being rewritten with tracking links to a third party service.  Aside from the fact this isn’t disclosed anywhere, the tracking links are overeager in that they are being written into emails that they should not be.  Emails such as those sent as part of the password reset or user registration processes really should not use any form of trackers, this can come across as deceptive if the link to a confirmation page is obscured through trackers or does not point to the site that is expected (and I would not expect a new registration on `community.joomla.org` to be confirmed with a link to `tracking.joomla.org`).

The email tracking should be limited to explicit marketing related emails, such as the newsletters.

**Comment by conconnl** [comment]
The tracking is required for the new supplier to get to know us, make sure we don't send spam around and those kind of reasons.
These kind of assessments are rather logical for professional services, as they also need to make sure that their systems aren't compromised. Especially with the big amount of false registrations we had the last couple of months (mail addresses) which do not exist, simply because the Google Captcha isn't 100% secure anymore, I find it completely understandable that these kind of checks are required.

After a bunch of mails the tracking can and will be disabled, as it isn't required anymore after the analyses phase.
The setting to turn off the tracking is not yet enabled for us until we have send more mails, we expect this can be done by the end of the week.
That their documentation wasn't fully up-to-date and created an issue for some users on link level (even though the tests didn't show this issue), can happen to any organization and they fixed it directly after asking them. We also find these kind of problems in the CMS, even though a lot is tested.

Other sites are not configured yet, as the analyses need to be finished before we are going to take any additional step.

**Comment by conconnl** [comment]
In the meantime all validations have been done by the new supplier and the tracking has been disabled again!
