### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by logoeffect** [joomla/joomla-websites#1479]
The site does not easilly support apple touch icons.  I cannot figure out how to get them working with my site.  I will pay for help.  If you can help or let me know who can please let me know

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
