### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by mthwltc** [joomla/joomla-websites#1480]
Dear Sir,

We are using Joomla backend system to create a webpage. Yesterday the backend system admin page cannot access. Please kindly help to resolve the problem. 

The admin page address is https://www.hkmover.com/administrator/

Thanks

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
