### ISSUE TITLE
puging

### ISSUE THREAD

**Issue by NISHA275** [joomla/joomla-websites#1484]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
