### ISSUE TITLE
Make Joomla 4! Hep Screen Images Responsive

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-websites#1488]
Go to a Joomla 4 site Administrator interface. 
Select Content -> Articles -> Help Toolbar button
The Help screen scrolls left/right because the Screenshot image is not responsive.

Open the Source document:
https://help.joomla.org/proxy?keyref=Help40:Content_Article_Manager&lang=en
Narrow the screen - the Screenshot is responsive.

I tested the Proxy delivered Help screen by adding this to the image tag: style="max-width: 100%; height:auto;"

I guess this counts as a Feature Request.

**Comment by mbabker** [comment]
If it can be guaranteed that only "static" images are being delivered throughout the wiki then it might be feasible to add those rules to the main `<img>` tag.  https://github.com/twbs/bootstrap/commit/09cdee2f03aaad5c5a767fbec2e3896ad3d1f980 explains why Bootstrap changed from applying rules directly to images to requiring the `img-responsive` class (later renamed `img-fluid`) for responsive images, so that needs to be considered before making a CSS change to a root HTML element.

**Comment by ceford** [comment]
I may be wrong, but I seem to remember that the proxy delivered Help screens were responsive before the recent changes to help.css. I gave the wrong url for the comparison above it should be:

https://docs.joomla.org/Help4.x:Content_Article_Manager

There the css (load.php) does contain responsive image styling. I am only suggesting a comparable change to help.css.

**Comment by ceford** [comment]
Thank you! I see the Help screen images are now responsive.
