### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by Mircodgteam** [joomla/joomla-websites#1490]
I can't find my articles in the articles page

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
