### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by frogking12345** [joomla/joomla-websites#1491]
Help I'm getting random emails and my web master had quit and I need help deleting our account https://www.dpinstall.com/ this is our domain I do have the logins but i need some assistance.
![Untitled](https://user-images.githubusercontent.com/68340225/87562958-47c07780-c684-11ea-812f-0ad200186bab.png)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
