### ISSUE TITLE
[jcertif] Feature Restorations: Certified Users Directory - Avatars, Logins and Other Features

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1493]
While writing up #1492 I went on to discover a range of other issues with the Certified Users Directory that need reporting.

**Logins**
When we sat the exams, our logins were to exam.joomla.org not certification.joomla.org.
- My exam login is now blocked.
- My exam login does not work on certification
- I've had to go back and reset my password on certification.joomla.org.

This is most likely the case for all certified administrators, and has not been communicated to users.

**Avatar Photos not linked**
As part of applying for certification you need to have uploaded a photo in the registration process. Since moving from exam.joomla.org to certification.joomla.org the majority of the photos are not now being displayed.

- I've just reset my user account on certification.joomla.org, and now find that photos are Optional in the new profile.
- You should be able to bring all of the photos back from exam to certification rather than users (most who now don't know they need to log into the certification site to fix a problem that shouldn't have occurred) having to upload a new photo to their profile.

**Sorting**
The default sort is not practical, and the filtering and sorting (as mentioned in #1492) no longer being available makes looking for a Certified Administrator a very convoluted and clumsy process.
- It looks to default sort by the registration order for the exam, not the certification date or the user's surname which would be more practical. I only assume this is the default search as I know my registration date is much earlier than my certification date (there's an earlier exam in my history, but we won't go there).

**Comment by conconnl** [comment]
> **Logins**
> When we sat the exams, our logins were to exam.joomla.org not certification.joomla.org.
> 
>     * My exam login is now blocked.
> 
>     * My exam login does not work on certification
> 
>     * I've had to go back and reset my password on certification.joomla.org.

In all the reports provided by this team, it's clearly explained that the exam website will be removed.
You also received a personal mail with a new account and login credentials and an explanation why you received this new account.

> This is most likely the case for all certified administrators, and has not been communicated to users.

Sorry, but this is an assumption, many of the newly created accounts logged in and updated their profile.
 
> **Avatar Photos not linked**
> As part of applying for certification you need to have uploaded a photo in the registration process. Since moving from exam.joomla.org to certification.joomla.org the majority of the photos are not now being displayed.
> 
>     * I've just reset my user account on certification.joomla.org, and now find that photos are Optional in the new profile.
> 
>     * You should be able to bring all of the photos back from exam to certification rather than users (most who now don't know they need to log into the certification site to fix a problem that shouldn't have occurred) having to upload a new photo to their profile.

Sorry, but this is also an assumption.
In the mail was explained, that the data will slowly be moved as it's a manual action from a non-joomla system to a Joomla one, but that the users can add the data themselves if they want to, but can also wait until it's done.

> 
> **Sorting**
> The default sort is not practical, and the filtering and sorting (as mentioned in #1492) no longer being available makes looking for a Certified Administrator a very convoluted and clumsy process.
> 
>     * It looks to default sort by the registration order for the exam, not the certification date or the user's surname which would be more practical. I only assume this is the default search as I know my registration date is much earlier than my certification date (there's an earlier exam in my history, but we won't go there).

We don't have the order / registration date information, so that is certainly not what is used.
The data is manually taken from the old directory, from the official displayed user directory.
Nothing has been changed on dates.
**OLD**
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/11913918/87642578-04c8d780-c74a-11ea-805b-65dd98284b52.png">

**New**
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/11913918/87642635-127e5d00-c74a-11ea-8705-8d25a125b4a8.png">


As you have created an additional request about a feature, the rest of the remarks are answered, this issue is closed.
