### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by VladLaz0203** [joomla/joomla-websites#1503]
The most recent request was denied because it contained an invalid security token. Please refresh the page and try again. Я не могу зайти на сайт как администратор, и сайт не работает, видна просто заглавная страница и все.( http://school8.slav.dn.ua/ сайт с которым проблемы)

**Comment by conconnl** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
