### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jeymz26** [joomla/joomla-websites#1504]
My client has a website created with Joomla. It was not maintained and now the website is damage and cannot load its content. I am new to Joomla and I would like to learn how to restore the old backup so I can restore the website and do updates.

Thanks

Domain: screwmaster.com.ph

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
