### ISSUE TITLE
Social Sharing Plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#151]
On category pages eg https://www.joomla.org/announcements.html you will see that there is metadata for each of the articles. If you check with the facebook debugger you will see that only the metadata for the first article is used. Not sure about twitter.

@Radek-Suski

**Comment by brianteeman** [comment]
Also excluding the plugin from the category view such as the one above isnt an option either because as well as disabling the buttons it disables the metadata.

**Comment by mbabker** [comment]
Probably need to tweak the plugin so that it builds appropriate metadata for the category pages instead of lumping all the article metadata into the head.

**Comment by brianteeman** [comment]
Actually I just noticed that the facebook debugger is NOT using the tags on the announcements page at all

>To find the object, these are the redirects we had to follow
original	https://www.joomla.org/announcements.html
og:url	https://www.joomla.org/announcements/release-news/5634-joomla-3-4-5-released.html

**Comment by mbabker** [comment]
I'll try to carve some time out over the next couple of days, but basically we need these changes in the plugin:

- [ ] Add a context check for supported contexts/extensions
- [ ] Adjust `onContentAfterTitle` to only run [these lines](https://github.com/joomla-projects/plg_content_joomlarrssb/blob/master/joomlarrssb.php#L172-L189) on the article view
- [ ] Add a `onContentPrepare` event listener to handle adding the category metadata for the page; this will need some extra checks to ensure it only triggers once since all of the events on the non-article view are triggered once for every item on the page

**Comment by brianteeman** [comment]
Also I think that it might be conflicting with the twitter and facebook code that is in the template itself (and doesnt seem to be working correctly if I read the code accurately)

**Comment by mbabker** [comment]
Do you have a specific example to look at?  Using the announcements page none of the items in the base template are conflicting at a quick scan.  I have `og:image`, `og:site_name`, `twitter:card`, and `twitter:site` set with some default values that are hardcoded and won't change and some code to check for Twitter's tags and add defaults if nothing else sets them (TODO - Need to add the equivalent for Open Graph).  `og:image` is allowed to have multiple tags the way I read up on the standard so that shouldn't be an issue.

**Comment by brianteeman** [comment]
Looks like I misread the template code

**Comment by mbabker** [comment]
Should be cleaned up now.  Probably would be a good time for someone to review the category descriptions and images to make sure they're relevant and good quality.
