### ISSUE TITLE
[idp] renew ALL consents

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1510]
It would be really useful if there was a renew all consents button. At first I only saw the one renew button and assumed that was everything. And its a bit of a pain to renew them all  manually and will become more of a pain as more sites are added.

**Comment by HLeithner** [comment]
I wrote roland more or less the same ;-)

**Comment by brianteeman** [comment]
It will get worse as ore sites are added.

Not sure what happens when you have consents with different dates and what the wording of the email would be in that scenario

**Comment by sozzled** [comment]
See also forum discussion on this matter:  https://forum.joomla.org/viewtopic.php?f=7&t=981498

**Comment by particthistle** [comment]
Adding to the suggestion here:

**Extend consents to a longer window of time**
Not sure which regulations require the consent process (GDPR I'm sure) but is there a potential to allow users to extend the consent for a longer window of time? And if you are to extend a consent, can the "Renew All" option @brianteeman proposes here effectively extend all consents to the interval from the time you're renewing the consent (eg if one consent is 3 months old with 9 months to run, and another is due for consent, then renewing the one that is due could also extend the first one to 12 months or the extended duration.

**Single Click Consent**
Can the email link be configured with a tokenised identifier to make the process a single click - the person with the email is the person who's the volunteer, and to simplify the consent approval process when they click, the consent is granted.

Currently you need to authenticate, find the page and acknowledge all the consents.

If they instead want to revoke, then they can log in to do so.

**Can we look at improving the messaging**
~1572 people would have received this email on Tuesday (That's the number of Joomlers shown at volunteers.joomla.org today). Of those, it would be interesting to see the stats on how many have logged into the Identity portal, and before that an age progression of when many of them last logged into the site. If the number of people asking for tips on logging in is anything to go by, 10x that number are ignoring it, and after the weekend, the 1572 may plummet to just a few hundred as a result.

![image](https://user-images.githubusercontent.com/5515866/89974877-a4c14480-dca7-11ea-98ad-f2754fa3150f.png)

This email, as it's now going to go out annually, is a good opportunity for Joomla to re-engage with Joomlers world wide, and the Volunteer Engagement team could consider a campaign to include in the messaging to invite users review their involvement (eg check out the Help Wanted section), review their personal profile and team memberships, and generally thank them (though the email is a generic one) for their continuing involvement and support of the Joomla project.

**Comment by roland-d** [comment]
> Not sure what happens when you have consents with different dates and what the wording of the email would be in that scenario

That is not only you wondering :smile: The question should be I think if we should send 1 very generic email or 1 email for each consent. That is something we need to look into, especially when more sites get connected.

I will add the all button.

**Comment by roland-d** [comment]
@partchristie consents are for 1 year, I don't think there is a need to extend this time. As for the email discussion, let's put that in an issue of it's own. This issue is about an all button.

**Comment by sozzled** [comment]
> @partchristie consents are for 1 year, I don't think there is a need to extend this time. 

This does not seem to be the current situation.  As I showed in the screenshot in the forum discussion https://forum.joomla.org/viewtopic.php?f=7&t=981498, the current situation shows that I my current consent expires in four days.  This is only three months after I gave my previous consent.

Please confirm that consents are for one year.

**Comment by hvdmeer** [comment]
I just renewed my consent and they were all for one year

**Comment by sozzled** [comment]
Thanks, @hvdmeer.

I renewed **_one_** of my consents and it's renewed for a year from today.  As @brianteeman pointed out at the beginning, I will need to renew each of the remaining consents, individually, before they are **_all_** renewed for a year.

It seems that, in the initial implementation of the idea in May this year, the consents were set to expire three months after people agreed to them.

The following screenshot shows the current situation in my case.

![j!consents1](https://user-images.githubusercontent.com/877778/89982916-f4107080-dcb9-11ea-9d4b-758ae87be780.jpg)

**Comment by conconnl** [comment]
@particthistle 
Please keep in mind that this specific issue called "[idp] renew ALL consents" a request about creating a renew all button.
Your reply is certainly of great value, but it does not fully relate to this specific issue.
In the list you can see what issues are created https://github.com/joomla/joomla-websites/issues and reply on-topic within one of them or create a new one for a specific topic. It would be a shame if things get lost in translation, because multiple topics are mixed in one thread.

@sozzled you have never given any consent before.
The data has been migrated from the JVP without consent feature to the Identity with consent feature, there was a simple choice between migrating everything and having an empty JVP website or adding a temporary consent.

I must say "I have read your forum reply, I personally find it having a reasonable amount of negativity against other hard working volunteers. This will probably not help in improving things."

Thank you both!

**Comment by sozzled** [comment]
@conconnl :  How do you know I have "never given any consent before"?  Prove it!

**Comment by conconnl** [comment]
> @conconnl : How do you know I have "never given any consent before"? Prove it!
For the fact that we have never requested Consent on the migration of the data, that the consent date was automatically added by us to make sure that the JVP site wasn't empty after the migration. That mail sent by the team, was the first consent mail ever.

**Comment by brianteeman** [comment]
Consent was given on the original site!!

Please look at the problem and stop getting diverted into attack mode. You did promise me that you would never ever comment on any issue that I created.

**Comment by sozzled** [comment]
@brianteeman   I'm kind of sitting on the fence with this.  In one way I can understand how it's a bit of a hassle if you have several consents to update and it takes a few seconds to update them individually.  In that way it would make sense if there was a "consent all" button.

On the other hand (and this may seem a bit far-fetched at the moment), if there were different terms of use or conditions w.r.t. each of those consents (e.g. if the policy settings for them different by imposing additional conditions or relaxing some conditions or varying the extent to which that policy applies to a certain website operated by j.org) then it makes sense to consent (or withdraw consent) to one or other of them.

While, at the moment, the conditions for all these things are identically worded (I think, but I haven't checked), it's possible that in future one or more of them could change.  In that case it probably makes sense to go through the mechanics of tick-and-flick each one as each one comes due for renewal.  Further, if a new site is added to the mix (and I can think of a good example of one to be added to the list), these consents may likely expire and become due for renewal at different times.

For these reasons, I'm undecided.

**Comment by brianteeman** [comment]
The consents should be the same across all sites managed by the identity portal
If a site is added during the year there is no problem still clicking on renew all - nothing says you cant renew early. Its only a consent not a payment ;)

**Comment by sozzled** [comment]
Well ... (I don't want to argue the toss with you) but there is something that says you can't renew _**too**_ early.  The ability to renew a consent becomes available within 30 days of the expiration of the consent.  See the second paragraph in the screenshot I posted earlier.  But I agree with you otherwise:  you're right that it's not a payment/subscription matter where people, however, while the ability to opt-out is persistent the ability to opt-in (and opt-in to all things at one time) is not available.

While I also agree that the mechanism to consent should operate consistently across all sites managed by the portal, I'm not sure that the same thing can be said about the terms of use/conditions/policy settings should likewise "be the same".  At the moment, yes, they are the same but that doesn't imply that they will always be the same.  As I said earlier, I'm still undecided.

**Comment by roland-d** [comment]
Just wanted to give an update on this topic. We are working on adding the Consent All button and it is currently in testing phase.

**Comment by brianteeman** [comment]
Thanks for the update

**Comment by sanderpotjer** [comment]
The button to approve all consents is now available on the consents page of the Joomla Identity Portal.
