### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Snawsen** [joomla/joomla-websites#1512]
Hola.
Me he registrado en Joomla, pero no recibo el e-mail para la activación de la cuenta.

Muchas gracias.

**Comment by conconnl** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.
Please use English as well in your message.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
