### ISSUE TITLE
[jrd] 

### ISSUE THREAD

**Issue by Martowalsh** [joomla/joomla-websites#1516]
Hi, we at Centralcabs.ie have had some changes to our management structure and web page admins. The result is that our Superusers have left the business and we cannot sign in to the back end of our site. We were left with one Superuser's login details but the password does not work and we cannot request a new one as another Superuser or admin needs to do this.
What are our options?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
