### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by samilapf** [joomla/joomla-websites#1520]
Older PHP version 7.2
Your site is currently using PHP 7.2.32. This version of PHP has entered its “Security maintenance” phase since Saturday, 30 November 2019 and has stopped receiving bug fixes. It will stop receiving security updates on Monday, 30 November 2020 at which point it will be unsuitable for use on a live site.

Akeeba Backup will stop supporting your version of PHP soon after it becomes End-of-Life on Monday, 30 November 2020. We recommend that you plan your migration to a newer version of PHP before that date. We recommend PHP 7.3 or later. You can ask your host or your system administrator for instructions. It's easy and it will make your site faster and more secure.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
