### ISSUE TITLE
[jlaunch]  https://launch.joomla.org/  no joomla 3.9.21 update

### ISSUE THREAD

**Issue by PixRob** [joomla/joomla-websites#1523]
After using this testsite http://schelpen.joomla.com at https://launch.joomla.org/ for a year joomla 3.9.21 update is not possible
Extension update is not possible either

![2020-08-26_114944 updates op schelpen site](https://user-images.githubusercontent.com/8125161/91978999-60184e80-ed25-11ea-9536-ca6261e68948.jpg)

> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by PixRob** [comment]
Message when trying to install
An error occurred

    0 syntax error, unexpected ''PLG_INSTALLER_PACKAGEINSTALLE' (T_ENCAPSED_AND_WHITESPACE) 

By the way.

 **_Also message with low php version_**
![2020-09-03_syntax , unexpected](https://user-images.githubusercontent.com/8125161/92127965-2a956300-ee02-11ea-923b-294580b5ad91.jpg)
![2020-09-03_162042 php version joomla lanch freesite](https://user-images.githubusercontent.com/8125161/92127979-2f5a1700-ee02-11ea-8f8f-1ecf07e5ca6a.jpg)

**Comment by conconnl** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

One possible thing you can try is: Go to Components -> Joomla Update -> Check for Update -> Reinstall core files
Which probably result in the same error as it's about the installer plugin.
If you have file access you could download the 3.9.20 full package here https://github.com/joomla/joomla-cms/releases/tag/3.9.20 and upload all files except for the installation folder over the current files.

Thanks!
