### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by Rasmysok** [joomla/joomla-websites#1524]
Greetings

I am writing to you in connection with a problem that I encountered recently. Namely, I cannot upload pictures to my own site https://bibik.com.ua, which is made on the Joomla platform.
All the design and structure was done by my employee, who is now far from me. I have  full access to my page.
Unfortunately, I cannot reconnect from them, so I decided to write to the support service so that I can make changes in the blocks.
So far, I've run into problems:
Can't update the platform to the latest version
I can not upload pictures and change pictures in blocks
I suspect that he may have mistakenly put the security protocol, but this is just my guess

In connection with the above, I ask you to help me figure out by downloading pictures and updating to latest version.

Thanks in advance,
Vitaly

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
