### ISSUE TITLE
Joomla Beta 4 Update [joomla.org] 

### ISSUE THREAD

**Issue by wbuk** [joomla/joomla-websites#1532]
I installed the latest version of Joomla 4 Beta 4 as I have done with the others.  
I downloaded the UK version.
I when to Joomla 4 beta 3 and install from file.  It almost completed then I got the message.

Oops! An Error Occurred
The server returned a "500 Whoops, looks like something went wrong.".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I tried to use FileZilla to install again but I think the whole site is now lost and will need a clean install.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

If you find issues in Joomla 4 Beta, please report them in the joomla-cms repocitory instead:
https://github.com/joomla/joomla-cms/issues

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
