### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-websites#1537]
to the joomla developers:

can you make / implement into the joomla installer to create a directory /administrator-j1209dj1j0f (numbers and characters different for each install) instead of /administrator so that hacking the site is more difficult for malicious people. putting the backend into /administrator is like an semi-open door

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/  (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by BRoehling** [comment]
> Hi,
> 
> This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.
> 
> For user support issues, please go to:
> -https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
> -https://docs.joomla.org/Main_Page
> -or find a service provider at https://resources.joomla.org/
> 
> For this reason, I'm closing your issue here.
> 
> Thanks!

why should I discuss a security problem in an open forum?

**Comment by pe7er** [comment]
The issue that you've posted here is not a software vulnerability. 
It's not a problem to discuss about it in a public forum.

If you do not want to discuss it on an open forum: this issue tracker is also publicly available.

You are right about being careful with posting about security issues in public. In case you find a software vulnerability in Joomla itself, please report it at https://developer.joomla.org/security.html
Thanks!
