### ISSUE TITLE
Impossible to update joomla 3.9.21 to 3.9.22 

### ISSUE THREAD

**Issue by Johann009** [joomla/joomla-websites#1540]
Please describe the I'm in the backend of my website, I'm logged in as a super user. When I click on apply "direct update" in direct transfer, the update page is displayed but the start of the transfer is blocked! ERROR: invalid login.
How is it possible?? I am logged as super user in the backend????
if I select "transfer and update", I select the package joomla 3.9.21 to 3.9.22 that I previously downloaded, then "send and install", joomla asks me to confirm my login and idem, ERROR Login!?

what's going on? first time I see this????
Thanks for your help.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
