### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Lovedecoded** [joomla/joomla-websites#1548]
To Whom It May Concern - 

My name is Stefan Deutsch and I am the owner of the domain - www.Love-Decoded.com. I am also the President of Global Human Development Inc., a 501(c)3 non-profit. We are using this domain and website for our research.

Our developer, Malcolm Simpson, from South Africa, who built the original website, has not been available to us since March of 2020.

We have been able to redesign the website - www.Love-Decoded.com - but we cannot access the Joomla admin area, which seems to require some older plug-in to be changed.

The user name and password are not working for us - we don't know if both or one them has been changed.

We need serious help to regain control of our website.

Thank you for you assistance.

SD

**Comment by pe7er** [comment]
Hi Stefan,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
- https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
- https://docs.joomla.org/Main_Page
- or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
