### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by wiruso4ek** [joomla/joomla-websites#1551]
Hello. Help me figure it out when the problem I enter the admin panel then a white background appears and nothing is displayed. website mobremont.ru tell me what to do? And is it possible to communicate with you in Russian?

**Comment by conconnl** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
- https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
- https://docs.joomla.org/Main_Page
- or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
