### ISSUE TITLE
[jcomm] removal of sites

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1556]
I see now that my submission to the new directory has been improved my existing one on the resources directory has been removed.

That's not thought through very well. As https://resources.joomla.org is the site that is promoted on our web sites  and the one that google will prefer for deeplinking etc for now it will be the number one place people go to 

Except now no one will see my training entry because you removed it instead of redirecting the existing entry.

There isnt even a link on the old site to the new site.

So thanks very much - you just killed my source of leads.

**Comment by conconnl** [comment]
It would help multiple if the tone of your communication would be much more friendlier, so that people are really willing to answer you nicely as well.
Maybe you should also check things first before doing assumptions, blaming etc.

This is your entry address on the old site, which is perfectly redirected, to which the volunteers thought about.
https://resources.joomla.org/item/joomla-training-uk
