### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by HussainRabia** [joomla/joomla-websites#1560]
When  I upload images using the  media, suddenly most photos  do not  load  even though  they 
 have  the  correct  extension ( jpg,jpeg) and  the  size is  less than 10 mb.  The images  load  into the  folders but only their  title showing in  text and  the image  does not show.  eg  Books.jpg
Please  help.
regards
Hussain Rabia

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:

https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
