### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by michaelaARLIS** [joomla/joomla-websites#1561]
My users are having an issue logging in. It says that they are "blocked". When I switch their user status to "enabled", the user is still seeing the "blocked" error message.

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:

https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
