### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by may33** [joomla/joomla-websites#1563]
Hello, I report an issue saw today on my latest Joomla version 3.9.23 (it also occurs on the former one): on the backend tags list manager, there is no way to publish the tag: when you select "Publish," it gets "Archived" value. So, on the tag components items, when asked to select a tag, none of the created ones is found. Is it a bug or does anything needs to be enabled in order to make them working well?
    Looking forward for a feedback, best regards.

**Comment by pe7er** [comment]
Thank you for reporting an issue with Joomla 3.9.23. 

However, this "joomla-websites" repository is ONLY for reporting issues with the *.joomla.org websites (to the site managers), not about the Joomla! CMS.

Could you please report the issue in the "joomla-cms" repository (for the Joomla CMS developers) instead?
https://github.com/joomla/joomla-cms/issues
Thanks in advance!

For this reason, I'm closing your issue here.

Thanks!
