### ISSUE TITLE
[joomla.org] partners.html meta data

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1579]
This probably should be updated

![image](https://user-images.githubusercontent.com/1296369/105091538-e3013200-5a97-11eb-8cc6-62dd455a5e51.png)

**Comment by conconnl** [comment]
Thanks, seems to be outdated for a few years.
I have updated it, hope I didn't miss one.

Also saw the Extensions one is outdated.
Updating that one as well

**Comment by brianteeman** [comment]
It's the title as well as the description

**Comment by conconnl** [comment]
I updated the title to follow the same structure as the Extensions Partner page.
On both pages the meta description is updated with all the names.

**Comment by brianteeman** [comment]
Thanks. I guess you need a procedure to update the metadata when partners are added and removed

**Comment by conconnl** [comment]
Indeed, but first you need volunteers who even manage these parts of the project. (I only do it because I have access, it's something simple, but not because it's part of my work)
As the partners were not even mentioned who are partner for many years, I guess the procedure wasn't defined since the page was created in 2005.

**Comment by brianteeman** [comment]
Perhaps it should be suggested to the legal & finance department as they are the ones who know when partners are added etc

**Comment by conconnl** [comment]
Let me not reply in details on that..... 
I think you can guess.
