### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by BrianGaddin** [joomla/joomla-websites#1580]
Hi. I am trying to log in to the admin of my site but I cant seem to remember the username to log in. I have tried the retrieval but none of my emails are recognized and says that the emails cannot be found. How can retrieve my log in info?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
