### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Divertoys** [joomla/joomla-websites#1584]
Cordial Saludo, mi nombre es Daniela Caballero de la empresa Divertoys Colombia, nosotros tenemos una pagina creada con ustedes y el día de hoy la pagina ha estado caida y no me deja entrar como administrador me da error, el dominio es www.divertoyscolombia.com, pedimos su pronta respuesta este mensaje.
Gracias
![pagina-caida](https://user-images.githubusercontent.com/78442779/106651214-d97ccd00-6561-11eb-8840-2670f460de22.jpg)

**Comment by pe7er** [comment]
Hola,

¡Este repositorio es SOLO para reportar problemas con los sitios web *.joomla.org, no sobre el CMS Joomla!

Para problemas de soporte a los usuarios, por favor vaya a:
-https://forum.joomla.org/ (por ejemplo el Foro en Español: https://forum.joomla.org/viewforum.php?f=24 )
-https://docs.joomla.org/Main_Page
-o encontrar un proveedor de servicios en https://resources.joomla.org/

Por esta razón, cierro tu tema aquí.

Gracias.

---
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
