### ISSUE TITLE
[jcomm] Joomla.org  issues

### ISSUE THREAD

**Issue by abaziarocco** [joomla/joomla-websites#1589]
Hi
there are a lot of problems in the last period on joomla.org.

- Th section "Learn joomla" was not working, so now that section has been substitute with a link go to OS Training for this video.
The problem in the section "learn joomla" is wrote : Learn Joomla!
Learn how to manage a Joomla website with **free video training** classes.

Instead on OS training you need pay $ 75.

- Another bug try to click on forget password. It send you a link with code of verification. You click on, you get back on joomla.org and it says "The code verification is invalid". So you can`t access. This bug is for over 6 months. I think many people left Joomla in the last period, for less support.

**Comment by conconnl** [comment]
You mention a lot of problems, but I only read two. (That is not a lot in my book).
The only confusing thing is, that you mention joomla.org while the issues are about community.joomla.org

Until the API is fixed by the supplier we can't do much.
If you are looking for videos you can also look hear: https://www.youtube.com/c/joomla/playlists?fbclid=IwAR2uiDnyDHddFnXREmfgalgw1eKjZA6L2k7PA1X3_HKbkIr9b7NCW_MnH3Q

I just tested the forgot password feature and it works perfectly on the community website.
Of course the verification code is invalid if you enter the incorrect username related to the verification code and the mail address you used to get it.

**Comment by conconnl** [comment]
Videos are being added again via YT Playlist
