### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by JKovalhuk** [joomla/joomla-websites#1599]
Hello. When I try to salve edtions in some article in Joomla I receive the message: 

"Forbidden
You don't have permission to access this resource.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request."

I am using Joomla! 3.5.4

Can someone help me?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
