### ISSUE TITLE
[jcomm] New social join buttons on home page of c.j.o

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#16]
Please review the twitter and youtube subscribe images and links.

Can these be improved and look less 2005.

![](http://s10.postimg.org/e0o7wwrk9/Screen_Shot_2015_08_05_at_7_08_11_pm.png)

**Comment by MATsxm** [comment]
6 months later...
Who's in charge and/or can help on CJO?

**Comment by mbabker** [comment]
I updated the YouTube iframe a while ago since that's using the https://developers.google.com/youtube/subscribe/#Configuration_Options widget.  Something custom would still probably be better though.

Twitter I'd just put one of https://dev.twitter.com/web/follow-button on there and be done with it personally.

**Comment by Joomv** [comment]
Font blew up in my face so I took the output on the main site, created png's out each one, created a sprite, added a new module position and mirrored  the main template as much as possible.

**Comment by MATsxm** [comment]
Cache issue?
Still the ugly bird
http://community.joomla.org/

**Comment by Joomv** [comment]
Ah I dealt with footer.
I shall now go prepare a quail!

**Comment by Joomv** [comment]
Better?

**Comment by MATsxm** [comment]
MUCH MUCH better!

**Comment by Joomv** [comment]
Closing.
