### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by groveshome** [joomla/joomla-websites#1600]
the website of www.centralmainebassmasters.com is not displaying anything correctly and when i try to log into the site with my username (not at the administrator login but at the joomla login (username of AnoeKE) and after supplying the password, it does not log me into the site to check it out.  This username and password did work for me just about 2 months ago.  Can you determine why i cannot login and why the site does not display correctly (there used to be links on the side like standings, schedule, etc....)  Thanks,  Charlie

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/ (for example the Joomla! Ideas Forum https://forum.joomla.org/viewforum.php?f=575 )
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
