### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by bazza14** [joomla/joomla-websites#1605]
I have been editing a site in Joomla 3.9.25. All was good until I came to select which menus to assign a module to. I had done this previously this session and it was ok but now the Main Menu layout is all over the place and ignores the menu select and expand options. See attached photo btw this is the isis template
![Screenshot_2021-03-28 Modules mod_hikashop - Ballyclander Ventures - Administration](https://user-images.githubusercontent.com/6246989/112764161-3abf9a80-8fff-11eb-81f3-b7f4db01c526.png)
OK that was weird. I found a bit of an issue with the Kunena menu setup, too long to relate here and too involved to reproduce, sometime after I fixed that I came back here and it was back to normal.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
