### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by SISAElly** [joomla/joomla-websites#1607]
Hi, our clear cache system doesn't seem to be working like it needs to be :(

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
