### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by leonvilla3** [joomla/joomla-websites#1608]
Please describe the problem or your issue

http://webnueva.zapatitoslindos-ortopedica.com/administrator

HTTP 502 Error

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
