### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by SISAElly** [joomla/joomla-websites#1610]
Hi, there seem to be problem with my cache as whenever I've updated contents on the site, the public interface does not have the updated content.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
