### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by mkhpd1** [joomla/joomla-websites#1613]
When a new Joomla Release is issues, email spam is constantly being sent to the administrators account until the upgrade is done.  This amounts to spam, and is probably illegal under the American Spam act and others.  It is also very annoying to administrators.
I ask that this feature be tempered so that rather than emails being sent out frequently at seemingly random times, that they occur no more than weekly, until the upgrade on that instance is completed.  I manage 3 different web accounts, and since 14 April I have had over 35 emails advising me of an update to Joomla!  That's way too much.  This feature alone macks me think I should move my clients to Wordpress!

**Comment by pe7er** [comment]
@mkhpd1 This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

Your question is regarding Joomla CMS itself. Joomla's update notifications are handled by the **Joomla! Update Notification System Plugin**. You can **configure** to whom it sends notifications and also the frequency. 
See: https://docs.joomla.org/J3.x:Plugin_Joomla_Update_Notification

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
