### ISSUE TITLE
Joomla 3.9.26 - intro images not showing in category blog pages [joomla.org] 

### ISSUE THREAD

**Issue by pfwdesign** [joomla/joomla-websites#1617]
I have a site that I upgraded to Joomla 3.9.26. When I did, a menu item that was a **category blog no longer showed the "intro images" I had set on the "Images and Links" tab** of each article. I haven't changed anything else that I can think of and I don't see any settings on the menu item, article general options, or the articles themselves that would keep the images from showing.

I also tested it by creating a NEW article, setting the "intro image" on "Images and Links", then creating a new menu item as a category blog to display that article. The article does not display the intro image. It DOES correctly display the "full article image" from the "Images and Links" tab after clicking "Read more".

See my test at https://ironrosesister.com/about-irsm/test 

I have been using Joomla for years and this page was working fine until I made the upgrade. I also have a Spanish version of this site that is still in Joomla 3.9.25 and it displays the intro images correctly.

Is anyone else experiencing this with Joomla 3.9.26? Or is there a setting I am overlooking?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
