### ISSUE TITLE
unwanted publicity

### ISSUE THREAD

**Issue by MartonMn** [joomla/joomla-websites#1618]
I have a website created years ago and yesterday I started to get advertising that I do not want to have, the advertising appears in the administrator of my website and on the website itself, I do not want to have any type of advertising on my website and it is annoying while I administer it.
Website: http://www.teacherschool.es/
![Captura](https://user-images.githubusercontent.com/82897189/115431670-d959a880-a205-11eb-893d-05d8d5aa71a9.PNG)

**Comment by hvdmeer** [comment]
Joomla doesn't serve ads in the administrator panel, check you browser plugins

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
