### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Lwineman** [joomla/joomla-websites#1619]
Please describe the problem or your issue: 

 I have this week updated all my current joomla sites to joomla 3.9.26 - many of my older sites are now getting bombarded with security exceptions - my admin tools application is doing a great job and blocking them but I havn't had this many issues for a long long time.  Is there something in the new 3.9.26 that has been missed? it's like I have lost a layer of security somewhere?  any advice would be appreciated.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
