### ISSUE TITLE
[joomla.org] issues with slideshow Module 

### ISSUE THREAD

**Issue by abdullahKJ** [joomla/joomla-websites#1620]
Dear All 
I hope you are well and rested 

I'm facing a problem with my site 
trying to insert a button into a slide that would redirect customers to another page(Landing Page)
the desktop version is working really well 

however the mobile version of the site has a problem once the slide shows up and we try to click on the button it's not doing anything 

on other slides it's working fine 
this is the first time it happens with me

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
