### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ccreston** [joomla/joomla-websites#1621]
Good morning,
We’re not able to log into our Joomla account using our ccreston login.  The original person who set this up for us moved years ago, and we don’t remember the email that was associated with establishing our account.  This is the first time this has happened and we just ran into this issue this week.  I can send a screenshot of what we see when trying to login. 

Appreciate your help!
Sean Adinig
Calvaryreston.org

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
