### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by osita12** [joomla/joomla-websites#1626]
I found uncategorized in my url, so i went to category in my joomla site and delete it, now all my website are loading 404.
Naturebenefitss.com

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
