### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by carollynnb** [joomla/joomla-websites#1636]
Hi,

I am having trouble logging into my website's administrator. When I log in to the administrator, it gives me a 404 page not found. I tested it on a few other computers and it's not doing it on all computers, only on a few. 

I have cleared the browser's cache and tried on different browsers as well, but it's still doing the same.

Here is the website's link: https://mossecuritysolarshop.co.za/

Any help will be highly appreciated, please. 

![image](https://user-images.githubusercontent.com/72488825/124483386-92ae3000-ddaa-11eb-8c49-bdcca4833b8c.png)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
