### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by kamrants** [joomla/joomla-websites#1640]
I'm unable to gain access to my website edditor as when i'm entering in my login credentials and press login, nothing happens. I also believe due to this, my website is now down. 

I look forward to your urgent response as i would like to get this sorted asap.

Regards,
Kamran Tariq-Syed

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
