### ISSUE TITLE
обновление.......

### ISSUE THREAD

**Issue by testogni19** [joomla/joomla-websites#1650]
Помогите решить проблему после обновления 
Версия Joomla! новая 4 сайт рухнул https://ogni19.ru  
Фатальная ошибка
 

Joomla-j4-fatal.png
Скорее всего, вы читаете это потому, что ваш сайт Joomla имел какую-то фатальную ошибку и выдал вам сообщение, подобное приведенному выше.

Есть две вероятные причины для этого:

Системный плагин вызывает сбои на вашем сайте
Было внесено изменение в ваш хост (например, обновление версии PHP, которое не совместимо с расширением или самой Joomla, если вы используете старую версию).
Как решить проблему
Если вы недавно внесли какие-либо изменения в свои системные плагины, отключите системные плагины один за другим в базе данных, пока не найдете, какой из них отвечает (помните, что вам не нужно отключать какие-либо основные системные плагины Joomla). как быть ???

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
