### ISSUE TITLE
проблема с обновлением до Joomla 4

### ISSUE THREAD

**Issue by testogni19** [joomla/joomla-websites#1653]
после обновления  Joomla 4 вышла вот такая ошибка  сайт  https://ogni19.ru???

**Comment by chmst** [comment]
This is the wrog place. Please post here: https://forum.joomla.org/viewforum.php?f=812&sid=7653a050cb5ec60e014b1b7a48fb4c25

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
