### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by mbolanosd** [joomla/joomla-websites#1663]
I have upgraded Joomla to 3.10.1.0 and unexpectedly in my backend administrator I have no longer access to Control Panel, although I do have access to other options under SIte menu. As an administrator, to sign in I now need to do so by using ?XXXXX after the index.php, like (/administrator/index.php?option=com_admintools), otherwise if I just try to access (/administrator/index.php) as administrator I only get a blank page.

The same happens when I sign in through another area, like components, but when trying to navigate to Site/Control Panel only a blank page is shown.

No messages of errors and therefore I cannot understand how to fix it. Tried reinstalling Joomla's core and also fix Database, but it still not working.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
