### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by kotlyar62** [joomla/joomla-websites#1666]
Class 'FOF40\Container\Container' not found

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

PS: when you post about your issue at Joomla Forum, please add more details about your Joomla version + setup (Use Forum Post Assistant https://forumpostassistant.github.io/docs/ for that ).
