### ISSUE TITLE
[joomla.org] Update notifications

### ISSUE THREAD

**Issue by Gizepi64** [joomla/joomla-websites#1668]
I know this has been approached before but do we poor admins have to get update notifications from our websites three times a day? 
It's fine if you only have a single website but when you have 20 and most on Joomla then it becomes unmanageable.  A single immediate notification and then a weekly notification from each affected site would be more than ample.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
