### ISSUE TITLE
[jtm] 

### ISSUE THREAD

**Issue by asusoglu** [joomla/joomla-websites#1672]
Hello, we need urgent help. Our website is redirected to the old mdq website. We need this to be corrected asap.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
