### ISSUE TITLE
[jhelp] administrator

### ISSUE THREAD

**Issue by MONTEREYEKATERINA** [joomla/joomla-websites#1673]
Hi,

When i enter to the Astro-monterey.ru/administrator page is blank.
Could you please help to login as administrator.

I have Astro-monterey.com and .com is OK, i could login to that.
HTTP ERROR 500
Kind regards, Ekaterina

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
