### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by uzzi87** [joomla/joomla-websites#1690]
Hello I need help somebody har taken over our super admin user for our netsite www.apppledoctor.no can you help us with that, we can not do anything our have any access for the control panel 

thank you 

regards 
Usman 
![Skjermbilde 2021-11-22 kl  13 50 03](https://user-images.githubusercontent.com/94542336/142864760-a04b2652-4a25-494f-b00a-96e58262e395.png)
K

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
