### ISSUE TITLE
[joomla.org] ERROR MESSAGE ON JOOMLA SITE

### ISSUE THREAD

**Issue by Kofi111** [joomla/joomla-websites#1691]
All of a sudden my joomla site is showing this error message, both at the backend and frontend **_"An error has occurred.
0 Class 'JRequest' not found"_**. Please assist me rectify the issue.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
