### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by SergiuCH** [joomla/joomla-websites#1692]
Hello, it seems that I HAVE PROBLEMS WITH CONNECTING TO MY JOOMLA ACCOUNT.

**Comment by conconnl** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://community.joomla.org/service-providers-directory.html

For this reason, I'm closing your issue here.

Thanks!
