### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by msbTemplar** [joomla/joomla-websites#1694]
Please describe the problem or your issue

Buenos dias estoy intentado instalar joomla atraves de cdmon pero no puedo ya he probado 11 versiones de joomla y se queda en el paso despues de introducir los datos de la abase de datos en cdmon

porfavor ayudarme que tengo un examen que terminar 

un saludoo

mohammed

mi email es:   sebti.benzakour.mohammed@iescamas.es

**Comment by pe7er** [comment]
Hola,

¡Este repositorio es SOLO para reportar problemas con los sitios web *.joomla.org, no sobre el CMS Joomla!

Para problemas de soporte al usuario, por favor vaya a:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-o busque un proveedor de servicios en https://resources.joomla.org/

Por esta razón, cierro tu tema aquí.

Gracias.

---

Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
