### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by damilola1234** [joomla/joomla-websites#1696]
![Screenshot 2021-12-06 at 15 32 58](https://user-images.githubusercontent.com/51806837/144864436-c74e5b49-0ccb-40fd-8b28-3ecd6eed37d9.png)
hello, how can I go about this? this was the response I got trying to access my dashboard; Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
