### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by Tasha0412** [joomla/joomla-websites#1697]
I have downloaded Joomla 4.0 and have the zip file on my laptop. However, I'm struggling to figure out what the next steps are to enable the software using the contents of the zip file. Could you please provide instructions or clear guidance on what to do next?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
