### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Shorebase21** [joomla/joomla-websites#1698]
Our website manager who set up our website www.cowalfiddleworkshop.co.uk is no longer with us. I have made minor changes as an administrator and I see now that the site has been hacked and is totally corrupted. I cannot access either the site itself or the admin section. Can you help please?
elizabethgower@btinternet.com

**Comment by conconnl** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
