### ISSUE TITLE
[jed] broken pagination

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1701]
> There seems to be something wrong with the behavior of pagination on the #Joomla official site.
> Go to Browse Extensions > Compatible with J4 and use pagination. For example, can you move from page 3 to page 7?
https://twitter.com/HidetoOshima/status/1478653660028895233

And I also see a broken pagination

**Comment by Llewellynvdm** [comment]
Those how setup the JED and actually understand what they did are no longer in the project, or to be found in the PHP world... so we are literally scooping out water while it still has massive leaks....

I am not sure why the filter system is so overly complex and why the pagination just is not truthful reflecting that actual available pages. As much as I want this fixed, it seems best to push my attention toward building JED4 instead.

I will investigate this some more and see what I can discover... @anibalsanchez or @JazParkyn do you have any idea what is happening here?

**Comment by anibalsanchez** [comment]
JED3 has its pagination logic based on Fabrik's library. 

The "Compatible with J4" is a special case of the original search navigation: https://extensions.joomla.org/extension/?searchall=&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=40&filter%5Btype%5D=&filter%5Bhasdemo%5D=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&dir=DESC&limitstart=&controller=filter&view=extension&layout=list&Itemid=145&clearorders=0&clearfilters=1

Since it doesn't work well based on com_jed, I would replace it with an Algolia's search URL:

https://extensions.joomla.org/instant-search/?jed_live%5BrefinementList%5D%5Bversions%5D%5B0%5D=40

**Comment by Llewellynvdm** [comment]
Thanks @anibalsanchez seems like a good work around... I will do that for now.

**Comment by Llewellynvdm** [comment]
Thanks again, its done!
