### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by chiroatadura** [joomla/joomla-websites#1702]
Dear Joomla,

For many years we work with Joomla to make our website. But since a month our website 'www.chirokanegem.be' is offline. We are not able to access our website for visitors, nor the control panel. Our web domain is still up to date, so that's not the issue. Because many people visit our website, this is a big problem. Can you detect the problem is as soon as possible?

Hoping on a quick repair.

Kind regards,
Eva Mortier
Chiro Kanegem

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
