### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by nfbauti** [joomla/joomla-websites#1703]
Where are my new items?

Cordial greeting.

On January 7 update joomla 3.10.4 to 4.0.5 the process was carried out normally and at the moment it works well and that same day (January 7) I did not make any article.

However, the new articles do not appear listed in the backend but in the frontend they do appear, that is, I can create and save them but they do not appear listed with the other articles, only those created until January 6 appear (screenshot attached).

Did anyone have that problem? Is there a solution?

However, if I enter the database and check the content table if the articles created on January 8 appear (attached screenshot)

https://portalnews.co

Thank you all very much for your help.
![listado backend](https://user-images.githubusercontent.com/33980599/148680669-fed01b44-e88b-4d01-abfc-b84e6e22552a.jpg)
![tabla content](https://user-images.githubusercontent.com/33980599/148680673-ff4285ec-3968-4a4f-9644-257f3051ae94.jpg)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
