### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by kirill2000-fox** [joomla/joomla-websites#1704]
Hello, please help me solve the problem with downloading joomla. In the installation wizard, in the database settings section, I enter my root user and his password, but I get the following message.Could not connect to database: Could not connect to database: Access denied for user 'root'@'localhost' (using password: NO). I do not know what to do with it and how to download the application thereby.

**Comment by kirill2000-fox** [comment]
I am installing joomla on hostinger

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
