### ISSUE TITLE
[forum.joomla.org] import articles and content (without migrate)

### ISSUE THREAD

**Issue by SEchavarria-BETA** [joomla/joomla-websites#1708]
Please describe the problem oHi all.
I am trying to migrate a site from joomla 3.10.5 to joomla 4, which has a lot of content and uses various third-party extensions, but attempts have failed.
I am trying another option which is to install joomla 4 as a new site, and I want to try to pass the content that I already have in the previous site (articles, categories and others). I found on the internet that I could import only the #_content table, and I did it directly in the database, but when doing it, from the joomla administrator I do not have access to be able to edit it or see them to link them, so it did not help me. I want to know if anyone knows what other tables I can import directly to make this possible, or if there is some other way to pass all site content.
I appreciate any information.
Thank you.r your issue

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
