### ISSUE TITLE
Cannot Login. Doesn't recognize password 

### ISSUE THREAD

**Issue by JPratt314** [joomla/joomla-websites#1710]
I cannot log into my account. My password is not recognized and I do not see a place where I can recover it. My email is JPratt314@yahoo.com. My website name is JenJeanschihuahuas.com. Please advise.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
