### ISSUE TITLE
joomla site log-in

### ISSUE THREAD

**Issue by biokinetics** [joomla/joomla-websites#1716]
i'm the website manager for Biokinetics.com and tried to log in https://biokinetics.com/administrator/?headForm and my user name/password is not working and my email is "not in the list" according to Joomla
how do i get access to my site via Joomla

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
