### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by dawnjgill** [joomla/joomla-websites#1717]
My website is no longer visible and hasn't been for the last few days, this has happened before and you're always able to fix it.    This screen  A screen pops up that reads:
You may not be able to visit this page because of:

an out-of-date bookmark/favourite
a search engine that has an out-of-date listing for this site
a mistyped address
you have no access to this page
The requested resource was not found.
An error has occurred while processing your request.
Please try one of the following pages:

[Home Page](http://godsbehalf.com/index.php)
If difficulties persist, please contact the System Administrator of this site and report the error below.

Using $this when not in object context

**Comment by dawnjgill** [comment]
It's not my System Administrator.  You guys fix it.  It typically happens when you update my site

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
