### ISSUE TITLE
[joomla.org] - Enquires 

### ISSUE THREAD

**Issue by jainamitr1** [joomla/joomla-websites#1718]
1. How to subscribe for Joomal support?
2. Does Joomla support includes the  Security patches? 
3. Whom to get the Joomal paid support?

**Comment by pe7er** [comment]
Hi,

> How to subscribe for Joomal support?
> Does Joomla support includes the Security patches?
> Whom to get the Joomal paid support?

The support given by the Joomla Community at https://forum.joomla.org/ is free.
If you are looking for a service provider to give you commercial Joomla support, find one at https://resources.joomla.org/

Actually, this repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
