### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by bennytark** [joomla/joomla-websites#1722]
hello-
I am trying to log into my account and after everything is entered... screen goes blank white.
Is there something that happened or I need to get into account.  Need to update blogs and it's been awhile due to this issue.
Any thoughts would be greatly appreciated!!

Thanks,
Ben

**Comment by pe7er** [comment]
Hi,
Do you mean that you cannot log into your Joomla CMS website?

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
