### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by HAntelo** [joomla/joomla-websites#1730]
Hello!

I just migrated my website to Joomla 4. My URL is **www.medicoespecialista.com.bo**

When a user visits my website, a Joomla icon or a box with information about the site appears at the bottom.

How can that icon or box be removed so that it is not visible to any visitor to the website.

Thanks.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
