### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by AEnyChris** [joomla/joomla-websites#1736]
Hi
I keep getting this index of/ page anytime I try accessing my website. How do I fix this, please?

**Comment by pe7er** [comment]
Hi,

Your question is about a Joomla web site that you maintain yourself.
This repository is ONLY for reporting issues with the *.joomla.org websites that are maintained by the Joomla project.
It's not meant for questions about the Joomla! CMS itself.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
