### ISSUE TITLE
Upgraded Joomla to 4, and my website disappeared.

### ISSUE THREAD

**Issue by GabRR1** [joomla/joomla-websites#1738]
Hi, I upgraded Joomla to 4.1.0, and my website disappeared. This is what appears in everything on the Control Panel: Call to undefined method Joomla/Database/Mysqli/MysqliDriver::query(), so I can`t edit anything. Help. 

![image](https://user-images.githubusercontent.com/101225792/157342633-183fc21f-6801-4170-b2d1-b79e540c00cb.png)

**Comment by pe7er** [comment]
Hi,

Your question is about a Joomla web site that you maintain yourself.
This repository is ONLY for reporting issues with the *.joomla.org websites that are maintained by the Joomla project.
It's not meant for questions about the Joomla! CMS itself.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
