### ISSUE TITLE
[joomla.org] How to achieve zero downtime 

### ISSUE THREAD

**Issue by speedkevin** [joomla/joomla-websites#1784]
Hi Joomla,

I have two VMs (say, VM-A and VM-B with Joomla installed) and one database (Cloud SQL) on GCP.

I encounter a problem that when I want to deploy new Joomla page (this page have new written code or have a new database schema in it), as far as I known Joomla will write a database configuration on DB table, and it turned out that VM-B have issues writing data to database because the schema is different from the data definition in VM-A

Thus, I need to create a new database, and then redirect VM-A which I am going to deploy new application to new database. But it is cumbersome. Is there any way to have a continuous deployment to the architecture to achieve zero downtime? (2 VMs and one database)

Thank you.

Cheers,
Kevin

**Comment by pe7er** [comment]
Hi,

Your question is about a Joomla web site that you maintain yourself.
This repository is ONLY for reporting issues with the *.joomla.org websites that are maintained by the Joomla project.
It's not meant for questions about the Joomla! CMS itself.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
