### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by denverfigadvertising** [joomla/joomla-websites#1786]
I created a hosting account and have tried installing Joomla3 to it. When I put in the database information, an error comes up saying it can't find the database. I have tried several times to create a new database and user to try to solve the issue. I have also deleted old databases and users and still the same result. Can you help?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
