### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by sabrinasousa0** [joomla/joomla-websites#1804]
the pages of the blog are not responding when i enter by the top bar, i used infinityfree as the hosting, do you think this is a problem there or on joomla?
![Sem título](https://user-images.githubusercontent.com/105297017/189668953-44a7dfca-ab00-49a5-aa6e-5a2f474e9a54.png)

![lll](https://user-images.githubusercontent.com/105297017/189669166-15da0f61-f033-4ddc-9e20-bafbd4332eb4.png)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:
- https://forum.joomla.org/
- https://docs.joomla.org/Main_Page
- or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
