### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by tactico-ms** [joomla/joomla-websites#1809]
I think there is a problem with 4.2.3…
After updating from 4.2.2 to 4.2.3 I found out that there are issues with routing.

Links to pages where not working properly and displaying other aliases (URL’s).
This happened with SP Page Builder and a search module (Article Good Search).

Page Builder:
Used integration and using SPPB as article editor. On the page, I added an addon called Articles (display articles by category & tag).
in the front-end, links didn't work.

Article Good Search:
In search results, when clicking a result, the URL was not of the category and item (category has a menu item). This caused duplicate URL and also the display was messed-up.  

Once I restored to 4.2.2 everything was running okay

I have a copy of of both versions websites ans will be happy to provide links if needed.

**Comment by pe7er** [comment]
Hi,

Thanks for reporting a possible bug. 
However, this repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If you found a bug in Joomla CMS, please report it at https://github.com/joomla/joomla-cms/issues instead.
Please try to reproduce your issue with a clean Joomla 4.2.3 if possible

However, as it seems 3rd party extension related, please contact the developer of the extension.

For user support issues with Joomla CMS, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
