### ISSUE TITLE
[joomla.org] Mail issue

### ISSUE THREAD

**Issue by michaelmahrous** [joomla/joomla-websites#1813]
I am working on joomla 3.10.11 , and was used SMTP for office 365 configuration, after office change to modern authentication, I couldn't send any email! is there any solution for this case?!

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
