### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by AEGAdmin** [joomla/joomla-websites#1814]
I reset the password to my Joomla account and it is not recognizing it.  PLEASE HELP!  Please contact me via lsmith@atlasgeonw.com or at 206-334-8391.

Lannie

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
