### ISSUE TITLE
Joomla Indonesian Language

### ISSUE THREAD

**Issue by kuendhi** [joomla/joomla-websites#1815]
hello
Why doesn't Indonesian appear in the Joomla language installation? How to
![Screenshot_19](https://user-images.githubusercontent.com/79362298/194115930-88a94517-23e4-43c0-986b-81142d8120aa.png)
 install the language that doesn't appear?

**Comment by alikon** [comment]
you can download from here https://downloads.joomla.org/language-packs/translations-joomla4

**Comment by zero-24** [comment]
As of today no J4 releases of the indonesian language pack have been uploaded to downloads.joomla.org yet therefor no language pack can be downloaded or installed via the backend: https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-indonesian

When you are the Indonesian TT or know someone from there please reach out to the TT Coodrinator / Stefan so that issue can be solved cc @tecpromotion Will close here as for now this is intended behavior as no package has been uploaded.

**Comment by HLeithner** [comment]
@kuendhi as already said by tobias there is no indonesian language pack for j4, but we would love to see one.
We use [Crowdin](https://joomla.crowdin.com/cms/id#files) to translate joomla, the indonesian language pack is translated to 50% so much work is already done. please help us to translate Joomla to Indonesian. if you need help please contact [Stefan Wendhausen](https://volunteers.joomla.org/joomlers/1163-stefan-wendhausen)
