### ISSUE TITLE
[jhelp] Moving media files across folders

### ISSUE THREAD

**Issue by SamuelSHernandez** [joomla/joomla-websites#1818]
Please describe the problem or your issue:

Hi, is there a feature, work around, or external tool you could refer me to for moving media files across folders? From my research, the only way is through FTP Connection, but I can't use that on my website. Thank you!

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
