### ISSUE TITLE
Edit this content to show it on your website text appears next to my photos on my website[jhelp] 

### ISSUE THREAD

**Issue by patriksz** [joomla/joomla-websites#1821]
Edit this content to show it on your website text appears next to my photos on my website

http://patriksz.com/portfolio

I tried to remove it, but could not figure it out how. Please advise me where can I find the option to remove it?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
