### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-websites#1823]

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!
