### ISSUE TITLE
locked out of my Joomla site 

### ISSUE THREAD

**Issue by hendrik529** [joomla/joomla-websites#1826]
I can not deactivate my two-factor authentication as I had to change my phone,
My new phone will not receive the two-factor authentication.
Can anyone advice me.

Thank you

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:
- https://forum.joomla.org/
- https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!

**Comment by chmst** [comment]
Please post this in forum.joomla.org, this is not the right place. https://forum.joomla.org/viewtopic.php?t=971316 maybe this helps.
