### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by nikolausober** [joomla/joomla-websites#1835]
Please describe the problem or your issue
Since I used sigplus-Extension to create a image-gallery and activated sigplus-content-plugin I got an "System Error",
I don't have access to any Joomla components anymore only to system information.
Website: web.tnms3-linz.at

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
