### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Nunemm** [joomla/joomla-websites#1860]
I login into my joomla administrator account for my website and I can't see anything, blank page appears.

How can I solve this?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
- https://forum.joomla.org/
- https://docs.joomla.org/Main_Page
- or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
