### ISSUE TITLE
[jhelp] SEF url not working in Joomla version 4.2.7

### ISSUE THREAD

**Issue by Zubiear55** [joomla/joomla-websites#1863]
I can't remove the id article/categories from my urls.

I've set routing to on in article setting and checked everything in global configuration (.htaccess also renamed) but it's not working, I still see the id in the urls. https://residency.com.bd/?view=article&id=4:about-us&catid=8 
Attach images is my setting.
![s1](https://user-images.githubusercontent.com/124078972/215836174-edc938f3-12e2-4624-800f-d78278f61b76.PNG)
![s2](https://user-images.githubusercontent.com/124078972/215836285-61a1c1e2-d8ae-4c19-93c6-1a74116f3157.PNG)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
