### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by interfacedesign** [joomla/joomla-websites#1864]
Issue logging in to Joomla 4 website administrative area

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
