### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by eribo559** [joomla/joomla-websites#1867]
I tried updating to the latest version of joomla manually, then my administrator  panel stopped working and I encountered this bunch of bug la on my Website (aifl-institute.com)

Warning: Undefined property: Joomla\CMS\Version::$RELEASE in /customers/4/f/b/aifl-institute.com/httpd.www/plugins/system/fabrik/fabrik.php on line 54 Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /customers/4/f/b/aifl-institute.com/httpd.www/plugins/system/fabrik/fabrik.php on line 54 Warning: Undefined property: Joomla\CMS\Version::$RELEASE in /customers/4/f/b/aifl-institute.com/httpd.www/plugins/system/fabrik/fabrik.php on line 70 Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in /customers/4/f/b/aifl-institute.com/httpd.www/plugins/system/fabrik/fabrik.php on line 70 Warning: Undefined property: Joomla\CMS\Version::$RELEASE in /customers/4/f/b/aifl-

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
