### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by Rakeshchaudharyit** [joomla/joomla-websites#1869]
i already updated website up to 4.2.5  of Joomla but when i am trying to upgrade to Joomla 4.2.8 then i am facing this problem

Joomla Update encountered a server error when applying the update to your site.

Your site may not have been upgraded completely to the new Joomla version.

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
