### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Carly40** [joomla/joomla-websites#1870]
Hello team

I wondered if you could help.  have recently updated my website from 3.10.11 to Joomla 4.

My website is this - https://www.electricsoulshow.com

However, I am having a few problems.

I am getting loads of these 404 pages not found replies due to these URL;s = please see below: In regards to people's trying to access  a page or pages on the = https://www.electricsoulshow.com

PLEASE SEE BELOW

 https://electricsoulshow.com/aguqumenu-1160257.html

https://electricsoulshow.com/fylmh/g1040842.html
https://electricsoulshow.com/gwldu/e2028216.html
https://electricsoulshow.com/gzfud/f1801822.html
https://electricsoulshow.com/ylamcmenu-1082131.html
https://electricsoulshow.com/xnanr/e632597.html
https://electricsoulshow.com/rhnptmenu-2160439587230114421412948931379886.html
https://electricsoulshow.com/lfojj/u1889769.html

Most of them are coming from the country that is = JAPAN

Can anyone help me here?

Thanks

Carl Brown

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
