### ISSUE TITLE
Joomla 4.2.8

### ISSUE THREAD

**Issue by ipsehans** [joomla/joomla-websites#1871]
Hello
when using an iframe menu item, then the http// is always inserted into the web adress. 
thank you for correction.
Best regards 
Hans Waelti

**Comment by pe7er** [comment]
Hi Hans,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
- https://forum.joomla.org/
- https://docs.joomla.org/Main_Page
- or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
