### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Huzaifa8524** [joomla/joomla-websites#1875]
Security Vulnerability!

Hi Team,
I am an Independent Security Researcher running a vulnerability identification service , and I accidentally found some vulnerabilities in your infrastructure.

And it can cause damage to your website. I want to share the vulnerability details with you (includes POC, screenshots, and suggested solutions).
So tell me may I report here ? Is there any appreciation reward for a valid report/bug ?
Kindly respond as soon as possible :)

 Regards.
Huzaifa Shahid

**Comment by HLeithner** [comment]
Hello @Huzaifa8524 

you can report security issues for Joomla! and the Joomla! properties to the Joomla Security Strike Team.
You can use the contact form on the [website](https://developer.joomla.org/security/contact-the-team.html) or per email, if you use email please encrypt your message with our gpg key you can find it at https://developer.joomla.org/security.html the email address is also located at this page.

Thanks for you responsible disclosure.

I'm closing this issue because this is not the right please to report security issue.

kind regards,

Harald
