### ISSUE TITLE
Site times out when adding users to course

### ISSUE THREAD

**Issue by lmcintoshgw** [joomla/joomla-websites#1879]
When adding user to a course, the site times out.  Other functions on the page are fine but this times out.  Please advise how to proceed. 
<img width="787" alt="Joomla_add user to course" src="https://user-images.githubusercontent.com/117777244/228280864-a19408f0-6d5e-4b7f-970b-aaade41cbcca.png">

Do you know why this times out?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
