### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by fishtime** [joomla/joomla-websites#188]
On page https://docs.joomla.org/API15:JApplication
is 
<a class="external text" href="http://api.joomla.org/Joomla-Framework/Application/JApplication.html" target="_blank" rel="nofollow">api.joomla.org</a>
but link going to page with "404 Not Found " content

**Comment by MATsxm** [comment]
Hello,
As a wiki, the content of the JDoc site can be edited, amended, updated, completed directly by logged users.
As this page is a bit specific, I will do it but feel free to edit the JDoc content if needed.
thanks.

**Comment by mbabker** [comment]
In general those links for the 1.5 API pages should be prefixed with `https://api.joomla.org/1.5` (i.e. https://api.joomla.org/1.5/Joomla-Framework/Application/JApplication.html) but since some of the template media is now gone and other parts of it broken on HTTPS, I'd be inclined to suggest at this point to just drop those links.
