### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by moaid500** [joomla/joomla-websites#1886]
I tried to install the script at this path
[قصة عشق](https://x.esheeq.watch/)

But it always shows fetal error

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
