### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by mdav** [joomla/joomla-websites#1892]
Our website is down showing the error message: 
mktime(): Argument #1 ($hour) must be of type int, string given

The website link is here
https://www.seced.org.uk/

Can someone please advice ? Many thanks

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
