### ISSUE TITLE
[joomla.org] Component Development - error with FormController Save method

### ISSUE THREAD

**Issue by christomagnifico** [joomla/joomla-websites#1894]
Custom component development- Frontend add/edit save error. Form displays, Controller saves data, upon displaying form a second time, row 1 of my db table is updated, despite starting with a blank form. Always row 1. Version 4.2.9.

Setting $loadData = false in Model does not solve problem.

I found this in FormController.save:

$recordId = $this->input->getInt($urlVar);

which returns 1. Then:

$data[$key] = $recordId;

sets the id = 1, which is incorrect... row 1 will always be edited (first insert will work as it is row 1).

Workaround: Because I want only an add, this works:

Override save method, then, $recordId = "0"; // or set value here, get id value from app->input for edits
alternatively:
$data[$key] = $app->input->get('id'); // and check for 0 in my situation

Issue seems to be site only; admin side seems to work, perhaps the way record id are passed from the list view adminForm, or perhaps using a different controller on admin side for save. Unsure.

Discussion appreciated...
-Christo

**Comment by christomagnifico** [comment]
I am moving this to joomla / joomla-cms

**Comment by pe7er** [comment]
Hi,
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
