### ISSUE TITLE
[joomla.org] Changing the website name

### ISSUE THREAD

**Issue by HalynaKalambet** [joomla/joomla-websites#1899]
Hello. I created a website on Joomla. I tried to change its name to the "name.surname" format but in the address bar it still names "localhost/joomla". I tried different ways but still the same((

And this is a link for a video when I'm changing name but it still shown incorrect 
  https://www.dropbox.com/scl/fi/vbumgxfi1902fmw3m3a7v/Home-Dashboard-halyna.kalambet-Administration-Google-Chrome-2023-05-31-19-36-43.mp4?dl=0&rlkey=v51odjpls5c5vwyhirca6tmr9

**Comment by pe7er** [comment]
Hi,
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
