### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by scaffaleweb** [joomla/joomla-websites#1901]
con Joombla 4.3.2
quando provo a duplicare un articolo, mi compare questo errore: "Salvataggio fallito con il seguente errore: Parent ID non valido."
Ho provato a rigenerare sia i menu che le categorie, ho pulito la  cache

**Comment by scaffaleweb** [comment]
with Joombla 4.3.2
when I try to duplicate an article, I get this error: "Save failed with the following error: Invalid Parent ID."
I've tried regenerating both menus and categories, I've cleared the cache

**Comment by pe7er** [comment]
Hi,
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
