### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by TerryF152** [joomla/joomla-websites#1905]
I am trying to alter the template on our website on Joomla 3. I go to extensions / templates / styles and then click on the template name. A new screen opens, with a progress circle, but the template page no longer opens. The last time I did this, maybe a month ago, it was fine, but now no longer opens, no matter how long I wait. everything else on the website seems fine.

Thanks in advance,

Terry

**Comment by max123kl** [comment]
Hi,
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
