### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by muiezrazak** [joomla/joomla-websites#1906]
hi, my website cant be use. its only preview this code.

Error: Class 'NRFramework\Functions' not found: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

**Comment by max123kl** [comment]
Hi,
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
