### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by shanai** [joomla/joomla-websites#1908]
I am using Joomla  ‎4.3.2
When i want to run Index for Smart Search, I got an error appear:

An Error Has Occurred
Attempt to assign property "text" on array

![Screenshot 2023-07-04 113539](https://github.com/joomla/joomla-websites/assets/3292113/7c905ecf-d509-44c7-80fa-dca7496e90f5)

only a small number of pages were indexed.

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
