### ISSUE TITLE
Why is extensions.joomla.org full of advertisement, including annoying pop-ups.

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-websites#1909]
So I travelled today to extensions.joomla.org, and I haven't been there in a while, but to my amazement it is now full of advertisement. Is Joomla doing so badly that this is needed?

- Like, 10 - 20% of the bottom of the page is taken up by a full width advertisement.
- In the middle of the page is a pop-up that takes up another 10% of the screen.
- On the homepage there is this huge advertisement for Scala hosting which is probably a sponsor, but it is not mentioned anywhere, and it is seriously unfair for other hosting providers.
- Just above the footer, there is another advertisement spot.
- In the search results, there are also advertisements on the homepage.

Look, I don't mind the advertisement I always try to minimize my time just browsing the store anyhow, but I do mind if the future of Joomla is being in jeopardy due to cashflow issues. We are one of the view web development companies that refuse to work with other CMS systems other than Joomla, and we have been stubborn for 14+ years and counting, but seeing this (for me) sudden increased advertisement makes me think something financially is going wrong.

PS: Not saying how to run the business of Joomla, but I am just wondering.

**Comment by crystalenka** [comment]
Hi! Thank you for taking the time to write. 

Joomla is run by Open Source Matters, which is a nonprofit organization that does not have any for-profit activities. The majority of our funds currently come from sponsorships and, unfortunately, ads. I don't like them either, but currently they are necessary.

That being said, I would love to reduce or eliminate our dependency on ads in the future. In order to make this possible, we are putting together a sustainability working group to address financial strategies and brainstorm additional income streams that are a better fit for our community (along with other project sustainability topics). 

Would you like to join the working group and participate in the conversation? :)

**Comment by HLeithner** [comment]
We removed the popup and fly in ads, I'm closing this issue for now.
