### ISSUE TITLE
[jlaunch] Recommendation for unsupported PHP Version

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1916]
Why is 8.1 not recommended and outdatet 7.3, 7.4 and 8.0 is?

<img width="381" alt="grafik" src="https://github.com/joomla/joomla-websites/assets/828371/bdb06ba3-1fb5-44fa-a534-47bf70fce281">

**Comment by HLeithner** [comment]
@Pawel-Panek can you have a look here please?

**Comment by Pawel-Panek** [comment]
I think we made a loop here. Derek from CloudAccess team started this discussion about recommendation for PHP 8.1 but I think it just made it back to CA. Maybe I'm wrong...

The information in this dropdown is based on what can be see here: https://downloads.joomla.org/technical-requirements . We even have an automated process that checks on recommended and minimum versions so the PHP version list in our control panel will get updates in case something changes on the technical-requirements.

Since PHP 8.0 is recommended for Joomla 4! so it is in our control panel.

**Comment by HLeithner** [comment]
I increased the version on downloads.joomla.org we will see if it works ;-) thanks

**Comment by dereksca** [comment]
Hey, it looks like PHP 8.0 is still recommended for Joomla 3 at https://downloads.joomla.org/technical-requirements

**Comment by HLeithner** [comment]
Joomla 3 is no longer supported by the Joomla community and the recommendation will not be change for it anymore. Only security updates are available by an official partner.

**Comment by dereksca** [comment]
But didn't you change it to 8.1 last week? Why was it changed back?
