### ISSUE TITLE
 how to activate my gridbox in joomla[jhelp] 

### ISSUE THREAD

**Issue by Mamiluu** [joomla/joomla-websites#1918]
Please describe the problem or your issue

**Comment by wilsonge** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
