### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by biochama1** [joomla/joomla-websites#1924]
Hi,my website biochama.com doesn't work because it asks to update the version and I can't, thank you for your help describe the problem or your issue, thanks

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!

**Comment by biochama1** [comment]
who can help me

**Comment by pe7er** [comment]
Have you tried Joomla Forum?
https://forum.joomla.org/

**Comment by biochama1** [comment]
yes, I contacted hostmonster, and they told me that the problem had to be solved by Joomla by updating the version, because I am paying for a site that does not work

**Comment by pe7er** [comment]
Again, this repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

Please use https://forum.joomla.org/ for Joomla community support for your own website.

**Comment by Hackwar** [comment]
Your website is using this software, but we are not responsible for your website. You have to either contact the person who created the website for you or hire someone to fix your site for you. Looking at your site, you have more than one issue, among other things that you are using a page with Flash before you actually reach the Joomla website. Flash has been disabled in all browsers for 3 years now.
