### ISSUE TITLE
[jdocs] 404 On "Developing an MVC Component/Our First Backend Page" Page

### ISSUE THREAD

**Issue by eko3alpha** [joomla/joomla-websites#1925]
Please describe the problem or your issue:

I attempted to follow the MVC Components tutorial, and my progress was smooth until I reached the following page:

Tutorial Page: [Setting up the Database](https://docs.joomla.org/J4.x:Developing_an_MVC_Component/Setting_up_the_Database)

However, when I attempted to navigate to the next step by clicking on the blue "[Next: Our First Back-end Page]" button located at the bottom right of the page, it took me to a URL that should represent the next part of the tutorial, but instead, I encountered a 404 error.

URL with Error: [Our First Back-end Page](https://docs.joomla.org/J4.x:Developing_an_MVC_Component/Our_First_Backend_Page)

It seems there might be an issue with the link or the content structure of the tutorial.

**Comment by max123kl** [comment]
@eko3alpha 
Hi Angel,
After looking at the source of the "Setting up the Database" page and the link to the follow-up page, I cannot find any error in the link syntax.
My guess is that the author simply hasn't finished that page yet and that's why it's missing. The 9th page "Our First Backend Page" is also missing from the table of contents, which supports my guess.

You can take a look at the same series for [Joomla 3](https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Using_the_database) and see if it gives you a solution to your questions.
There are also several YouTube channels (including [Robbie's](https://www.youtube.com/@robbiejackson7919/videos)).
Don't forget to check out our [Joomla Forum](https://forum.joomla.org/index.php) where you are sure to get some help.

**Comment by eko3alpha** [comment]
I went back to the tutorial, and I'm still getting the 404.  Could it be that you have to be logged in to see that page?  This is what I'm seeing...

https://docs.joomla.org/J4.x:Developing_an_MVC_Component/Our_First_Backend_Page

![SCR-20231108-mhgy-3](https://github.com/joomla/joomla-websites/assets/1705908/6377391f-9b2a-4a7b-9fda-04953c7d4fb5)

**Comment by ceford** [comment]
What you are seeing is not a 404 page. MediaWiki does not return 404 pages. Any link to a non-existent page gives you a page with three options, including the option to create the page. Whoever was working on revising this tutorial for Joomla 4 has not yet created this particular page.

To be honest, it looks like this tutorial has been abandoned but you will find it here: https://blog.astrid-guenther.de/
