### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Catcher-Ry** [joomla/joomla-websites#1926]
Hi, We have been trying to fix this but we cant.

![Screenshot 2023-10-02 161504](https://github.com/joomla/joomla-websites/assets/146690786/8af40ac9-aa11-4275-9254-2b427fd3f9a4)

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
