### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by C15P** [joomla/joomla-websites#1932]
Problemas de acceso en usuario y contraseña, no logro acceder. Ayuda porfavor

**Comment by pe7er** [comment]
¡Este repositorio es SOLO para informar de problemas con los sitios web oficiales *.joomla.org, no sobre el CMS Joomla!

Para problemas de soporte al usuario con su sitio web Joomla CMS, por favor vaya a:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
o encontrar un proveedor de servicios en https://resources.joomla.org/
Por esta razón, cierro tu tema aquí.
Gracias.

-----

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.
Thanks!
