### ISSUE TITLE
How to properly optimize images on your phone in Joomla 5?

### ISSUE THREAD

**Issue by fun88chinhthuc** [joomla/joomla-websites#1948]
Hi all,
I insert image in article of joomla with attribute size of tag is width=720px height=405px. And size of image also width=720px height=405px.
I don't know how to optimize it on mobile?
If I use css to change, the size of the image remains unchanged.
If you use the srcset attribute of the img tag, the image size is reduced, but those are two different image files.
Which way should I choose? Please help me. 
My URL website is: [fun88chinhthuc.com](https://fun88chinhthuc.com/)
Thank you.

**Comment by max123kl** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

If it's a bug in Joomla CMS, please create an issue at https://github.com/joomla/joomla-cms

For user support issues with your Joomla CMS website, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
