### ISSUE TITLE
DOMAIN. [joomla.org] 

### ISSUE THREAD

**Issue by Truestoryads** [joomla/joomla-websites#1953]
I popped in a domain named: galaletsangguesthouse but I can't seen to access it now.

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your own Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
