### ISSUE TITLE
Update unavailable

### ISSUE THREAD

**Issue by Laudex123** [joomla/joomla-websites#1955]
Hello, I try to update Joomla but this message appear and i can't do nothing more.
What I have to do please ?
![Capture d'écran 2024-01-16 12545566](https://github.com/joomla/joomla-websites/assets/156781405/3bbf666d-2ba9-46ff-b5f9-2c3d2a50f429)

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
