### ISSUE TITLE
Access not set

### ISSUE THREAD

**Issue by YadakGostar** [joomla/joomla-websites#1963]
Please describe the problem oThere are two things to consider in Joomla 5.
1- It is a module editing setting that when I put it on the manager, it is still accessible in the front of the manager.
2- Apparently the permissions don't work in Joomla 5 because when I disable module access for the administrator, the permissions are not applied.r your issue

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
