### ISSUE TITLE
article page empty but content still present[jhelp] 

### ISSUE THREAD

**Issue by exluxtenebris** [joomla/joomla-websites#1966]
I cannot update a form on my membership page, because the article page in article manager shows zero content, 0 word count, and yet in the front of website the content is still there. There are some minor errors however, e.g. £ sign not displaying, just a diamond with ? in it instead of the £sign, and this also occurs with the copyright symbol at bottom of home page and in other punctauation areas through the website too. Can someone help me please, I don't understand what is going wrong?

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
