### ISSUE TITLE
Joomla Install Extension

### ISSUE THREAD

**Issue by AdminOG** [joomla/joomla-websites#1970]
Hi,

I wanted to upload the new website package thru the install extension. However, there is an error as below:

![image](https://github.com/joomla/joomla-websites/assets/139205138/9eb1729f-54cf-46cc-9cb3-b4bf67e86ac5)

I don't know what is happening. May you resolve this ? 

Thanks

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
