### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by cstagman** [joomla/joomla-websites#1971]
www.mysbsc.org

Our website is down and I do not know how to access our Joomla Account to address issues. Our gmail email is through the website and is also down.

Please help!

Chris Stagman - Community Relations Manager
South Brevard Sharing Center
321-480-3452
cstagman@yahoo.com

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, 
not about your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
