### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by meganautas** [joomla/joomla-websites#1972]
Hello, I want to know if I can update Joomla version 4.4.3 with these warnings that make no sense, because there is no compatibility information. not one, not the other. It is very confusing because many of those who say they do not have compatibility appear in the verified component or act to be able to update Joomla. This information is not clear and we may make errors when updating. My version Joomla is 4.3.4
![image01](https://github.com/joomla/joomla-websites/assets/41700433/1b774efb-d683-47dd-ac78-38b0dfd210ce)
![image02](https://github.com/joomla/joomla-websites/assets/41700433/c1566260-0e7d-40ba-9ed7-75389ad1f214)
![image03](https://github.com/joomla/joomla-websites/assets/41700433/b16f278c-1047-4b70-ba98-f37d183de7a4)
![image04](https://github.com/joomla/joomla-websites/assets/41700433/733cf15c-5420-4fcb-92be-07008cec16e4)

**Comment by max123kl** [comment]
Dear Joomla! user
You have posted your issue to a repository that is responsible for Joomla's own websites.
These are located in the domain joomla(dot)org and all subdomains.

This repository is **only** for reporting issues with the official *.joomla.org websites, not about your own website that uses Joomla!

There are many experienced and helpful people on our forums, so for user support issues with your Joomla! website, please go to
https://forum.joomla.org/
or you can find help with our user documentation at
https://docs.joomla.org/Main_Page

If you are looking for a paid service provider, you can find one at 
https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thank you for your understanding.
