### ISSUE TITLE
[forum.joomla.org] Error upgrading from Joomla 3.10. 

### ISSUE THREAD

**Issue by birdiepromotions** [joomla/joomla-websites#1973]
Hello,

I'm new here and not very saavy with upgrading websites or coding. I had someone trying for the longest time to upgrade the Joomla to 4 or even 5 and he has been getting this error message. Can anyone assist or give some insight on how to get past this?

This is the error:

Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."

then there is an option that says Help me resolve this that isn't much help.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!

**Comment by birdiepromotions** [comment]
I guess I'm confused. I thought I asked the question on forum.joomla.org?
That's the same link you just sent is it not?

**Comment by pe7er** [comment]
No, you created an issue with ``[forum.joomla.org]`` in the title, in a GitHub repository dedicated to issues with the official Joomla.org websites.

https://forum.joomla.org is a separate website for issues with Joomla users' websites.
Please go to that website to get help with the issue on your own website.

**Comment by birdiepromotions** [comment]
Thank you, I will do that.
