### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by RCorreia24** [joomla/joomla-websites#1976]
Hey! I have a website (aeisec.pt) with joomla and I delete all the permissions of everyone and now I cant edit my webpage.  And now anyone can edit the site, can you help cause is a website of an University and is very urgent.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
