### ISSUE TITLE
[jhelp] intalling an ecwid template 

### ISSUE THREAD

**Issue by mpustalka** [joomla/joomla-websites#1984]
Connecting is fine to ecwid but not able to upload theme and website code comes up as rext.. need assistance please. Documentation isn't correct

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
