### ISSUE TITLE
Cannot access links on my website

### ISSUE THREAD

**Issue by bforman5** [joomla/joomla-websites#1985]
I can access the main page, but when I click on a link, I get a message that I "don't have authorization to view this resource.  I also am having trouble with my administration login.  When I click on log in it stays on that log in page.   My website is Golf Fit Carolina (www.golfitcarolina.com).  Thanks

Bob Forman
336-509-4610

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!

**Comment by pe7er** [comment]
For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
