### ISSUE TITLE
Administrator backend log-in fail 

### ISSUE THREAD

**Issue by bforman5** [joomla/joomla-websites#1988]
I can't log-in to my Administrator backend.  Username and password is entered and when I click on "log-in" it just returns back to the log-in page.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
