### ISSUE TITLE
No Hebrew language package

### ISSUE THREAD

**Issue by emanuel-r** [joomla/joomla-websites#1989]
I don't find a Hebrew package for Joomla 4.

What steps should I go through to create it by myself?
I tried to copy other language files, both in the site and administrator languages folders and changed to he-IL everywhere (XML files and localize.php and, of course, the folders themselves), but it seems insufficient. Joomla doesn't recognize the new language).

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!

**Comment by max123kl** [comment]
See here https://downloads.joomla.org/language-packs/translations-joomla4
