### ISSUE TITLE
UNABLE TO LOGIN TO JOOMLA ADMIN PORTAL

### ISSUE THREAD

**Issue by Agstar01** [joomla/joomla-websites#1993]
Dear Sir/Madam,

I am unable to login to Admin Portal. Staff member who previously administer this has left the company and we need to gain access to the portal to administer our website www.ecm.com.pg.

Kind Regards,

Mon Aisir
mon.aisir@ecm.com.pg

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
