### ISSUE TITLE
Joomla5

### ISSUE THREAD

**Issue by babincan** [joomla/joomla-websites#1998]
Dobrý, mám problém s joomla5 , vždy po aktualizácii na novú verziu stránka spadne. Do administrátora sa dostanem môžem robiť zmeny, ale stránka spadne. Viete mi poradiť??. www.farnostbabin.sk

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
