### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by steelborn** [joomla/joomla-websites#200]
First, I am unable to log into Joomla with my original account. 

Second, something is massively wrong with my site. I already checked with the hosting site, and they say it has to do with Joomla.

The pages are full of lines like this:

Strict Standards: Non-static method JLoader::import() should not be called statically in /home1/editguy/public_html/erikrosenbluh.net/libraries/joomla/import.php on line 29

My site is: erikrosenbluh.net

**Comment by mbabker** [comment]
1) This repository is only for reporting issues with the `*.joomla.org` websites, not the Joomla CMS.  For CMS bugs, please use https://github.com/joomla/joomla-cms/issues/new

2) For user support issues, please use the Joomla Forum at http://forum.joomla.org

3) This is an issue specifically with Joomla 1.5 and running PHP 5.4 due to its PHP 4 compatibility.  You can silence error reporting on this installation to hide the message regarding JLoader.  Your other issue should be taken to the forum.

**Comment by steelborn** [comment]
Thanks
