### ISSUE TITLE
[joomla.org] Blank page when choosing "Menu Item Type" and "Select".

### ISSUE THREAD

**Issue by comprog-ux** [joomla/joomla-websites#2018]
Not possible to make a new menu item. Joomla 5. Totally stuck. Running Safari on Mac
But when running in Chrome I got "viktoria.kozow.com **refused to connect**."
When inspecting in Chrome it shows:
"The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field."

In Safari it says: "[Error] Refused to display 'http://viktoria.kozow.com/administrator/index.php?option=com_menus&view=menutypes&tmpl=component&client_id=0&recordId=0' in a frame because it set 'X-Frame-Options' to 'DENY'."

So what's the problem?

![Skärmavbild 2024-08-16 kl  15 26 43](https://github.com/user-attachments/assets/bba16126-c604-4658-9ed7-2244e94626c8)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
