### ISSUE TITLE
[jhelp] Our site crashed yesterday 

### ISSUE THREAD

**Issue by ricmcd46** [joomla/joomla-websites#2020]
Please describOur site cis showing a http 500 error , how can I resolve this

**Comment by ricmcd46** [comment]
the site is https://www.southerndistricts-rotary.com/
I can get into the back end but not the front

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
