### ISSUE TITLE
[joomla.org] www.aquavera.fr

### ISSUE THREAD

**Issue by Culminique** [joomla/joomla-websites#2022]
JOOMLA merci pour votre aide Véronique Culminique AQUA AURA ENERGIE www.aquavera.fr

je n'arrive plus à me connecter sur mon site www.aquavera.fr
identifiant et mot de passe et l'adresse mail  plus valide (cela me dit non reconnue )

voici mes identifiants et MP avec lesquelles je me connectais depuis des années 
vuzelia
VeCuVi88.

OVH ne reconnait pas mon adresse mail veroniqueculminique@gmail.com
cv121123-ovh

je ne peux pas travailler sur mon site www.aquavera.fr

je pense etre victime d'usurpation d' identité

car sur le net je vois un parc d'attraction avec  tous mes noms  identiques 
aquavera.com
Aqua Aura Energie  et l'adresse de contact 

je viens de recevoir un mail avec mon adresse de contact@aquavera.fr pour une annulation de contrat je vous le joins ci dessous 

ce qui m'a interpellé
Anne-Marie Ruiz <annemarieruiz@hotmail.com> | Anne-Marie Ruiz <annemarieruiz@hotmail.com> | 10 sept. 2024 10:18 (il y a 1 jour) |   |  

Anne-Marie Ruiz <annemarieruiz@hotmail.com>
À contact@aquavera.fr | À contact@aquavera.fr
À contact@aquavera.fr
-outlook-mobile-signature Bonjour, Mon papa est décédé samedi 7 septembre.  Jean Ruiz 38 rue du négron 13118 Entressen Code client : 1149774.Je souhaite donc annulé le renouvellement de son contrat d'entretien d'adoucisseur d'eau. Je vous remercie Cordialement Anne Marie Ruiz

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
