### ISSUE TITLE
Cassiopeia mobile menu collapse dropdown bug

### ISSUE THREAD

**Issue by xeno024** [joomla/joomla-websites#2027]
I've discovered a bug in the Cassiopeia topic and I can't find a solution, and I don't even know what's causing it.
I searched around and found such a page, and it appears here, too, on several browsers: https://cassiopeia.joomla.com/help/menu-module
When I'm in mobile view, and I open the hamburger menu ("Site Modules" - Menu Module Settings in the "Advanced" tab under "Layout" - "Collapsible Dropdown Menu" ), then open the submenus, any of them, then close the whole hamburger menu as it is, leaving the submenus open, then open it again... If I play with this for a while, something randomly gets stuck and suddenly the collapsible submenus don't open. I check the inspector, can't find the cause of the error.
Several joomla versions have the same error (J4, J5), tested on localhost, with a completely fresh, empty installation, same thing.
Has anyone experienced similar?
Can anyone tell me what could be causing this error?

Thx!

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

If you can reproduce this issue with a clean installed Joomla website without 3rd party extensions, then please report a bug here: https://github.com/joomla/joomla-cms

For this reason, I'm closing your issue here.
Thanks!
