### ISSUE TITLE
[joomla.org]

### ISSUE THREAD

**Issue by johnlee16fuji** [joomla/joomla-websites#2031]
Please describe the problem or your issue

Login, then click on edit icon in Members, Judges results, receive error 500 , went to siteground checked error logs , all entries deprecated, seems to be old code in use, can this be rectified ?

Regards
John

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
