### ISSUE TITLE
Cannot Log In or Reset

### ISSUE THREAD

**Issue by AsquithBaptist1** [joomla/joomla-websites#2032]
Hello,

I am not able to login to our account. I am the Office Administrator for asquithbaptist.ca. I have attempted several times to reset my password but a password reset has not been sent to my email account (asquithbaptist@gmail.com). At this point I am locked out of our account. If someone could help me resolve this issue that would greatly appreciated.

Sincerely,

Crystal Peters
Office Administrator
Asquith Baptist Church
admin@asquithbaptist.ca

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
