### ISSUE TITLE
Téléchargement d'images

### ISSUE THREAD

**Issue by fabienne75154** [joomla/joomla-websites#2033]
Sous Joomla je ne sais pas comment télécharger une image dans smartimages 154300.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
