### ISSUE TITLE
Joomla Iframe Menu

### ISSUE THREAD

**Issue by ipsehans** [joomla/joomla-websites#2035]
Good morning,
since a long time in Joomla 5.1 and before:

- create a new menu item of type wrapper
- in the tab Advanced / Auto Add I could prevent to add http://  before the URL
- this does'nt work 
- http://  is allway added before the URL

Thanks for reoair
Sincerly 
Hans Waelti

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
