### ISSUE TITLE
Ayuda por favor

### ISSUE THREAD

**Issue by Ryckycarrizo** [joomla/joomla-websites#2039]
Hola Hace meses que tengo este problema y no puedo solucionarlos, pero les envio el enlace de ingreso para que ustedes lo vean:

http://curasopp.com.ar/web/index.php

realmente no se como resolverlo y no encuentro herramientas que me ayuden a recuperar el contenido y poder hacerlo de nuevo usando el material que ya estaba cargado...

desde ya muchas gracias

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
