### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by royaleng2013** [joomla/joomla-websites#2047]
I am the sole owner of a website created on Joomla.

I don't remember the username, password or email used.

my website is www.royaleng-me.com

How can I get my username or the email I used so I can reset the password.

Your reply is highly appreciated at the earliest.

Best Regards,

Mohamad Hamad

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
