### ISSUE TITLE
[jdown] http://www.commercialigiene.it/

### ISSUE THREAD

**Issue by fabio218** [joomla/joomla-websites#2048]
Good morning, I have managed the site in question for many years and I wanted to update the domain, but the customer tells me that nothing can be seen. Having said this, many years ago I had a communication agency with people who followed all this aspect, but today I no longer have them and I am alone without the knowledge and details of things. I tried to log in to Joomla, with old credentials, but it doesn't allow me to log in because it doesn't match and because it's old. Now all contacts are new. I await directions to enter and help![Image](https://github.com/user-attachments/assets/b187f33b-12c6-41c3-b327-6455f65ac034)

**Comment by pe7er** [comment]
Good morning,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
