### ISSUE TITLE
[joomla.org]

### ISSUE THREAD

**Issue by Kalaniart** [joomla/joomla-websites#2051]
my webpage is not working...   almoloya.hidalgo.gob.mx          can you please help me.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!

**Comment by ghost** [comment]
You can get support at the [forum](https://forum.joomla.org/) as ```This repository is for reporting issues with the joomla.org websites only. ```

Please close the issue.
