### ISSUE TITLE
[joomla.org] Website not working after Joomla 4 update

### ISSUE THREAD

**Issue by fairuzzi91** [joomla/joomla-websites#2053]
Hello I have issues accessing by backend after trying to update my website to Joomla 4. It gives several error, refer to the screenshot ![Image](https://github.com/user-attachments/assets/3805e1e9-4230-4730-9215-70f473138b0d)

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
