### ISSUE TITLE
Configuration -> Server -> eMiling: Issue

### ISSUE THREAD

**Issue by Doppeleule** [joomla/joomla-websites#2055]
Hi all, 

under: Configuration -> Server -> eMiling
am not able to set / change my password for my smtp authentication. When i klick on the Button in the field "Password" nothing happens.

Best regards
Uwe

**Comment by pe7er** [comment]
Hi,

This is a known issue in Joomla 5.2.2. It will be corrected in the next version. In the meantime you can manually change the email directly in the configuration.php file.

Note that this repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
