### ISSUE TITLE
[jdocs] Forces right to left

### ISSUE THREAD

**Issue by shauleiz** [joomla/joomla-websites#225]
The site insists on displaying the pages in Hebrew and Right-to-left.
How can I make it display in English and Left-to-Right?

**Comment by MATsxm** [comment]
This is based on the browser (language setting) and/or geographic location. 
I would suggest to signup:
https://docs.joomla.org/index.php?title=Special:UserLogin&type=signup
Then Login.

* go to Menu -> Preferences
* Internationalisation - Language -> select: en - english
* Save

That is supposed to force the default EN language

**Comment by shauleiz** [comment]
Does it make sense?
In order to read a document correctly, I need to register to as a Joomla Doc member?
This is true only for people in places where the default language is R2L.
Let me see, if you leave in Egypt, Iran or Pakistan (Which amount to about 200 million people) and you want to **read **a document you then you must register.
However, if you live elsewhere - you don't.

**Comment by MATsxm** [comment]
Sure it makes sense if your computer params are set up to read in Hebrew and TBH, you're the first to ask about it.

**Comment by brianteeman** [comment]
No marc that's wrong. If the content is in English then it should always be
displayed ltr no matter what the local browser settings are.
Tomorrow I will set my Firefox to Hebrew and see if I can debug

**Comment by MATsxm** [comment]
@brianteeman 
then I miss something...
you mean the en is currently RTL???

**Comment by brianteeman** [comment]
When hebrew is the default language then the docs site loads as RTL
The problem is that pages that are only in english are also displayed RTL when it should be only the hebrew language pages
I "think" its a bug in media wiki. Hebrew is one of the available languages so it is detected as an available language and switches the entire site to RTL when it should only switch those pages that are actually in hebrew

It is easy to test in firefox. Simply add hebrew as a content language and make sure it is the first language and then visit the docs site and you will see

**Comment by MATsxm** [comment]
I see now... must be (not sure at this point) in relation with the "Special:" status for pages available for translation.
I'll have to dive a little further.... I miss @Hutchy68 :stuck_out_tongue_winking_eye:

**Comment by brianteeman** [comment]
Yes the special bit is the only bit on hebrew on the page so it must be
setting everything to RTL

On 25 February 2016 at 22:14, Marc-Antoine Thevenet <
notifications@github.com> wrote:

> I see now... must be (not sure at this point) in relation with the
> "Special:" status for pages available for translation.
> I'll have to dive a little further.... I miss @Hutchy68
> <https://github.com/Hutchy68> [image: :stuck_out_tongue_winking_eye:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/225#issuecomment-189008521>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by shauleiz** [comment]
The funny part is that I don't think my browser (Chrome) is set to Hebrew. Nor my Computer (Windows 10 Enterprise En-Us).
The computer's location is set to Israel and my IP probably points to Israel.
So, I don't have a clue why the Doc site assumes it should display the pages R2L. Also, it displays the frame (Search etc.) in Hebrew which is not a real problem but hey, what about a person that does not speak Hebrew that is located in Israel?
I think we have two distinct issues here:
- A text written in L2R language should to be displayed so even if the location setup is R2L
- The option to select a language should not require subscription.

**Comment by brianteeman** [comment]
Yes its a definite bug with the mediawiki config
As Mat said it uses either the browser language or IP address (it was
easier for me to add a browser language than to fake an IP address :) )

Because it is identifying you as an RTL user  by IP it tries to load a RTL
version of the page - that is wrong
Then it is worse because the page has just one bit of hebrew on the page
but the rest is in english which of course looks worse in RTL

Please allow us some time to investigate this and we will update this here
when it is resolved.

Thank you so much for reporting this - its appreciated

On 26 February 2016 at 08:42, Shaul <notifications@github.com> wrote:

> The funny part is that I don't think my browser (Chrome) is set to Hebrew.
> Nor my Computer (Windows 10 Enterprise En-Us).
> The computer's location is set to Israel and my IP probably points to
> Israel.
> So, I don't have a clue why the Doc site assumes it should display the
> pages R2L. Also, it displays the frame (Search etc.) in Hebrew which is not
> a real problem but hey, what about a person that does not speak Hebrew that
> is located in Israel?
> I think we have two distinct issues here:
>
>    - A text written in L2R language should to be displayed so even if the
>    location setup is R2L
>    - The option to select a language should not require subscription.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/225#issuecomment-189164914>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
