### ISSUE TITLE
[josm] Missing the Trademark-use Request Form

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#23]
even if everybody knows my point of view about this declarative system (as stupid and ineffective as no-mosquitoes plugs), the application form is no longer active for many months for the the Trademark-use Request.
http://opensourcematters.org/legal/trademark/213-trademark-use-request.html
Asked Marco Richter about it few days ago...
Thanks

**Comment by Hutchy68** [comment]
I see a link on that page which takes you to a form. Not very apparent and I didn't fill out the form to test. Perhaps a button so it isn't missed. Are you saying the form doesn't work?

**Comment by MAT978** [comment]
Nope, the link was supposed to be a temporary solution... "TEMPORARY" ;)

**Comment by SpiritJC** [comment]
The trademark team is looking for volunteers.
Once we have rebuild the team, we will working on the new website.

The new website has the highest priority :-)

**Comment by Radek-Suski** [comment]
If I may to dare to ask: why do you need yet another website (**YAW**) for this team?

**Comment by mbabker** [comment]
I'm just going to link to this and say I agree totally - https://groups.google.com/d/topic/joomla-leadership/NcA94igR7UM/discussion

I've got no problem helping get a team going on an existing install (as long as I have access), but for the love of what's left of some of our sanity, can we not add to our existing menu of ~30 Joomla installations, please?

**Comment by MAT978** [comment]
if the "new site" means integration in .org, and if the TLWG wish, Sandra and I can help if needed/wanted

**Comment by SpiritJC** [comment]
There is already an existing website for more the 2 years.

The purpose off this website was to decouple from the osm website since that hold back the upgrade of that website. 

The idea was to have a ticket system implemented, which was done at that time by Pedro Gonçales. After that a long time no work was done on the site. At JWC14 some people worked on the content of the website. We want to move on with what we have right now in order to get the trademark process working again like it should've been for years

The trademark team would be the team to work with the ticket system, it seems a lot easier to me if this website is, as it was decided long ago, a stand alone site.

@Radek-Suski : As far as i know, during your time within OSM it was numerous time explained to you.

**Comment by mbabker** [comment]
A lot's changed in 2 years, including identifying a lot of very bad practices that we've enabled, such as setting up subdomains and separate Joomla installs for no other reason than we can (serious personal rant, but WTF do we *NEED* separate installs for JRD, community, VEL, magazine, developer, and events when almost all of that content could be rolled into one install and managed via ACL and the right combination of server configuration and extensions for multi-site?).  This is why we have 30 separate CMS installs on `*.joomla.org` and quite frankly it needs to be dealt with.  The TM site was never live, so if it doesn't have requirements that demand it be a totally separated install, then lets merge its content and whatever into an existing install and try to work on cleaning the absolute mess that is our website architecture.

Is there anything in the proposed TM site that justifies making it a fully standalone site, and if so, what?  If there are requirements to make it a standalone site, let's make them clear before it launches instead of sticking with status quo just because it's status quo.

Sorry if it seems like I'm groaning at the TM team specifically, I'm not; I'm just annoyed at the major disorganization our group has.  We produce a CMS and we can't seem to use the software our own community produces to manage our own sites effectively.

**Comment by MAT978** [comment]
so it seems that the TLWG is still on that stupid declarative system policy...
and even if, what would justify a dedicated and isolated site that a single form can't do?
always repeating the same mistakes again and again...

**Comment by marijkestuivenberg** [comment]
Hi all,
The decision to create a separate website for tm was taken long ago. I don't think it makes sense to go back every time again and repeat this discussion over and over again. At least I get tired of it.

It is a known fact that the trademark process has been a struggle for years. The system used to keep te records of requests and the conversations with the parties involved was a huge drama. I think we can all remember how it caused the osm website from going down frequently. Other reasons to have it as a separate website is, the current one on tm.joomla.org (which is up to date with the latest version of Joomla) has a new ticket system build in. A lot of hours and work got into that and last year we were not that far of launching it. All it needed was updated content, better information on when and how a request can be made. The hopes were high at that time that the new manager would take on this job, we even had a meeting at a JDay in the Netherlands back then to get him up to speed. Long story short, he didn't focus on that part of the job. Now we found Marco being available to carry on where others left of. 

As much as I agree that it doesn't make sense to create a website for each and anything, I think maintenance of our trademark is important enough to not have any hold backs anymore and the fastest way to get things online is to work on what is already there. It already is migrated to the latest version, as said includes a ticket system with a lot of work in it, and last but not least; Trademark is related to legal matters. Conversations going on in the ticket system could include confidential information that we prefer to keep within a small group of people working on this.

At MAT, I know your not a fan of the trademark process we use, that's okay, calling it stupid is not. If you think it can all be done with a single form, it shows that you're not aware of the work. Right now it is maintained with a single form, and I can tell you that is not the best way to maintain it!

**Comment by MAT978** [comment]
So as I understand it, the only valid justification is: "The decision was taken long ago"...
due credit.

**Comment by Radek-Suski** [comment]
Hi @marijkestuivenberg,

I can imagine that you are tired. Your tiredness is however not caused by the fact that someone is attacking you but because everyone who is asking it is simply not able to comprehend this decision. 
I will try to go step by step with your arguments:

* `the decision to create a separate website for tm was taken long ago` - despite the fact that this is absolutely irrelevant argument, it's also not quite correct. As Jacques was working on the OSM website he was actually integrating the ™ part into the OSM site. After Crystal eventually took over and finished the site the ™ part was removed. I doubt Crystal took this decision on her own and frankly for me it looks like this decision have been made shortly before the OSM site has been finished. So as much the time feeling may be very relative, I wouldn't call it "long time"
* `it caused the osm website from going down frequently` - fully agree. Ironically the reason why the site went down frequently was the fact that this site was under-maintained. Which is exactly what we are trying to avoid. Am I understand it correctly that the reason to split the most relevant part of the OSM website to a separate one is the fact that you fear that this site would goes down again? 
* `the current one on tm.joomla.org .... has a new ticket system build in.` - the system was previously part of the OSM site and has been split later. I don't see why it could not be integrated back into OSM website, or, even better probably, into the joomla.org site
* `A lot of hours and work got into that and last year we were not that far of launching it` - forgive me my ignorance but how much time a team of people need to built a single, relatively simple website? But apart from that, this work is not going to be wasted. It's not a big deal to integrate it into an existing website.
* `I think maintenance of our trademark is important enough to not have any hold backs anymore and the fastest way to get things online is to work on what is already there.` - agree. But again, there is no reason to create **YAW**. I am pretty sure we could integrate the whole site into an existing Joomla! website within days.
* `Conversations going on in the ticket system could include confidential information that we prefer to keep within a small group of people working on this.` - and I can repeat what I am repeating the whole time since this thing came up: **We have a very advanced ACL in Joomla! since the version 1.6**. I would seriously recommend to play with it some day. This is really an awesome tool. Seriously.

Respectfully,
Radek

**Comment by marijkestuivenberg** [comment]
At MAT, I did write a couple of lines more, you might want to read them too...

At Radek:
- Jacques put a lot of work in the migration of the OSM website and was the one that worked towards decoupling the trademark part. Not intergrating. I worked closely with Jacques on it at that time and was involved with creating the ticketsystem. The ticketsystem was build in the migrated site, but with the intention to decouple it.

- Crystal never took over anything, she was only briefly involved during JWC14. I worked with Saurabh on the website, the only way to finally be able to launch the migrated OSM website was to remove all TM related stuff that was not up to date or subject of discussion in the TM team. 

- Already in February when Duke took over the TM lead from Jacques, the decision was made to have only brief information of TM on the OSM website, linked to more in dept information on the TM website, including the ticketsystem. 

- The site was not under- maintained. The CivicCRM part were records were kept of all TM requests was causing the issues. All TM related stuff was causing the delay to get a migrated version online, hence the choice to remove it. 

- There is no fear for a site going down, there is a concern to prevent happening in the future from the issues we've faced in this process, not being able to migrate records of TM requests and all conversations and a huge delay in upgrading the OSM website.

- The term 'relative simple website' is very relative. Why do I get the feeling that I have to explain things to people that never ever looked under the hood of this website, and all the ones that have don't have these kind of questions but all come to the same conclusion. Why do you want to ignore and be irrespective to what people who actually have to work on the site think would be the best way to move forward.

- I am totally up to speed concerning all Joomla features, including ACL. Degenerating my knowledge about Joomla's system is a non argument in this discussion. Thank you!

**Comment by rdeutz** [comment]
Integration it is the right path, we followed long enough the wrong path of creating separate websites for any little use, we need to stop. Haven't read a real argument for keeping it separate.

**Comment by mbabker** [comment]
On my part I asked one simple question and made one simple statement:

> Is there anything in the proposed TM site that justifies making it a fully standalone site, and if so, what? If there are requirements to make it a standalone site, let's make them clear before it launches...

Thus far, the only thing I can see justifying it is the legal argument, and I'll admit that has a bit of strength.  Let me make clear once more, my groaning has nothing to do with the TM team, it's with the fact that we have ~30 CMS installs, most of them stupid simple installs that could seriously be merged into one site (the community site blogs, the dev site in full, the volunteer portal, the VEL, just to name a few) or so complex that they have reached the unmanageable point (hello community site that nobody can seem to figure out how to upgrade past 1.5).  The current WIP site is running the latest version and upgradable, great job, that should be the standard for our sites.

There's a technical concern noted about CiviCRM (or whatever integrations were in use previously) causing the site it's hosted on to constantly crash.  I'd seriously evaluate whether a new platform is needed if it's that unstable, and if that's already been done then great.  I don't have access to the OSM site backend or the TM site, I don't know what's gone on behind the scenes during those two site's upgrade/development periods, so all I can do is make blind guesses.

The decision was made 2 years ago to make it a separate site and that stance isn't changing.  OK, got it.  I asked for some justification on the decision and found some in the legal argument, I can live with it.  That said though, I'm going to keep groaning about the fact that we have so many CMS installs on every major version branch of Joomla and the fact that our admin team can't seem to administrate the `*.joomla.org` network efficiently until something is done about it.  If that offends or annoys anyone, I'll offer my half-hearted apology in advance right now, but quite frankly having seen as much of our infrastructure as I have, the current situation is a complete freakin' joke.

**Comment by JacquesR** [comment]
Just a clarification: CiviCRM is not afaik used for the new TM site. It caused issues on the old site mainly because bots were targeting the TM forms, and the load made the site fall over. It was also used for something that it was not really created for. (Pedro's component is the one installed on the new TM site)

Michael I do understand the points you are making, but my view is slightly different.

The Community site is a good example of the problems that comes with maintaining a big site. Anything that's now a co-install on that site (not sub-domain) would have to wait until that big ship manages to turn.

If sites are not maintained, then yes, merge them (or even better, get new volunteers in those teams), but to force all sub-sites into the main Joomla site will just create a bloated install that's more likely to fall over.

On the other hand, if a team is maintaining a sub-domain site, then leave them be to work where they choose to. It's not hurting anybody else.

**Comment by rdeutz** [comment]
@JacquesR yes atm there might be a team, but time is running fast and soon you might have the situation nobody know or is able to manage the site, and then? Someone else has to clean the mess with starting to get the admin keys for the site. Wouldn't be the first time we run into such a situation.

**Comment by mbabker** [comment]
> Michael I do understand the points you are making, but my view is slightly different.
> 
> The Community site is a good example of the problems that comes with maintaining a big site. Anything that's now a co-install on that site (not sub-domain) would have to wait until that big ship manages to turn.

That's why we don't put everything on one site.  Let's be honest for a minute though, the main content that is published currently on www, community, magazine, and developer is essentially blog content or static articles; all of that can be merged into a single site and organized via categories and ACL used to limit publishers as needed.  If I'm not mistaken our current events site is using a single component for organizing the event data and some articles for static text (just the way the site looks on browsing, I don't know the backend structure); generally that site's content could probably be merged with our main single install too.  As far as the VEL goes, again it looks to be mostly articles plus a form component for receiving submissions; I don't see anything here justifying it be a separate install.  The `joomla.org/3` landing page is yet another CMS install with i18n support, but again is mostly static articles, a couple of modules, and a unique template.  All of these sites I've listed are generally static content or a single additional component for a unique data purpose, merging them into one site does make it a big ship but this ship is serving a majority of one content type and a couple of extra extensions for unique purposes.  If it is really that difficult to coordinate the update of the core CMS install plus an event and forms component, then we have major issues.  (and yes I know I'm leaving out some content on all of those sites, like the showcase(s?) on the community site or JoomlaCode Issues Archive on the developer site)

We have at least three directory installations; JED, JRD, and the community showcase.  If I'm not mistaken, the first two are now completely custom solutions (JED at least dictated by needs, not so sure on the JRD's needs or structure) and if I'm not mistaken the showcase is a Mosets install (which I've heard is either hacked to bits or a botched install, main point is it sounds like it's a problem point in our structure).  I do understand at this point merging them into another install is pretty much inefficient, but it again goes to demonstrate total inconsistency in our network, very relaxed administrative standards (showcase is still on 1.5 and the way JRD is coded they are still running 3.3.3), and the overall miscommunication of our admin teams.

Our in-development downloads portal justifies a standalone site; download packages for the main CMS and the language packages top one million hits monthly.  Add to that the traffic that would be generated for browsing the site and potentially serving the XML update streams via the site and on the traffic alone we can justify having that separated and configured explicitly for high(er)-availability.

We can't run `joomla.org` off one CMS install, that is impractical and I agree 100%.  But, we can't run it with ~30 CMS installs, plus a phpBB installation, Jenkins CI, two Framework applications, Mediawiki, GForge, a (managed) UserVoice application, and a static HTML subdomain.  We've all seen the issues with that and I can't say enough that we need to do something about it.

**Comment by marijkestuivenberg** [comment]
Michael, don't get me wrong, I do agree on your arguments totally. As a fact, when we found Marco available to take the lead in TM and discussed the tasks and put a high prio on making available the needed TM information and ways to get our trademark requests handled in the best way, I gave him the keys to the existing website on tm.joomla.org and let him have a look under the hood. Already then he was contacted to integrate into the main site and I told him he was free to look at whatever he thought would work the best way for the team. He wasn't opposed it at first glance but he needed to look at it in more dept. Right now he has come to the conclusion that continuing the work on the site and subdomain that already exists is the easiest and fastest way to move forward with the team.
For me that is at the moment the best argument to do so. How hard everyone here tries to convince me that there are no arguments to not integrate it. On the flip side I don't see any arguments to not continue the work and finally get things moving forward. 

I understand your groaning, please understand my groaning about all that has hold back the trademark maintenance for so long. Now that we have people that want to work on it, please let them do the work.
They have the keys to it, they have all the permissions to do their work properly, the subdomain is already there, the site already installed and working. I really would hate to see yet another time that people get demotivated by that discussions that keeps them from moving forward on the work they are willing to do. If integration is that easy it can always be subject of discuss later on and decide with the team and all working features in place. As I read there is enough work already on the part of integration of a lot of other sites, I suggest, focus on that and let the TM team focus on their part. 

At Robert, I think we have a vault for that. It's just a simple thing to maintain access and passwords there and no one needs to clean up messes nor have to gain admin access. Imo not an argument to delay and continue the work where it is.

**Comment by rdeutz** [comment]
@marijkestuivenberg I second your point, let them concentrate on tm and not on the site, like updating the template, finding out why the site in not available and so on. The easiest way might be not the best one, migrating later will come with new problems like redirecting URLs to make the old still working. Now is the time to make it right.

**Comment by mbabker** [comment]
The point that was made about the legal info for me was enough to stop arguing for integrating the site into something existing at this explicit moment.  In an ideal world I'd still rather see it merged into something existing before launch but that alone at least gave me an argument for having a separate install beyond "well, the site is already there, let's just use it".

**Comment by rdeutz** [comment]
I was long enough in the TM team and haven't seen a need to keep it private at least not more private as you can make it via the ACL System. The "legal argument hammer" is too often used to kill discussion.

**Comment by marijkestuivenberg** [comment]
Robert, I really hope I don't have to draw a picture for you how trademark is related to legal! Seriously.
I am reading an email thread right now from 2011, where you reported to be totally lost in all the emails going on in TM and Jacques reported how he was working with Pedro on moving CivicCRM to IMaqma.
Then I realized, I have about a ton of other much more useful things to do then keep on arguing here. I have said what seems to me more and enough reasons to just move on. And as I learned in history you are a big fan of just doing and not wasting time on useless discussions, I am going to follow that example and bow out of this discussion and just let the TM team move on as they see fit best. 

For the TM team to move forward and be able to work as a team on TM, the website with the ticket system is essential. Past and current situation is proving that all the way.

Oh btw. I recall we have a redirect component in Joomla core, just in case URLs need to be redirected. While not being skilled enough to judge if the code of that component is good enough for Joomla standards, nor having the knowledge if the PLT has any plans to decouple it from the core, i think 'if' in any case later on integration is at stake, a solution for redirecting is at hand.

Michael, thanks for your understanding, I also agree with you about the ideal world, but reality tells us different at the moment. It is what it is.

**Comment by rdeutz** [comment]
@marijkestuivenberg yes I can remember and I agree it is time move forward 2011 is some time ago.

**Comment by MATsxm** [comment]
Where are we about this topic 6 months later?

**Comment by marijkestuivenberg** [comment]
https://volunteers.joomla.org/reports/202-tlwg-meeting-report-march-09-2016

**Comment by SpiritJC** [comment]
The website online now.

**Comment by MATsxm** [comment]
Great job! thanks
