### ISSUE TITLE
[jmag] article in violation of the JCM Content Guidelines

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#237]
Following the Joomla! Community Magazine Content Guidelines
https://docs.google.com/document/d/1OCi5pJZ7r4wKTbhvDb0Ci2A33tejikR4HvNWxqlrO1k/preview?pref=2&pli=1

> * No commercial advertising is permitted. This includes advertising of any services and/or products not fully compliant with the GPL license.
> * Any posts deemed to be self promotion, advertising, or spam can and will be removed. NO SPAM - NO ADVERTISING eg. Posting and making excessive, inappropriate and unnecessary references to your products and websites is self promotion.

and regarding the article:
http://magazine.joomla.org/issues/issue-mar-2016/item/2977-three-keys-to-a-successful-joomla-website-building-business

I would consider that the end of the article AND the signature both constitute a violation of the guidelines as they are a manifest self promotion and advertising.
![ead4abf7219799466eb502b133b2d0e1](https://cloud.githubusercontent.com/assets/1972717/13556323/2a117e5a-e3ad-11e5-964f-47e6109449ed.png)

Thanks for the explaination about that point.

**Comment by brianteeman** [comment]
it just needs the "about the author" part of the article removed as it is
already present in the info box - where it is allowed to have links (within
reason)

TBH though you should jut contact Helvecio or Jaques directly

On 6 March 2016 at 19:08, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> Following the Joomla! Community Magazine Content Guidelines
>
> https://docs.google.com/document/d/1OCi5pJZ7r4wKTbhvDb0Ci2A33tejikR4HvNWxqlrO1k/preview?pref=2&pli=1
>
>
>    - No commercial advertising is permitted. This includes advertising of
>    any services and/or products not fully compliant with the GPL license.
>    - Any posts deemed to be self promotion, advertising, or spam can and
>    will be removed. NO SPAM - NO ADVERTISING eg. Posting and making excessive,
>    inappropriate and unnecessary references to your products and websites is
>    self promotion.
>
> and regarding the article:
>
> http://magazine.joomla.org/issues/issue-mar-2016/item/2977-three-keys-to-a-successful-joomla-website-building-business
>
> I would consider that the end of the article AND the signature both
> constitute a violation of the guidelines as they are a manifest self
> promotion and advertising.
> [image: ead4abf7219799466eb502b133b2d0e1]
> <https://cloud.githubusercontent.com/assets/1972717/13556323/2a117e5a-e3ad-11e5-964f-47e6109449ed.png>
>
> Thanks for the explaination about that point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/237>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MATsxm** [comment]
why I'm not surprised... ;)

**Comment by Sandra97** [comment]
Also, articles on JCM are supposed to be related to Joomla. The subject of this article is not linked to Joomla, it's just a general topic, including self promotion (in order to get backlinks?). We managed during few years the French edition of the magazine and we refused this kind of articles, and it was the same for English articles.

**Comment by MATsxm** [comment]
This is clearly an abuse of the philosophy and principles that used to rule the magazine and also an open door to all kinds of excesses. We used to refuse (IMHO the right way) many articles in such cases, even some from the OSM President. Now, if the editors find it there is nothing wrong with that, I'm no more in charge of it but just thank you to let me know that the editors lines have changed.

@brianteeman Everything is not that black or that white (links are allowed yes, but the notion of abuse and/or excess of rights do exist also) and If you therefore considere that there is no problem to create links because they are present in signature, just let me know. That will be good to know..

**Comment by JacquesR** [comment]
@MATsxm Please don't use this issue tracker for complaints or debates on JCM content. 
The JCM chatroom on Glip seems far better suited for that. Or otherwise email or skype us if you spot a content issue. (you know us both, and the general contact email also routes to us) 
It looks like Helvicio already made some changes. I'll discuss further with him.

**Comment by Radek-Suski** [comment]
I think as this is issue tracker for all project websites it is perfectly ok to post it here. Also in case of transparency I think an open for everyone channel it seems to me much more suitable than a closed Glip channel

**Comment by helvecio** [comment]
I, as co-editor of the JCM, would like to thank you for your feedback. Since I was invited to be a part of this team, I realized there is a lot to learn. Being the magazine`s co-editor is a big responsibility and I`m glad the community is out there to remind the team where to go to increase our knowledge. 
Jacques and I are looking into this issue. 
It`s good to hear the opinion from the editors of the french magazine, who have been contributing for way much longer than me. I`m sorry that you see this incident as an abuse and that you are willing to leave the magazine for that reason. I don't understand it, but it's your call.

**Comment by Sandra97** [comment]
Helvecio, I think there's a misunderstanding. For information, MAT stopped to be the editor of the French section more than 2 years ago and I stopped one year ago and it was not for any "abuse" reason. 
Here, the goal was of course not to create a controversy but, as mentioned in the first post, it was just about asking for an explanation as it seems to be an abuse. 
As editors, if you decide it's not a abuse, just tell us.
To be honest, when we were editos, we would have loved to have a tracker like this so that people can report any "issue" or question.
Wish both of you good luck in your new mission.

I guess this issue can be now closed. Re-open it if needed.
