### ISSUE TITLE
[jforum] unable to register

### ISSUE THREAD

**Issue by GitHubincus** [joomla/joomla-websites#340]
I am unable to register or use the previous account, there is always an error message that tell me i did not fill in the password field correctly, this is a BUG!!!!

reply to : tom.2009@live.it

**Comment by MATsxm** [comment]
@pe7er
could you please take a look.
Thanks

**Comment by pe7er** [comment]
Did you empty your browser cache? Could you try it with another browser?

Could you please add a screenshot of your screen with the error?

Could you use the following form so that we could look into the problem with your existing account?
http://community.joomla.org/index.php?option=com_rsform&formId=3

**Comment by MATsxm** [comment]
No answer since 2 months - Closed
Re-open if needed.
