### ISSUE TITLE
[jcomm] blog post lanugage

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#343]
Once again a new post on community has a typo in the alias
`http://community.joomla.org/blogs/community/1900-basque-lanugage-pack-added-to-joomla-35.html`

And the link to the language pack is wrong - it goes to the spanish pack - which if i am not mistaken is definitely a faux pas

**Comment by MATsxm** [comment]
to the slovenian (sl-SI) pack

**Comment by imanickam** [comment]
Good catch Brian.  Apologize for the mistake in the link.  At present, i could not log into the site's back-end to make the correction.  I have contacted Peter about this.  Once, I could login, I will correct the issue.

**Comment by imanickam** [comment]
I am now getting in touch with Rowan about my login issue.  Further, I learned from Rowan that a new system is expected to be rolled out by mid next week.

The link is pointing to the Slovenian language instead of the language Basque.  In the Sand Box, I have corrected the link to point to the Basque language.  So, next week when the new system is rolled out,

**Comment by brianteeman** [comment]
And did you fix the alias?

**Comment by imanickam** [comment]
I observed that both in the existing page (http://community.joomla.org/blogs/community/1900-basque-language-pack-added-to-joomla-35.html) and in the sand box page (https://community.joomla.org/sandbox/blogs/community/3052-basque-language-pack-added-to-joomla-35.html), the alias has/have been fixed.
