### ISSUE TITLE
[jvols] What about archived groups?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#365]
I was looking at the huge number of working groups born within the GSoC 2016 on the volunteers portal.
But, when the GSoC will finish, what will happen to related groups on jvols?
Will they be archived? 
Is there a possibility to archive groups (not only for GSoC) and keep memory of the activity of them?

**Comment by mbabker** [comment]
From what I can tell the behavior right now is a group with no members falls off the active working groups list but is still accessible, see https://volunteers.joomla.org/working-groups/unit-tests-working-group as an example.

**Comment by jeckodevelopment** [comment]
Thank you Michael.
It could be useful to have a view for "past/archived" groups

**Comment by brianteeman** [comment]
Before doing that doesnt there need to be a decision about what is a "dead"
group. Just basing it on their being no members isnt enough as that
requires someone to remove all members. There are plenty of other "dead"
groups that woudnt be archived because they have members. A great example
would be this one
https://volunteers.joomla.org/working-groups/joomla-turns-10 for the 10th
anniversary. Not only has that "event" passed now the group did absolutely
nothing

On 10 June 2016 at 08:51, Luca Marzo <notifications@github.com> wrote:

> Thank you Michael.
> It could be useful to have a view for "past/archived" groups
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/365#issuecomment-225116127>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8QLqIvTPc1vaq2kKEq1A8n8MJFEYks5qKReRgaJpZM4IyidS>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jeckodevelopment** [comment]
It has been fixed by the new version of the Volunteers Portal released today.
