### ISSUE TITLE
[jrd] Menu: same name, different targets

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#405]
On resources.joomla.org if i click on "Get Listed" top menu item I'll see the page:
`http://resources.joomla.org/en/getting-started-on-the-jrd `

![jres-menutop](https://cloud.githubusercontent.com/assets/733133/16787887/44907846-48a0-11e6-8d18-c081e7acd5ed.PNG)

In this page I've a button and a right-menu item with the same name "Get listed" and the target page is: 
`http://resources.joomla.org/en/getting-listed-on-the-jrd`
to start the application process.
![jres-menuright](https://cloud.githubusercontent.com/assets/733133/16787906/6c3f0f56-48a0-11e6-90ae-522204ffc06e.PNG)

In my opinion, we need to differentiate menu item names, using "Apply now" or something like that for the button/menu item to start the application submission process.

Thank you!

**Comment by genr8r** [comment]
@jeckodevelopment if you look at your screenshot, there are actually 3 different items that are all labeled "Get Listed" (great UX huh?).

The button in the article and the top sidebar menu item both go to the start of the application/registration process.  So, given your feedback I have changed those two items to "Apply Now".  They both do the same thing.  I considered eliminating the button in the article but I am betting the original thought was to make the primary call to action on the page a little more obvious.

I kept the "Get Listed" menu item in the menu bar as it is because it is the primary navigational item that gets you to this page where you learn about what is involved with getting listed.  Feel free to re-open this and provide additional feedback if you think there is more that can be done to streamline and add clarity.

**Comment by jeckodevelopment** [comment]
@genr8r I like it now. Thank you.
I suggested this change because I thought that same item name with two different targets could be misleading.

**Comment by genr8r** [comment]
I agree. It was a good suggestion.
