### ISSUE TITLE
[jrescs] Endless loading at the bottom

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#406]
If I go to resources.joomla.org (with or without the HTTPS) I see an endless loading Joomla! clover at the bottom of the page, under the list of categories.

![jres-endless](https://cloud.githubusercontent.com/assets/733133/16788019/687a986c-48a1-11e6-8ce2-435d6a8c1910.PNG)

I guess that there should be the provider map / search filters there.

**Comment by brianteeman** [comment]
Probably related to

Refused to execute script from '
https://resources.joomla.org/cache/widgetkit/widgetkit-9fcb460d.js' because
its MIME type ('text/html') is not executable, and strict MIME type
checking is enabled.

On 13 July 2016 at 01:28, Luca Marzo <notifications@github.com> wrote:

> If I go to resources.joomla.org (with or without the HTTPS) I see an
> endless loading Joomla! clover at the bottom of the page, under the list of
> categories.
> [image: jres-endless]
> <https://cloud.githubusercontent.com/assets/733133/16788019/687a986c-48a1-11e6-8ce2-435d6a8c1910.PNG>
>
> I guess that there should be the provider map / search filters there.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/406>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8XO2mIwI8hW7rg9futBWttTZmT8Aks5qVDE2gaJpZM4JK9Hy>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by genr8r** [comment]
This issue is resolved
