### ISSUE TITLE
[jvols] outdated PHP version

### ISSUE THREAD

**Issue by rdeutz** [joomla/joomla-websites#422]
Anyone knows what are the steps to update to a newer PHP Version, I have cpanel access but there is nothing. Ticket to Rochen?

**Comment by sanderpotjer** [comment]
@rdeutz I do think it needs to wait on https://github.com/joomla/joomla-websites/issues/127 before the PHP can be upgraded on the server

**Comment by rdeutz** [comment]
Thanks @sanderpotjer but we can move the site to another box? 

@mbabker ?

**Comment by jeckodevelopment** [comment]
Is there the possibility to unlock the situation with Showcase?
Do we have a less used space where to move this website?

**Comment by mbabker** [comment]
The only thing I can think of is to move the showcase site to the server we have Jenkins running on since that's still a PHP 5.4 box, but we also set up that server explicitly for Jenkins and not the intent of hosting a "visible" site so it may not be the best of ideas.  Otherwise, we don't have any other place to move that site without establishing a new server; every other box that we have is running PHP 5.6 and I'd start requesting PHP 7 for those except after the last round of updates not going so smoothly I'm hesitant to ask for more changes at the moment.

**Comment by jeckodevelopment** [comment]
We should define a due date for the new Showcase, otherwise we need to stop the current installation and wait for the new version.

**Comment by mbabker** [comment]
They had a beta version running last year (see all the open issues here about that site).  So unless someone rebuilt from scratch after that point, I'm curious why that hasn't been completed by now.

**Comment by jeckodevelopment** [comment]
maybe that team should be improved... but it's not fair that an outdated / abandoned project creates too many issues to the others.

**Comment by mbabker** [comment]
Well in their defense they weren't the single point of failure until about a month ago.

**Comment by jeckodevelopment** [comment]
of course. But we should start sorting out things.

**Comment by rdeutz** [comment]
ok guys, let's stop discussing it, seems more complicated as I thought. World will not end when the v.j.o will run on PHP 5.4.x for a longer time.
