### ISSUE TITLE
[jmag] Social Media module

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#475]
This module is really not nice and quite useless (no need to mention all the HTML code needed for it) as we already have them in the footer. 
And regarding, the newsletter part, could you please correct the display in order to have the 2 elements correctly aligned?
Thank you! 
![index](https://cloud.githubusercontent.com/assets/4682328/17912273/9128b7dc-6960-11e6-9c7b-684c8764ee60.png)

**Comment by MATsxm** [comment]
I have no words to say how ugly and has been this mod is...
I thought we were in 2016

**Comment by JacquesR** [comment]
This is a all-in-one legacy (very old) custom module that will be removed in the near future. 

It may be good to still have a Facebook module there, specially since it is a community-orientated sub-site, but I still wanted to chat to @Joomv to see if the Community site is planning to use a FB module on that site, and then use the same.  (someone from the FB J admin would have to create the module for us)

The Subscribe part will be replaced by something else.

@MATsxm please try to use a less snarky style of communication here. Thanks.

**Comment by JacquesR** [comment]
I've removed that old social media module, and replaced it with 2 custom modules on all pages (on the English edition for now). 

The one with the code for the social sites (the same that's used in the template footer), and the other one containing updated code to subscribe to the JCM (English edition) via Feedburner.  I'll make the same changes to the Spanish side after confirming with their admin.
The styles will be tweaked later on.
