### ISSUE TITLE
[jmag] old articles on the frontpage

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#495]
On the frontpage  articles from July 2010 are currently displayed 
![screen shot 2016-08-29 at 09 59 15](https://cloud.githubusercontent.com/assets/1110663/18044708/74e91fa8-6dcf-11e6-9c17-eb1d20ee76c9.png)

**Comment by jeckodevelopment** [comment]
Confirm!!!!

**Comment by JacquesR** [comment]
This is a strange bug that appears from time to time (since we upgraded the site). Clearing the cache fixes it, but it's unknown what causes it. I'm (on the test site) working on a different/simpler way to show the new month's articles, that should avoid this issue.
So no immediate fix, other than to clear the cache when the issue appears.

**Comment by wilsonge** [comment]
I've hacked k2 to stop caching in the list view. Fuck life.
