### ISSUE TITLE
[jshop] the adress popup has a smal `Ok` button

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#519]
If you checkout an article and the system asks for more information the `ok` button is very smal and not good visible.

![image](https://cloud.githubusercontent.com/assets/2596554/18097514/59252324-6ede-11e6-92c1-952e9a3d8998.png)

**Comment by mikeveeckmans** [comment]
Conflicting CSS in between hika and jdotorgtemplate.
@Joomv @Sandra97 : would it be possible to have a look at it?

**Comment by Sandra97** [comment]
It seems I don't have access to the CSS file anymore.

@Joomv, maybe you can try something like this:
`.contentpane #hikashop_address_form_span_iframe input.btn {
  border-radius: 0;
  color: #fff!important;
  padding: 7px 40px;
  background: #1b63a2; 
  border:none
}
`
Blue background for the button so that it's more visible, text so needs to be white, but as Hikashop used an !important, no other solution than adding one.

Result: 
![1](https://cloud.githubusercontent.com/assets/4682328/18179370/1b220452-7050-11e6-8669-ef74ff98e4fe.png)

**Comment by Joomv** [comment]
I will sort you out some access when I get home





On Thu, Sep 1, 2016 at 7:27 PM +0100, "Sandra Thevenet" <notifications@github.com> wrote:












It seems I don't have access to the CSS file anymore.



@Joomv, maybe you can try something like this:

.contentpane #hikashop_address_form_span_iframe input.btn {

  border-radius: 0;

  color: #fff!important;

  padding: 7px 40px;

  background: #1b63a2; 

  border:none

}



Blue background for the button so that it's more visible, text so needs to be white, but as Hikashop used an !important, no other solution than adding one.



Result:

**Comment by Sandra97** [comment]
You don't have to. If you're ok with my button, just copy paste my code. 
The less people has large access, the better it is ;)
 
Sandra 
 
De : Rowan Hoskyns Abrahall [mailto:notifications@github.com] 
Envoyé : jeudi 1 septembre 2016 14:29
À : joomla/joomla-websites
Cc : Sandra Thevenet; Mention
Objet : Re: [joomla/joomla-websites] [jshop] the adress popup has a smal `Ok` button (#519)
 


I will sort you out some access when I get home





On Thu, Sep 1, 2016 at 7:27 PM +0100, "Sandra Thevenet" < <mailto:notifications@github.com> notifications@github.com> wrote:












It seems I don't have access to the CSS file anymore.



@Joomv, maybe you can try something like this:

.contentpane #hikashop_address_form_span_iframe input.btn {

border-radius: 0;

color: #fff!important;

padding: 7px 40px;

background: #1b63a2; 

border:none

}



Blue background for the button so that it's more visible, text so needs to be white, but as Hikashop used an !important, no other solution than adding one.



Result:

**Comment by mikeveeckmans** [comment]
CSS in custom , works perfect ! 
Thank you @Sandra97 & @Joomv
