### ISSUE TITLE
[jorg] Joomla Core Features Clound Storage API & Webservice

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#545]
https://www.joomla.org/core-features.html

![image](https://cloud.githubusercontent.com/assets/2596554/18126989/09740b42-6f7e-11e6-97e8-fa83912a6e8a.png)

The last i know is that the Clound storage API is not implemented in core (just as external API) and the Webservice API is still under development?.

CloudStorage API https://github.com/joomla-extensions/Joomla-Cloud-Storage-APIs

Webservice API: https://docs.joomla.org/Web_Services_Working_Group

**Comment by MATsxm** [comment]
@mikeveeckmans thanks to check for the content

**Comment by mbabker** [comment]
Cloud should just be removed and that repo sent to `/dev/null`.  There's no interest in ever getting that GSoC project in a releasable state and it was already decided that code will not be merged to the CMS.  And from a Framework perspective, no value there; send users to Flysystem instead of reinventing another wheel.

Web services won't be merged to core either in the current project's shape, it'll be all opt-in code.  So if we're calling that page "features that ship with the download you get from `joomla.org`" it needs to be removed too (and any references to weblinks and Install from Web as features).  If we're only listing stable features, web services needs to go.

**Comment by Sandra97** [comment]
Cloud Storage APIs and Web Services removed from the page.
Closing this issue.
Re-open if needed.

**Comment by zero-24** [comment]
Thanks
