### ISSUE TITLE
[jshow] Crop messaging hiccup

### ISSUE THREAD

**Issue by AlisonAMG** [joomla/joomla-websites#549]
I just tested out the new Joomla Showcase. 

I uploaded images sized exactly to spec but still got the message cropping was required. 

NB: I did a search for submissions from Canada and version 3 and it took several minutes to complete.

**Comment by sebastienlapoux** [comment]
Hi Alison,
Thanks to test again. Please delete your navigator cache before.

**Comment by AlisonAMG** [comment]
Hi Sebastien

I tested the search and it works quickly and perfectly now. 

I loaded another site (CanadaScreens) and again sized my images exactly to spec and again the message of cropping required. (as attached image) 
![crop](https://cloud.githubusercontent.com/assets/3825882/18489675/8133610c-79cc-11e6-8dd9-dbebcd11b22e.JPG)

Thanks again for your attention to this. 
Alison

**Comment by MATsxm** [comment]
Thanks
Closing - reopen if needed

**Comment by AlisonAMG** [comment]
It isn't closed Mark. The issue is not corrected.

**Comment by sebastienlapoux** [comment]
Thanks Alison for your feedback.
Currently it's working like this. The error message after cropped is not disappear but you can submit your form correctly and after submission the message is no more displayed.

It's an enhancement that we will plan but it's very complex because lot of JS scripts here and we need to add some with AJAX only for this.

Currently you're the only person to have speak about this.

Thanks again Alison!

**Comment by AlisonAMG** [comment]
Hi Sebastien

Very well. Do you not think this will confuse users when they are trying to use the system to upload their projects? I was concerned that this would be a pit of email notices from users afraid they couldn't move forward. 

Thank you for your reply. 
Alison

**Comment by sebastienlapoux** [comment]
Hi Alison,

Not currently. If it's the case we will speed up this enhancement.

Thanks again for your participation.

**Comment by lionelratel** [comment]
Alison,
this is not a malfunction.

Currently, the choice of operation is as follows:
When a user uploads images, it is obliged to resize its images as we believe that in 95% of cases the images will not fit the right sizes.

Indeed, an improvement could be to control whether the image is the right size and in this case does not display the message.

For now, we have improved the help message that is under the pictures.
<img width="582" alt="capture d ecran 2016-09-14 a 18 39 05" src="https://cloud.githubusercontent.com/assets/9533292/18521573/e4d635c8-7aac-11e6-8396-ed840f4fb91a.png">


If we receive lot of returns on this, we'll look on this enhancement.

Lionel

**Comment by sebastienlapoux** [comment]
Thanks @lionelratel .
@AlisonAMG sorry for this misunderstanding. Contrary about what I said, the crop message is no more displayed after you cropped. So working nicely.
Like Lionel said the fact that you need to crop even if your picture match exactly the right size is not an issue. Working correctly here too. Currently you're the only person to have submit the exact size of pictures. It will be not the common behaviour. That's why we decided to add crop feature to the new site... to do this easily online.

Thanks to close this issue.

**Comment by AlisonAMG** [comment]
Good morning Sebastien

Thank you for the first laugh out loud of the morning. First person to upload the correct size. OMG

Have a good day/evening
