### ISSUE TITLE
[jshop] back button on order detail view throws an JS error

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#558]
back button on the order detail view throws an JS error:
![image](https://cloud.githubusercontent.com/assets/2596554/18181764/1c385598-708d-11e6-8ee8-41bf80c5833c.png)

**Comment by hikashop-nicolas** [comment]
Hi,

For some reason the core.js file of Joomla is not loaded on that page and it is necessary for the button.

Edit the file "show" of the view "order" via the menu Display>Views of HikaShop in the backend and add the line:
<?php JHTML::script('system/core.js',false,true); ?>
at the top and that will fix the problem.

We'll add a proper modification in HikaShop in order to avoid that.

**Comment by mikeveeckmans** [comment]
Fixed, thank you @hikashop-nicolas .
