### ISSUE TITLE
[jdown] [RFC] "Release FAQs" link

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#598]
Should we add the "Release FAQs" link to the documentation for each release?

![jdown6](https://cloud.githubusercontent.com/assets/733133/18534319/2b08acb4-7aea-11e6-8b7f-a636c6b3e924.PNG)

We generally link to a FAQs page in the release announcement, even if the docs page is empty:

![faq362](https://cloud.githubusercontent.com/assets/733133/18534345/56b2b86e-7aea-11e6-8afa-6600a45cb9f3.PNG)

Sample: https://www.joomla.org/announcements/release-news/5667-joomla-3-6-2-released.html
FAQs: https://docs.joomla.org/Category:Version_3.6.2_FAQ

**Comment by mbabker** [comment]
If you can ensure this page exists with the same formatting for all 126 releases then sure.  The announcement URL is a field in the backend so that's not being auto-generated, and I don't think we need to add another field for that personally.

Not to mention the FAQ is linked from all announcements.  So it is indirectly available already.

**Comment by jeckodevelopment** [comment]
Thank you!
Re-thinking about that, if the FAQs page is empty, linking that is unuseful, and as stated before, it's linked in the release announcement.

Closing.
