### ISSUE TITLE
[jdown] Last release why only full install

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#608]
On this page:
![image](https://cloud.githubusercontent.com/assets/2596554/18543693/662fc038-7b31-11e6-8804-ebdf74363458.png)

We have only the full packages. why do we not add the update packages also?

And why is the most common download (zip) at the end of the list?

**Comment by mbabker** [comment]
The reversed ordering looks like a bug in ARS.  I'll get that fixed and pushed upstream later.

We made an explicit decision to only list the full package on the latest release page since presumably the majority of users visiting the site will need these more than the upgrade packages.  It's just a match in the layout file on whether the title contains "Full Download" so nothing too special.

**Comment by zero-24** [comment]
:+1:

**Comment by mbabker** [comment]
Upstream fix has been merged and the options for all 12 menu items have been painfully updated.
