### ISSUE TITLE
[jdown] Dokumentation

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#609]
![image](https://cloud.githubusercontent.com/assets/2596554/18543974/bed2885a-7b32-11e6-974b-f93afdbfc3e8.png)

hmm I'm not sure. On the most sites we use the word `FAQs` and not Dokumentation. So why this is `Dokumenation` and not `FAQs`? 

Also I'm not sure about the link to the `Technical Requirements` as it is also in the top navi?

**Comment by MATsxm** [comment]
- Agree for the use of the FAQs only
- Disagree for the BTN as it is a specific access from a dedicated page

**Comment by Sandra97** [comment]
For this one, I agree with the guy who is officially my husband ;)

**Comment by jeckodevelopment** [comment]
happy to see that you are a lovely couple :smile: 

BTW, i agree on the FAQs

**Comment by MATsxm** [comment]
- `Joomla! Frequently Asked Questions` instead of `Joomla! Downloads Documentation & Frequently Asked Questions` for the article.
_Note that only the source content en-GB is up to date and will be pushed for t9n in the next few days_
- Menu `FAQs` instead of `Documentation`
Strings for t9n pushed on Crowdin

Closing - Reopen if needed
Thanks
