### ISSUE TITLE
[jrepo] Design issues with viewports > 1920px

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-websites#66]
The j.org test site looks quite weird on viewports larger than 1920px; the background-graphics end in the middle of nowhere, not sure if this is intended or not.
![voila_capture 2015-08-26_12-12-53_nachm](https://cloud.githubusercontent.com/assets/498096/9490955/e19c3f4c-4beb-11e5-93f0-49650b038bc1.png)

**Comment by Sandra97** [comment]
On the principle, I fully agree with you. 
But note that it's just an upgrade, not a redesign of the website, which is the mission of an other team. That's why the original image has been kept.

**Comment by SniperSister** [comment]
It worked fine on the old site, seems to be related to the adjustments done to make it responsive

**Comment by Sandra97** [comment]
There is no module position for full width on the template and as it's a temporary website we'll not add a new module position. The redesign of the template is the mission of a.n other team.

**Comment by JacquesR** [comment]
I think the issue is not that the graphics end at a certain width, but that it stretches out the content area too wide in the new template. See for example the Glip announcement page (or any text-heavy page).
Apply a max-width to the .body class (or where appropriate) of 1170px (or a bit wider if you wish), to match the navbar .container, and the content is tighter and easier to read.
The front-page also looks better with at that max width.
Remove the 1920px max-width from .body.site.fluid so the color bars are full width (that should help sort the issue @SniperSister mentions)

I know this is not meant to be a redesign, but the current new max-width is a regression since it makes the content more difficult to read (and looks worse than the old width)

**Comment by Sandra97** [comment]
Applying a width of 1170px to the homepage breaks the desired. But it's possible to keep the current width to the homepage only, and a width of 1170px for all other pages.

**Comment by MAT978** [comment]
disagree but maybe because I'm no more living in the late 00's ;)

**Comment by Sandra97** [comment]
A max-width of 1170px has been applied to all the inner pages.
Thanks.
Re-open is needed.
