### ISSUE TITLE
[jdown] Suggestion to merge all file types in one box

### ISSUE THREAD

**Issue by ITPrism** [joomla/joomla-websites#661]
The site looks wonderful. I like it.
However, there is something that burdens me when I scroll through the pages with different file types and updates.
There are too much information and elements on the page.
What do you think if you merge the file types in one box?

![file_formats](https://cloud.githubusercontent.com/assets/1272206/18879363/abb4e552-84dc-11e6-9f45-9c691b97d57d.png)

**Comment by mbabker** [comment]
One thing I will agree massively on is there is a lot of dead space that
could be more efficiently used.  Without adding more options into ARS
though I'm not so sure how many changes to the layouts we can make and keep
things efficient.  Conceptually I like where this is going but it's still
something to think about for the moment (and the long scrolling does get
worse the deeper you go; our largest release has 71 items).

**Comment by mbabker** [comment]
So on some very rough testing, my first impression is this isn't going to scale well for smaller devices.

This first screenshot is pretty similar to your mockup but even on a 1440px display we're already having text overflow issues without adjusting the font sizes (and we already run a pretty small base font).

<img width="1440" alt="screen shot 2016-09-29 at 9 34 54 am" src="https://cloud.githubusercontent.com/assets/368545/18958549/8dc1fed4-8628-11e6-84e5-59ed831c8405.png">

So if I turn off the `dl-horizontal` class it gets a little better, but again when we start getting into smaller viewports it starts overflowing (this screenshot is at 979px which is the largest width on that viewport).
<img width="979" alt="screen shot 2016-09-29 at 9 38 00 am" src="https://cloud.githubusercontent.com/assets/368545/18958555/8f97e1ce-8628-11e6-8de6-43620eb43405.png">

Even wrapping the signatures in `<small>` tags (which is an 11px font on our template) it's still overflowing on smaller devices.

So someone with better design skill might need to build up good mockups I can convert into the layouts to make this work, but at a quick glance, unfortunately I'm finding a lot of small quirks making this less desirable for the moment.

**Comment by Sandra97** [comment]
No need to change the font size. I can correct the overflow for the signature codes thanks to a `word-break:break-all`, if it's ok for you to display the signature code on 2/3 lines depending on the screen resolution (and if you're ok, would be nice to createa a specific class for the 2 related `<dd>` tags).

**Comment by mbabker** [comment]
It's one long string though, I don't think it's right necessarily to break that string across multiple lines.  Then again, I'm always the last person who should be giving design related advice.

**Comment by Sandra97** [comment]
Honestly, I think we should keep it like it is currently. 
We should just break that string for screens under 480px in order to not have any horizontal scrolling.

**Comment by ITPrism** [comment]
I am attaching a code that you can try. 
[full_download.zip](https://github.com/joomla/joomla-websites/files/501082/full_download.zip)

![html](https://cloud.githubusercontent.com/assets/1272206/18960834/b864d90e-8673-11e6-918c-3e48ad22c473.jpg)

**Comment by ITPrism** [comment]
I removed the property text-align in **.dl-horizontal dt** and changed the **width to 100px.**
I changed margin-left to 100px  in **.dl-horizontal dd**.

![dt](https://cloud.githubusercontent.com/assets/1272206/18961016/49eb1820-8674-11e6-8f89-f1a5dcb99200.jpg)

![dd](https://cloud.githubusercontent.com/assets/1272206/18961024/4da0e42c-8674-11e6-904b-d4501eb72253.jpg)

**Comment by ITPrism** [comment]
I did SHA1 Signature **font-size: 11px**;
![sha1-signature](https://cloud.githubusercontent.com/assets/1272206/18961184/d1230140-8674-11e6-85c5-d475cf81b789.jpg)

**Comment by mbabker** [comment]
It's fine at wider views with the smaller font on the signatures.  And a little better when you don't make the list horizontal.  The main issue is getting it to render well at the smaller viewport.  The 768-979 viewport has a massive overflow (the tailing 5 or 6 characters of the MD5 get covered by the next block over and the SHA1 even longer, even with 11px font) and for 980-1199 it's still there but less noticeable.  The 767 and under viewport is pretty OK too since at that point the spans are all full width.

**Comment by ITPrism** [comment]
You can hide signatures with  class="hidden-phone" on the phones.
![phone](https://cloud.githubusercontent.com/assets/1272206/18961476/e018c8be-8675-11e6-8c73-29f1e5375909.jpg)

**Comment by sanderpotjer** [comment]
What about showing the signatures in a readonly input field? Wont break the responsive layout and makes it also easy to copy.

**Comment by mbabker** [comment]
1) Is that valid HTML structure? (Serious question, some days I feel lucky enough to use Bootstrap's grid, let alone understand what can be nested where)

2) Would we need to make clear somehow the hash is longer than the input?

<img width="470" alt="screen shot 2016-09-29 at 2 23 09 pm" src="https://cloud.githubusercontent.com/assets/368545/18968890/7f761db0-8650-11e6-946b-638d27fae385.png">

**Comment by mbabker** [comment]
This is something I think we can revisit after launch.  With our current releases the current one item per row layout isn't too terrible (the container ends at ~3750 pixels from the top of the page for reference on the 2.5 and 3.x releases; 1.0 and 1.5 can get excessively long due to the old packaging processes) and implementing this is a little trickier than just editing the layout files (we'd have to do a lot of extra filtering on the FOF DataModel collections the layouts work with to get the row layout correct), and as pointed out there are some responsive issues to cope with.

I do agree there is perhaps a lot of whitespace (and dead space) on these pages now, but there is also a part of me that thinks maybe collapsing it in this way might actually worsen usability a bit by cramming everything into a smaller space (remember I'm the last person who should be giving UI related advice so take this part as nothing more than a personal opinion).  So overall there are ways we can look to improve things, right now though at least for the next few weeks I think I'd rather focus more on architecture stability and having a smooth transition when the site launches over "nice to have" UI improvements.

**Comment by conconnl** [comment]
[Closed] - No response after a long period and the website looks currently different then in the screenshots.
