### ISSUE TITLE
[jdown] rename "Joomla! 3.6.2 Full Download (.zip)" to "Joomla! 3.6.2 Full Package (.zip)"

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-websites#664]
when you click on "Upgrade packages" you go to https://downloads.joomla.org/cms/joomla3/3-6-2
here I suggest for consistency to rename "Joomla! 3.6.2 Full Download (.zip)" to "Joomla! 3.6.2 Full Package (.zip)" and other full packages...

**Comment by joo7** [comment]
or "Joomla! 3.6.2 Full Package Download (.zip)" ?

**Comment by mbabker** [comment]
If we're going to change names it'll be done once and once only because
that means rebuilding the database and fixing all layouts using these
titles in conditional logic.  I'm not particularly concerned with what the
end result is but I don't want us changing it more than once.

That said, I actually find "full package download" rather verbose.
Truthfully I find the existing names to work fine, I don't think the titles
need to explicitly say package in them.  And the one that uses package IMO
sounds funny as "upgrade download".

**Comment by mbabker** [comment]
Backing up a bit.  The file names are all packages.  So maybe we just
replace download with package I guess.

**Comment by MATsxm** [comment]
... I will miss our "download with success" :stuck_out_tongue_winking_eye:

**Comment by mbabker** [comment]
Titles changed.  Closing.
