### ISSUE TITLE
[jdev] Nightly Builds are not up-to-date

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#678]
![image](https://cloud.githubusercontent.com/assets/2596554/19035495/070d2b62-896a-11e6-9570-b8a4101876e1.png)

Today is the 03.10.2016 maybe the job needs restarting?

**Comment by mbabker** [comment]
Nope.  It's fine.  http://build.joomla.org/job/cms_nightly/scmPollLog/

Maybe the job config needs tweaking right now but it only builds based on whether there have been changes in the staging branch, and as it says on the polling log right now there weren't any so the job didn't run.  It's always been that way.

**Comment by zero-24** [comment]
Yes but the 3.7.x and the 4.0 branche had updates :)

**Comment by zero-24** [comment]
hmm i guess we should always run the script on all branches as there are just a few cases where there is no commit per day or do we have reasons to not rebuild it?

Or we check per branch the `changes since last build`

**Comment by mbabker** [comment]
It's the way the Jenkins job is configured, it only polls the staging branch.  In part because I don't know if telling it to poll all 3 branches will cause it to run the job 3 times (once per polled branch).  Either way if the job needs reconfigured then someone with more free time than me needs to look into it.  Right now it's functioning as designed.

**Comment by zero-24** [comment]
ok. Thanks.
