### ISSUE TITLE
[jshow] typos/grammar

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#692]
https://showcase.joomla.org/browse-sites/16717.html

**Description:** **Its** a public club about ...

**It is** or **It's**

**Case Study**

"The goal was to create a easy to use website für the members of the club to publish their stories and events. "

The goal is to create an easy-to-use website for the members of the Club to publish their stories and events.

**Comment by mbabker** [comment]
Your last two items are user content.  Is the review process including grammar checks?  (I guess the same could/should be asked for the other directories).

**Comment by Hils** [comment]
This is the Joomla Showcase with a team - surely the team should allocate people to check these entries?

**Comment by mbabker** [comment]
Well most of the showcase team aren't native English speakers either, assuming https://volunteers.joomla.org/teams/site-showcase-team is accurate it looks like 3 of the members (who aren't primary moderators) are the only native speakers.

And again, the same issue is most likely going to exist with the other directories.  IMO this isn't an issue localized to the showcase; JED, JRD, and the volunteer portal are going to have issues with improper English because the content is coming direct from the users.  And I wouldn't suggest delaying publishing listings to get the English right, especially if the team has few native speakers.

**Comment by sebastienlapoux** [comment]
Yes, it has been never the rule of site moderators to correct english description of submitted site. And in regards of the number of site submissions I don't see any solution to resolve this.
Any idea is welcome.

**Comment by genr8r** [comment]
If it helps... the JRD requires submissions to be in English, but we have not been grammar checking prior to approval.

**Comment by sebastienlapoux** [comment]
@Hils just for your pleasure I fixed the english issues that you highlight.

**Comment by Hils** [comment]
aww thank you! and don't worry, I just did two at random :)
