### ISSUE TITLE
[jshop] Shipping Price

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#703]
My issue is that it costs €12.62 to ship €4 worth of stickers to the UK. 

**This is a complete rip off.**

I often post myJoomla.com stickers from UK to the USA and that costs £1.57
I often post myJoomla.com stickers from UK to Europe and that costs £1.38

![screen shot 2016-10-06 at 16 02 31](https://cloud.githubusercontent.com/assets/400092/19157919/c589ec58-8bde-11e6-83c8-eae58a21404a.png)

**Comment by brianteeman** [comment]
IIRC thats because its the minimum charge of the carrier. @mikeveeckmans was going to look at a different way of mailing (not shipping) orders of just labels - for now its really only appropriate to purchase the stickers as an add-on to an existing order

**Comment by mikeveeckmans** [comment]
Hi @PhilETaylor ,
I understand, at this point that's one of the disdavantages of the shipping API. We're pushing Bpost to change it.
As soon as we have an update on this i'll notify you.

**Comment by StefanSTS** [comment]
Hi,
there is a bug in the shipment calculation. I tried to order from India. The 30 Euros shipping is steep too, but it is not the bug, it is the pleasant surprise, that in the next step it is reduced to 0,40 Euros (30 INR). So somehow the currency calculation is off.
First after adding the shipping, the cart was stuck, checkout button was not working. Then I changed the number of shirts from 1 to 2 and the cart reloaded and two shipping options came up.
Choosing Paypal I was redirected to Paypal, but got an error message, most probably, because the proper total was different from the Paypal total, which was 35,40 Euro for two shirts with shipping. Should have been 65,00, if shipping is 30 Euros.

**Comment by mikeveeckmans** [comment]
@StefanSTS thank you for reporting we'll check it.

**Comment by mikeveeckmans** [comment]
@StefanSTS could you retry? thank you.

**Comment by StefanSTS** [comment]
@mikeveeckmans Prices are shown now in Euro instead of INR, which is fine. So order goes all the way to Paypal, which I cancelled then. All good. I will order, once you have a local retailer in India. ;-)

Selecting the payment is not very user friendly though. Choosing the payment is on top, below you see comparably small which payment you have chosen. That should be all in one area which you directly see.
Going as a dumb user, I just clicked finish without choosing a payment, credit card was selected, but I wanted Paypal. There was no way back via button, so I pressed the browser back button. I expected to go back to the cart, but I went back to the shop. Pressing the cart button now, the cart was empty and I had to choose the shirt again.
I would expect a back button to choose my payment again, or at least the product should stay in the cart. Since the process was probably already finished without the payment done, the cart was empty.
So to keep these things from happening, it would be good to clearly see your chosen payment. 
Having the upper choices as buttons that would show an active status, if a payment is chosen would be better than having the small indicator below the cart.
Hope I could make myself understandable. ,-)

Good going
Stefan

**Comment by StefanSTS** [comment]
One more thing from my experience, if you enable the email verification for adding an account, the cart abandonment is much higher than if you keep that off. I does not happen too often that the email is given wrong and the important thing for selling is not the email, but the postal address which is presumably right or the postal office will make it right.

**Comment by PhilETaylor** [comment]
I no longer need this fixed for me, so feel free to close this - or keep it open and fi the problem 

I'm all for financially supporting the project, however I refuse to be ripped of.

I bought my stickers, with £1.63 shipping (correct price) at https://www.redbubble.com/

see: 

![screen shot 2016-10-09 at 13 34 21](https://cloud.githubusercontent.com/assets/400092/19220451/440a23f2-8e25-11e6-877c-25e5ce9210dd.png)

**Comment by Sandra97** [comment]
As the Shop is closed since the end of 2016, I'm closing this issue.
Note that the creation of a team for the Shop as well as the correct management of the shipping rates are on the marketing team todo list. So it should be fixed, one day or another ;)
