### ISSUE TITLE
[jshop] Product spacing not correct on first page load (Firefox)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-websites#724]
On Firefox, when you visit the Shop page for the first time, or hard refresh, a height (`124px`) is being applied to the product thumbnail:

```
<div class="hikashop_subcontainer thumbnail" style="height: 124px;">
```

resulting in the following:

![screeny](https://cloud.githubusercontent.com/assets/2019801/19560015/8af549ec-96ca-11e6-9e4d-7c59eb7bf055.png)

If you perform a standard refresh, the inline height is no longer applied.

Having looked though the `hikashop.js` file, the height is being set on line **805**

**Comment by mikeveeckmans** [comment]
pinged hikashop on this.

**Comment by hikashop-nicolas** [comment]
Hi,

The problem comes from an optimization which results on the images being loaded too late and the script which set the height of the elements has already been calculated.
Change the line:
this.setConsistencyHeight(elems);
to:
this.setConsistencyHeight(elems, 'min');
in media/com_hikashop/js/hikahop.js and that should prevent that issue by setting the minimum height of the div, instead of forcing the height.

**Comment by Joomv** [comment]
Can you check now please? @C-Lodder

**Comment by C-Lodder** [comment]
Working now. Thanks

**Comment by mikeveeckmans** [comment]
Thank you @C-Lodder @Joomv @hikashop-nicolas
