### ISSUE TITLE
[joomla.org] how to get automatic security update emails?

### ISSUE THREAD

**Issue by agreif** [joomla/joomla-websites#732]
Hi,
I am subscribed to Feedburner “Joomla! Security News” mailing list.
In former times I got emails from there, but nowadays no emails are sent. Especially for 3.6.4 no Email came. It seems that Feedburner is not working the expected way.

What is the best way to get notified about security update announcements via email?

thanks,
Alex.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by agreif** [comment]
the email just came.
OK, so the mailing list seems to work. I only ask myself why this security news comes so late.... almost one day too late!! Security news should be sent immediately IMO.

Alex.

**Comment by zero-24** [comment]
>OK, so the mailing list seems to work. I only ask myself why this security news comes so late.... almost one day too late!! Security news should be sent immediately IMO.

That mail that you got was the pre release notice that points to https://developer.joomla.org/security-centre.html

As this contains some more info than just "there is a sec issue" it is released by the JSST after the release.

If you want to get a mail on new joomla release and also sec release pre news you can suscribe here: http://feeds.joomla.org/JoomlaAnnouncements

**Comment by mbabker** [comment]
If a message went out for the pre-release it was from another feed for .org itself.  That article wasn't distro'ed through the security feed because it's not in the security center on the dev site.

Those notices were published yesterday at the same time as the release.  Feedburner just has a major lag in sending mail I guess.

The main point here is that Feedburner is slow from the time it picks up new articles from the security center's RSS (published 24 hours ago now) to the time it sends email notifications on that.  It should definitely be much quicker, for all feeds in general.
