### ISSUE TITLE
[docs.joomla.org] special chars in url/title

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#733]
google for 

Joomla How do you redirect users after a successful login

You get this as the first link:

https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F

This link works while the %3F is in the url

Email this link to someone, yourself, whoever, most mail clients then change the link when clicked to 

https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login?

and when clicked this url leads to a blank wiki page

For now I have edited the blank page to provide a link to the real page, but the correct solution is to prevent/stop/clean special url chars from the titles of pages.

**Comment by Hutchy68** [comment]
I can't replicate the issue when emailing between gmail, Outlook, nor an iphone email's client.

https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F

That said, I know it can occur because the client is outputting the ? instead of the %3F. I have seen in the past on occasional, mainly in forum posts. Yes, the correct method would be stripping the special chars from the title pages, but the FAQs were created as questions and are now well established. The work around is a redirect. I have fixed your created page to show it and it now works to take you to the proper page. Try it below with this link.

[https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login?](https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login?)

**Comment by PhilETaylor** [comment]
When GH emailed me your reply, I clicked on both links - and both links worked for me this time - thanks. 

Im guessing there are a lot of others with a ? at the end of a question. :-(
