### ISSUE TITLE
We are not showing advertising on www.joomla.org

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#845]
I understand that we have decided not to show banner ads on the homepage of www.joomla.org but we should be showing banner ads on the sub pages such as:

- https://www.joomla.org/core-features.html
- https://www.joomla.org/3/
- https://www.joomla.org/announcements.html
- Etc.

I can create the zones we need on the ad server, once we have agreed where the banners should be. 

It could be a simple 728 x 90 banner at the bottom or a 300 x 250 banner somewhere or even our special 270 x 225 banner.

Please let me know who can implement and what zones we should have.

**Comment by MATsxm** [comment]
> but we should be showing banner ads on the sub pages
who said that? :wink:

**Comment by mbabker** [comment]
As much as I agree we should be trying to place advertisements, let's not make it a "ads on all the pages" thing please.  There's a difference between strategically placed and bombarding users.

**Comment by MATsxm** [comment]
don't think /3 should be
just MHO

**Comment by franz-wohlkoenig** [comment]
if Joomla need Money, do it.

**Comment by mbabker** [comment]
We definitely should place ads, I'm not saying don't (ask MAT & Sandra who was the one pushing to get the advertising stuff sorted before launching the downloads site).  I just don't want the Joomla properties to turn into some of those sites we use as examples of how not to do advertising because ads are displayed anywhere and everywhere.  One or two spots on carefully selected pages, or a generic sidebar slot for some of the sites, is more than enough.

Landing pages like the Framework site's homepage or the /3 site IMO should be left "clean", their purpose is to advertise OUR software, not be a selling spot for someone else too.  Same for the .org homepage itself.  For me, I welcome the discussion for every other page on the network.

**Comment by MATsxm** [comment]
@franz-wohlkoenig not because I need money I will do anything especially in a project driver by a community...

**Comment by franz-wohlkoenig** [comment]
@MATsxm d'accord. Meant Money for Tickets, so People can get on a Conference.

**Comment by aDaneInSpain** [comment]
OK, I agree that maybe /3/ should not have ads. But https://www.joomla.org/announcements.html - there could easily be a banner in the right hand column. And there are other pages I am sure.

I totally agree that we should not plaster ads everywhere, but a simple banner in the right hand column or at the end of content (or both) is not that bad, and they help pay for everything.

**Comment by Joomv** [comment]
I have already clearly stated my view on this.  
.org should NOT serve advertising nor should any of our release sites. They advertise US and that's all they should do.
Also given the quality of ads served at the moment compared to the extremely small income stream, just because its a high traffic page and might bring us in a couple of thousand a year, is that worth it for losing trust in our brand and ethos?  I personally don't think so.

**Comment by aDaneInSpain** [comment]
I did not know that you meant **all** pages under www.joomla.org I thought that you just meant the homepage. If the general consensus is that we should not have ads on any pages on www.joomla.org I am fine with that and will stop chasing it. To be honest, I was not thinking about it. Was just on autopilot trying to get ads served on every page.

Looking forward to hearing more peoples' thoughts.

**Comment by Sandra97** [comment]
As this discussion is quite old, and we don't/won't display ads on jorg, I'm closing this issue.
