### ISSUE TITLE
[jhelp] Clicking on help brings up RuntimeException in new browser pop-up 

### ISSUE THREAD

**Issue by efduggan** [joomla/joomla-websites#852]
Using the 3.7 beta 3 I clicked on the help button:
![where to click](https://cloud.githubusercontent.com/assets/25716272/23031283/4652e3d6-f425-11e6-8f5b-6db19c0ff940.png)

 A pop-up appeared with RuntimeException

![runtime exception](https://cloud.githubusercontent.com/assets/25716272/23031310/6224f5f4-f425-11e6-82ff-fc9ddd9caa30.png)

While I realize the 3.7 help isn't published yet, since 3.7 hasn't been released. (Assuming it goes live with a release candidate.)

There are two issues with this behaviour:

1) The error message makes the missing help seem more "tragic" than it really is.

2) There should be a link to some documentation so that the user can get help - perhaps link in the 3.6 docs (if the section exist) or present a better message that no help is currently available for this version.

**Comment by mbabker** [comment]
The help system isn't that "smart" unfortunately.  The app is just reading the Mediawiki API looking for the page it was asked for, there isn't any "sorry this doesn't exist but perhaps you meant this" type of response from the API to do this and any type of "change the HelpXX URL key" logic is just going to be arbitrary at best.

Honestly the best we could probably do is improve the error page (https://github.com/joomla/help.joomla.org/blob/master/templates/helpscreen/exception.html.php) otherwise we're dealing with limitations of the Mediawiki API.

**Comment by Hutchy68** [comment]
I'll create an alias to the namespace and it should work without error, I'll ping you when I get it set.

**Comment by Hutchy68** [comment]
@efduggan Try it now. It should work without the error.

**Comment by franz-wohlkoenig** [comment]
@Hutchy68 works, thanks.

**Comment by Hutchy68** [comment]
Awesome! Closing as fixed.

**Comment by efduggan** [comment]
Hi,

 I've also given it a spin and see that I get the help documentation. Thanks to everyone for addressing this issue!
