### ISSUE TITLE
[josm] [DISCUSSION] - interest of keeping the OSM site alive?

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#885]
We all know that maintaining a site is an expenditure of energy and time not negligible and which, following our philosophy of volunteerism are two things of great value we can not waste.

Now that we are back to the first "vocation" of OSM to hold and protect the name Joomla! (not a decision board), I think that the site http://opensourcematters.org/  is no more intended to exist or if this is the case, a simple page would be enough, even more that this site contains many duplicate content.

The number of visits is not significative and the only original and useful information on it can be widely supported, and with more visibility, on joomla.org

**Comment by jeckodevelopment** [comment]
We must keep the "domain name" and at least one page including all the needed information and references for legal reasons.
By the way, this item will be discussed at the first Board Meeting.
Be sure that i don't want to do double work :)

**Comment by MATsxm** [comment]
> this item will be discussed at the first Board Meeting.

Great thanks

I'm really curious to know where, it is writtent that legal stuff **MUST** be on a specific (who and what are criteria to decides the domain name?) domain name that **MUST** be `opensourcematters.org` and that the legal info "needed" (thanks for the text for the legal mentions) can't be on a "legal section" on org?

Anyway, if someone can proove me there's no other choice as they are legal requirements... let's go for a one page...

**Comment by jeckodevelopment** [comment]
will do MAT.
I have to go through a lot of documents :)

**Comment by Joomv** [comment]
Work has been done to remove the duplicated content.  Those links now point to the main sources on other properties.  The offering on the site has been significantly scaled down with prominent signposting to .org throughout.

Liaison is needed with TM on the remaining legal items.  Minutes and News now point to other sources and are in archive mode.  This is a start.

**Comment by jeckodevelopment** [comment]
Thank you Rowan

**Comment by Joomv** [comment]
I was thinking about this overnight.  With the site trimmed down and providing either archives or links to the proper content.  I think this is pretty much there apart from some wording needs attention.
I think we should keep the by-laws, financial filings and policy on this site.  I personally have secured discounts and other incentives by directing potential partners to those pages.  When we're asking for something that involves an agreement or contract, we're asking as OSM because it "exists" - having these documents on the OSM site goes some way to giving a level of perceived "credibility" when it comes to these things.

**Comment by Sandra97** [comment]
As Rowan made a big cleaning and update of the site, I presume we can close this issue.
Re-open if needed.

**Comment by MATsxm** [comment]
never mind @jeckodevelopment...
still waiting for
https://github.com/joomla/joomla-websites/issues/885#issuecomment-285860488
