### ISSUE TITLE
[joomla.org] Team News

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#905]
On the Joomla.org home page select News
At the bottom you will see links to three categories

<img width="576" alt="screenshotr11-30-48" src="https://cloud.githubusercontent.com/assets/1296369/24352293/e8aebf90-12e0-11e7-81d8-8bade21a9338.png">

The most recent article in the Team category is from **2008**

**Comment by Sandra97** [comment]
I know :(
One thing I could do would be to merge them into General News and manage the 404.
If anyone has a better suggestion, don't hesitate

**Comment by franz-wohlkoenig** [comment]
@Sandra97 the Split in 3 different Categories isn't neccessary.

**Comment by mbabker** [comment]
We can't just completely drop the three subcategories.  It would completely kill the rankings for .org to have that much content redirect.

The only person that was presumably around when the site was set up was Brian.  And at that point the team were using that area for personnel announcements.  Obviously the number of subdomains has blown up since then and that category isn't used anymore.  I tried archiving the category but it broke all of the links to the existing content, so that isn't an option.  It's either leave it there or completely drop that category.

**Comment by mbabker** [comment]
All of the articles are archived and the news menu item configured to not show empty subcategories, effectively hiding that category from navigation without breaking anything.

Considering this fixed.
