### ISSUE TITLE
[demo.joomla.org] read on + url rewriting -> 404

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-websites#959]
On demo-site https://demo.joomla.org/ click "Launch Test Drive", 
create new article, set featured,
in global config set url rewriting on,
on frontend click read on -> 404

related to https://github.com/joomla/joomla-cms/issues/15343 ?

**Comment by brianteeman** [comment]
no nothing to do with that - its because there is no .htaccess file created which if you look at the tooltip needs to be created BEFORE enabling that option
<img width="339" alt="screenshotr13-11-55" src="https://cloud.githubusercontent.com/assets/1296369/26353677/738b4fac-3fb9-11e7-99ea-1d751b897bfc.png">


@Sandra97 this can be closed but you might want to talk to SG aboout having the .htaccess in place to prevent reports like this

**Comment by Sandra97** [comment]
Thanks Brian. Yes, I'll see that with them.
Closing this issue.
Re-open if needed
