### ISSUE TITLE
[jrd] Resources Directory Listing Request

### ISSUE THREAD

**Issue by dcassone** [joomla/joomla-websites#965]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
I submitted a listing request in the Joomla Resources Directory in February 2017 and have heard nothing.
I submitted a couple of tickets requesting the status and they have gone unanswered, none are even assigned.
It could be useful to include an URL of evidence.
resources.joomla.org My name is Dom Cassone
Please use a consistent title for your issue.

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla-cms/issues/16539 for more infos.

**Comment by zero-24** [comment]
the last message was not for you @dcassone ;) It was for the JRD admin ;)

**Comment by genr8r** [comment]
Hi @dcassone. I have a user account for you in our system but am not seeing a listing application or any support requests in our system.
You can login and go here... https://resources.joomla.org/en/my-jrd-listing to apply for a listing.
Please also report any concerns about listings or the approval process to our ticket system at https://resources.joomla.org/en/help-desk (again after logging in). If you have technical problems with either if those processes feel free to open an issue here. Otherwise, this github account is really for addressing specific technical problems with the various Joomla properties.

**Comment by dcassone** [comment]
Hi,

I’m not sure where you are looking, or if I put it into the wrong area, but there is a listing listed in my account (djc1) for Zacaw Enterprises, Inc.

It was suggested to me that I contact this github because my listing has not been approved since February 

thank you for your reply!
Dom
