### ISSUE TITLE
[forum.joomla.org]  Impossible to connect

### ISSUE THREAD

**Issue by Django29** [joomla/joomla-websites#969]
Hi
On joomla.org, I can't loggin anymore.
The username and password are refused (same as I use on this forum).
In case I made a mistake on the password, I asked for an email to recover it : Username and/or email refused.
Then I tried to create another account, with another email. After 15mn, I haven't received any confirmation email.
Then I tried to connect by another login module (https://community.joomla.org/login.html) : it asks me a secret key ?????

It looks like this site doesn't want me.

**Comment by Sandra97** [comment]
Hi, 

Community and Forum are separate websites, so that's normal you can't log in cjo with your forum credentials.
joomla.org is not open to user registration, so it's normal you can't login. 

For forum.joomla.org, could you please fill the form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by Joomv** [comment]
Two Factor Authentication is enabled on CJO but it is optional.  All Super Users have it.  It is not required for registered users.

**Comment by Joomv** [comment]
I am closing this as no response from OP.
