### ISSUE TITLE
[jdocs] I can't edit this page https://docs.joomla.org/Security_Checklist/Hosting_and_Server_Setup

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#973]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.
https://docs.joomla.org/Security_Checklist/Hosting_and_Server_Setup
I want to edit the part that says **use PHP 5** and change it to PHP7.  If someone from the security team is better placed to do this then please forward my request.

**Comment by zero-24** [comment]
Confirmed. There are also 404 / 503 Links on that page. 😄

**Comment by zero-24** [comment]
looks like this is expected see: `temporary until JSST group is created ([Edit=Allow only administrators] (indefinite) [Move=Allow only administrators] (indefinite)))`
https://docs.joomla.org/index.php?title=Security_Checklist/Hosting_and_Server_Setup&action=history

I don't know if a JSST Group is created until that day.

**Comment by mbabker** [comment]
That entire page needs rewritten.  It's all geared toward Joomla! 1.5 at a quick glance.

**Comment by uglyeoin** [comment]
I think someone more technical than I is better placed to do this, but it is a useful doc that we should be signposting I think.  Unless there's another newer version?

**Comment by Sandra97** [comment]
The page hasn't been updated in the last 4 years. If it's completely out of date and if nobody can update it, we'll archive it.

**Comment by Hutchy68** [comment]
Lol it is or was under jsst. Then supposedly they moved to vel subdomain. I think Phil was supposed to be taking care of them because if any editor edited them a certain someone would freak out. 

At this point, 4 years later, I would say they are abandoned. As abandoned property it is subject to seizure if jsst will not do their job and keep them updated.

**Comment by mandville** [comment]
> Lol it is or was under jsst. Then supposedly they moved to vel subdomain
inaccurate i am afraid. **JSST** are still the JSST who deal with **CORE** at https://developer.joomla.org/security.html
The **VEL** on vel.joomla.org deal with **vulnerable extensions.** 

afaik Phild did work on it till he was asked to stop in prep' for updates re 2.5/3

**Comment by PhilETaylor** [comment]
Two people have alerted me to this thread now, so I'll reply

>  I think Phil was supposed to be taking care of them

To be clear, `Phil` doesnt mean @philetaylor here, it means, `[Phild](https://docs.joomla.org/User:Phild)` whoever that is! 

First I have heard of it. I dont *do* wiki's I hate them. 

>if any editor edited them a certain someone would freak out

If you mean me, I would only freak out when "idiots" pretend to be security experts. This happens daily on the Joomla Security Forums and elsewhere.

> As abandoned property it is subject to seizure if jsst will not do their job and keep them updated.

I don't believe the editing of Joomla Wiki is the job of the JSST. Its certainly not in the public remit. 

`The JSST operates with a limited scope and only directly responds to issues with the core Joomla! CMS and Framework, as well as processing reports regarding the *.joomla.org network of websites
`

**Comment by Sandra97** [comment]
Permissions of the page changed.
You can all edit it if you want.
If nobody wants to edit it, we will archive and block it.

**Comment by Hutchy68** [comment]
>inaccurate i am afraid. JSST are still the JSST who deal with CORE at https://developer.joomla.org/security.html
The VEL on vel.joomla.org deal with vulnerable extensions.

Based on all the communications of almost 5 years ago and the cross work you (@mandville) did I thought they basically worked in sync. My apologies, but all I knew was there were 2 people who always watched and sent me PMs(which I still have) on J! forum. The jist was do not edit those pages nor were they to be edited by "JDocs" editors.

>To be clear, Phil doesnt mean @PhilETaylor here, it means, Phild whoever that is!

If I meant you I would have said @PhilETaylor. I don't think Phil D is here an only but is active on forums. Sorry, if that wasn't clear.

> I dont do wiki's I hate them.

Great attitude

>The JSST operates with a limited scope and only directly responds to issues with the core Joomla! CMS and Framework, as well as processing reports regarding the joomla.org network of websites

From your page -

>## Goals
>
>1. Investigate and respond to reported vulnerabilities in the Joomla! CMS, Framework, and joomla.org websites.
>2. Execute code reviews prior to release to identify new vulnerabilities.
>3. Provide public presence regarding security issues.
>4. Help the community understand Joomla! security. 

Hmm, looks like # 4  might be in conflict with your statement *"I don't believe the editing of Joomla Wiki is the job of the JSST."* If you believe, *"Its certainly not in the public remit"* then we have an issue solve. 

So, let's solve the issue.

1. JSST takes control of the wiki pages
2. JSST decides to host the pages on developer.joomla.org
3. We archive pages as is and let users ask questions on J! Forums on server set ups and best practices.

**Comment by Webdongle** [comment]
Apart from one broken link and a section called **Use PHP5** ... what is out of date in that page ?

imho 

1. The page should be locked from general editing to stop everyone and their dog from mucking it up
2. Whoever is in charge of the wiki should find someone who is able to edit it with the correct information ... then allow them editing rights

This shows the weakness in using a wiki.  If Joomla docs was a Joomla site then security could be a Category and allowing/restricting editing could be achieved more accurately.

Bad call for the wiki team to make the page editable by everyone and their dog.  And all the rhetoric from the wiki team is just a reluctance to admit that it was a mistake to change the edit rights !!!

**Comment by Sandra97** [comment]
@Webdongle Seems you don't know a lot about the Wiki. Anyway, I don't have time to waste in useless talk

**Comment by Webdongle** [comment]
@Sandra97 
My post was not useless talk and I feel strongly about who should be allowed to edit security pages in Joomla docs.  Please do not try to dismiss my concerns by using flippant comments.

**Comment by Sandra97** [comment]
We are checking every single edit on JDocs every single day and reverting them when needed. 
If it wasn't the case, JDocs today would be just a site full of spam. 
We opened this page yesterday so that Claire can update it (and she did some edits). We'll reprotect it when needed.
It's not because a page is open for edits that it means we will accept edits. 
The principle of a wiki is to be open for all edits. Users are maintainers. And a few people including me are the gate keepers.

**Comment by Webdongle** [comment]
> We are checking every single edit on JDocs every single day and reverting them when needed.
If it wasn't the case, JDocs today would be just a site full of spam
Great ... so you will know if an edit is factually correct and if the person editing it knows more than you about security ?

> We opened this page yesterday so that Claire can update it (and she did some edits). We'll reprotect it when needed.
My point exactly ... with Joomla you could just have added her to a User Group.  That would negate the need to allow everyone and their dog to edit the page ... which would mean less (possible) edits to check

> It's not because a page is open for edits that it means we will accept edits.
The principle of a wiki is to be open for all edits. Users are maintainers. And a few people including me are the gate keepers.
I understand the concept of a wiki and understand that edits do not have to be accepted.  My point is that appointing different editing rights per Category is better than making a page editable by everyone just so one person can edit it.  But that is my opinion.

**Comment by uglyeoin** [comment]
@Webdongle as they are the gatekeepers they should be able to judge whether the workload is too much.  

Although I see where you're coming from, not everyone and their dog should be able to edit, I am everyone and his dog, I'm not a security expert.  But I wanted to update the PHP version to 7, which is a small change, but would have been helpful enough.  

I think having and encouraging contributors is important we can't expect a small team to manage the entire docs and keep them up-to-date and the JSST have surely got plenty to do if someone helps them out a bit we should not turn it down.  So long as it's moderated surely that is ok?

@PhilETaylor calling people idiots is offensive.  People don't know what they don't know.  You can politely disagree with people and state your qualifications without showing such disdain.

**Comment by mandville** [comment]
clarification : the main page that was requested locked/restricted at the time was the checklist 7 and the original vel page (on docs.joomla.org)
currently i have altered the php 4/5 to 7 and removed the link that was leading to a 18+ website~
feel free to add in the discussions page any other suggestions if the page is locked

**Comment by Webdongle** [comment]
> @PhilETaylor calling people idiots is offensive. People don't know what they don't know. You can politely disagree with people and state your qualifications without showing such disdain.

@uglyeoin 
I totally agree with Phil ... there are a lot of idiots who think they know when they don't.  I for one make many mistakes with my understanding of things but am aware that I do ... so I rarely edit the wiki.


> I think having and encouraging contributors is important we can't expect a small team to manage the entire docs and keep them up-to-date and the JSST have surely got plenty to do if someone helps them out a bit we should not turn it down. So long as it's moderated surely that is ok?

It's the (accuracy of) method of moderating the edits that I question not the moderators themselves.    My point is that instead a a few people moderating all edits (including subjects they have little or no knowledge of) ... moderating should be delegated per category to people who have the relevant knowledge.  Those moderators (with their specialised knowledge) could accurately asses suggested edits/new pages.

Using that type of hierarchy cuts down on human error and is more efficient than un-specialised people moderating subjects that are outside of their skill set.

In short edit permissions should not have need to be changed in order for Claire to edit the page.   It is Claire that should have absolute control of who posts (and what is posted) in regards to security pages.  That hierarchy can easily be set in Joomla but (as shown by the need to change edit permissions) is not easily (if at all ) possible with a wiki.

I make no apologies for my apparent arrogance because that is my nature.  But I feel sorry for the people who are unable to understand what I (and many others) understand about the inaccuracies that occur due to the structure of wiki's.  There are many examples of that not just the page in question and also a lot of the problems in the forum are as a result of users following incorrect information from the wiki.

In addition to that ... many of us who help out in the forum have extra work because our advice is often contradicted by some idiot who quotes an incorrect wiki page.  We then have to spend some time explaining why the page is incorrect.  Being able to edit that wiki page is often no advantage because the page is so wrong it needs a major edit.

**Comment by mbabker** [comment]
Correcting some of the system ignorance, Mediawiki does indeed have user
groups and ACL so referencing those features and using that as a "Joomla is
better" argument is a mute point.
-- 
- Michael Please pardon any errors, this message was sent from my iPhone.

**Comment by uglyeoin** [comment]
@Webdongle I'm not arguing that you and @PhilETaylor  have superior knowledge, I'm just saying it's impolite to call people idiots in an public forum.  It's very condescending, and probably against CoC.  That they are following official Joomla! documentation would seemingly make them educated fools, but we educated them. I guess that makes us idiots too.  

I don't really understand your point, you seem to be saying we spend hours correcting loads of idiots but it will take too long to update the wiki.  I can't believe it is 100% inaccurate some of the stuff must still be relevant, some can probably be deleted which doesn't take long.

If you are not prepared to update the wiki, then someone else will have to.  If it's wrong and people are following wrong advice we either remove it or update it.  You say you want the correct people to update it, but it seems as though you may be the correct people and yourself and Phil are unwilling.  That means we simply have to do the best we can, we don't live in an ideal world, and we run on volunteers.

The questions are:

1. Is no documentation better than partially correct?
2. Do we have a responsibility to educate our users (correctly)?
3. Would Joomla! suffer as a brand with bad security type of labels if there is no documentation
4. Do we have a list of the most qualified Joomla! volunteers in order of most security aware that we can work through until we find the best match & most willing to update this wiki
5. Should we set up a process whereby this document is monitored once a year (for example)
6. Does calling less educated users idiots alienate them instead of getting the message we want to get across which is improving their education and the overall security of Joomla! websites.

I'm not the right person to answer these questions, I'm probably not the right person to ask them. Just trying to find a resolution.

**Comment by Hutchy68** [comment]
First, I must apologize to @uglyeoin. Thanks for wanting to improve documentation. There are a lot of community members who should follow your initiative. 

The recent [Open Source Survey](http://opensourcesurvey.org/2017/) spells it out plainly. **Incomplete or outdated documentation is a pervasive problem, observed by 93% of respondents, yet 60% of contributors say they rarely or never contribute to documentation. When you run into documentation issues, help a maintainer out and open a pull request that improves them.** In JDocs case, update the page, if you can. The issue specific to this case was the information was perceived to be closely guarded(even by me) as well as it should be. We have dealt with it temporarily, @mandville thanks for updating the page. 

>In addition to that ... many of us who help out in the forum have extra work because our advice is often contradicted by some idiot who quotes an incorrect wiki page. We then have to spend some time explaining why the page is incorrect. Being able to edit that wiki page is often no advantage because the page is so wrong it needs a major edit.

This statement just shows your lack of understanding for applying a **bandage vs. fixing the problem**. 

- Bandage == repeating yourself over and over
- Fix the problem == point to the answer and save yourself some time

@Webdongle if you have nothing to add to solve the issue I posted earlier, you are wasting everyone's time with negative comments. The goal is to solve the issue I presented earlier.

Repeating the issue (and yes we can ACL a JSST team for security pages)

>1. JSST takes control of the wiki pages
>2. JSST decides to host the pages on developer.joomla.org
>3. We archive pages as is and let users ask questions on J! Forums on server set ups and best practices.

**Comment by mbabker** [comment]
> JSST decides to host the pages on developer.joomla.org

I can't speak for David, but personally I'd have no problem expanding the Security section on that site with more information.

**Comment by Hutchy68** [comment]
Perfect! When they are setup, all I need is the urls. I can archive those pages and do rewrites to send to JSST pages. Thanks @mbabker

**Comment by Webdongle** [comment]
@mbabker 

> Correcting some of the system ignorance, Mediawiki does indeed have user groups and ACL so referencing those features and using that as a "Joomla is better" argument is a mute point.
Great ... then Claire can be given edit permission without everyone else being able to edit it ?  And newly created pages by new wiki users can be unpublished until checked thoroughly in order to prevent pages that advice updating with Release Candidates ?

@uglyeoin 
Phil has superior knowledge of server/site security ... I don't but I don't

**Comment by mbabker** [comment]
> Great ... then Claire can be given edit permission without everyone else being able to edit it ?

Right, if the docs team chooses to set that up.  It sounds like there's a nudge to consolidate security advice into the security center on the dev site, I'm personally OK with that but I think VEL & JSST need to work out what'll be best for that instead of either myself or the docs team trying to push it one way or another.

> And newly created pages by new wiki users can be unpublished until checked thoroughly in order to prevent pages that advice updating with Release Candidates ?

Theoretically if there's a publishing workflow in Mediawiki then yes, but I'm not familiar with the system well enough to know if that exists (AFAIK it's basically either page exists, page was deleted, or page doesn't exist).  That also means though there would need to be more content reviewers involved in the process and that might be too disruptive of a change to implement.

**Comment by Webdongle** [comment]
@mbabker 

> Right, if the docs team chooses to set that up. It sounds like there's a nudge to consolidate security advice into the security center on the dev site, I'm personally OK with that but I think VEL & JSST need to work out what'll be best for that instead of either myself or the docs team trying to push it one way or another.

That would be great because I for one would like to be assured that 'official Joomla security advice was written by (and/or reviewed by) someone who knows what they are doing when it comes to security.


> Theoretically if there's a publishing workflow in Mediawiki then yes, but I'm not familiar with the system well enough to know if that exists (AFAIK it's basically either page exists, page was deleted, or page doesn't exist). That also means though there would need to be more content reviewers involved in the process and that might be too disruptive of a change to implement.

'_publishing workflow'_ ... ahh that sums it up completely.  That is what is missing and that is something that would be easily implemented using Joomla without the need for extra reviewers.  But "_page exists, page was deleted, or page doesn't exist_" is clearly allowing incorrect information to be added to the wiki.  And there are a lot of those and the number keeps growing.

Hopefully this discussion will lead at least to security information being accurate.

**Comment by mbabker** [comment]
> That is what is missing and that is something that would be easily implemented using Joomla without the need for extra reviewers.

Not necessarily.  If we had a documentation site built on Joomla where any user could contribute, said users would still need to register an account, go to the create content area, write their page, and said page be saved in an unpublished state pending a editor/manager review and publishing it.  So again, the workflow is not much different, it is simply a different software stack.  The main differences honestly is that a Wiki is purposefully designed for anyone to be able to contribute whereas generally you're setting up a Joomla installation with a privileged publishing workflow.

**Comment by Webdongle** [comment]
> , write their page, and said page be saved in an unpublished state pending a editor/manager review and publishing it. So again, the workflow is not much different

Big difference between an unchecked new page being held unpublished until reviewed fully by a person who understands that part of the subject ... and an unchecked new page being published immediately and sitting there while it is looked over by someone who might (or might not) be experienced in that area.  The latter allows more chance of incorrect information posing as 'Official documentation'.  Not a big issue in many cases but could be disastrous for many users when it is a security page.

**Comment by PhilETaylor** [comment]
Other than "Joomla Best Practice" I don't believe its the role of the Joomla Project to educate Joomla users on general internet/web hosting/server security. 

To quote someone else, **_"Stick to the code!"_**

**Comment by mbabker** [comment]
My main point is the software is not the problem here, and you've made reference a couple of times that "Joomla would handle this more efficiently than Mediawiki" in essence.  The same types of workflow problems can exist whether we are using Mediawiki, Joomla, phpBB, or any other software stack in our inventory or at our disposal.
